### ISSUE TITLE
FIX(-1) fails on gcc 6.0.0

### ISSUE THREAD

**Issue by johnwcowan** [cisco/ChezScheme#1]
Left shifting a negative number is undefined behavior in C.  gcc 6.0.0 on x86_64 Linux prints a warning for this, even though all sane machines do the Right Thing.  -Werror promotes this warning to an error, so the build fails.

I patched around this by simply removing -Werror from the Mk* files.  However, recent C compilers take undefined behavior as a license to miscompile things, so the FIX macro needs to be improved to do the necessary casts to unsigned and back.  Here's an example of miscompiling:

```
uint32_t shiftleft(uint32_t v, uint8_t n)
{
  if (n >= 32)
    v=0;
  return v<<n;
}
```

may wind up being compiled without the `if` statement, because it assumes that `n >= 32` can never be true, since if it were true it would lead to undefined behavior.

**Comment by jonathanyc** [comment]
@dybvig Thanks so much for releasing the source! Would something like this fix the issue?

```diff
diff --git a/boot/a6osx/scheme.h b/boot/a6osx/scheme.h
index c97296a..4d72379 100644
--- a/boot/a6osx/scheme.h
+++ b/boot/a6osx/scheme.h
@@ -127,7 +127,7 @@ EXPORT void Sset_cdr PROTO((ptr, ptr));
 EXPORT void Svector_set PROTO((ptr, iptr, ptr));
 
 /* Constructors */
-#define Sfixnum(x) ((ptr)(uptr)((x)<<3))
+#define Sfixnum(x) ((ptr)((uptr)(x)<<3))
 #define Schar(x) ((ptr)(uptr)((x)<<8|0x16))
 #define Snil ((ptr)0x26)
 #define Strue ((ptr)0xE)
diff --git a/c/prim5.c b/c/prim5.c
index c4d1031..2184456 100644
--- a/c/prim5.c
+++ b/c/prim5.c
@@ -1686,8 +1686,8 @@ static void s_test_schlib() {
   INT test = 0;
   I32 n1 = 0x73215609;
   I64 n2 = n1 * 37;
-  I32 n3 = (I32)-1<<31;
-  I64 n4 = (I64)-1<<63;
+  I32 n3 = (U32)-1<<31;
+  I64 n4 = (U64)-1<<63;
   I32 n5 = -1;
 
   SCHLIBTEST(Sinteger_value(Sinteger(n1)) == n1)
```

**Comment by jonathanyc** [comment]
Looks like this was fixed in https://github.com/cisco/ChezScheme/commit/42e6fed96d69fa17cfcd9cdcec101aaa36ba4512. Awesome!

**Comment by dybvig** [comment]
Thanks for the report and comments.  The latest commit should fix the prim5.c warnings.  I haven't installed gcc 6.0.0 to verify.

**Comment by jonathanyc** [comment]
The latest commit fixes the prim5.c warnings at least on on my computer. Thanks!
