### ISSUE TITLE
Strings make from (make-string) seems can't be rewrite by recv function in c

### ISSUE THREAD

**Issue by Saigut** [cisco/ChezScheme#103]
Sorry, I am new to scheme, maybe here is not the place for my question :(   But I really want the answer.

I tried the socket example code in the examples/ directory.
But the result is not as expected. 
Expected is:
```
server:
> (put '(let ((x 3)) x))
> (get)
client:
3
>
server:
```
but mine:
```
server:
> (put '(let ((x 3)) x))
> (get)
client:

server:
```
I tested the single c-read:
```
(define buf (make-string 10)
(c-read client-sock buf 10)
```
then I send 10 characters from client, c-read indeed received them, but content in buf Unchanged.
So I wonder if the string create by make-string can't be filled by c-read(wrapper of recv in c).

And then I change the definition of c-read to:
```
(define c-read
  (foreign-procedure "c_read" (integer-32 u8* integer-32)
    integer-32))
```
changed string to u8*.
and then tried:
```
(define buf (make-bytevector 10)
(c-read client-sock buf 10)
```
and then c-read received data too, and content in buf Changed.

so, strings make from (make-string) seems can't be rewrite by recv function in c?

**Comment by Saigut** [comment]
I find the answer in Chez Scheme Version 9 User's Guide :P
At Section 4.2. 
```
utf-8: The argument must be a Scheme string or #f. For #f, the null pointer (0) is passed to the foreign procedure. A string is converted into a bytevector, as if via string->utf8, with an added null byte, and the address of the first byte of the bytevector is passed to C. The bytevector should not be retained in foreign variables or data structures, since the memory management system may relocate or discard them between foreign procedure calls, and use their storage for some other purpose.

string: This type is an alias for utf-8.
```

**Comment by Saigut** [comment]
It seems that the examples need to update :P

**Comment by jltaylor-us** [comment]
Opened PR #105 to update this example.
