### ISSUE TITLE
ARM native emitter, illegal cache flushing instruction

### ISSUE THREAD

**Issue by evilbinary** [cisco/ChezScheme#107]
When i compile chez to android native so file and run on android with dynamic so file ,it went wrong.

10-16 11:16:49.478 30549-30549/? I/native-scm: init...4
10-16 11:16:49.479 30549-30549/? I/native-scm: Sscheme_init
10-16 11:16:49.479 30549-30549/? I/native-scm: Sscheme_init end
10-16 11:16:49.479 30549-30549/? I/native-scm: Sregister_boot_file
10-16 11:16:49.479 30549-30549/? I/native-scm: Sregister_boot_file end
10-16 11:16:49.479 30549-30549/? I/native-scm: Sbuild_heap
10-16 11:16:49.479 30549-30549/? I/native-scm: Sbuild_heap main_init
10-16 11:16:49.480 30549-30549/? I/native-scm: Sbuild_heap load
10-16 11:16:49.480 30549-30549/? I/native-scm: Sbuild_heap load 1
10-16 11:16:49.480 30549-30549/? I/native-scm: S_boot_read /data/local/tmp/chez/petite.boot 0x6fe8e608
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: uf read
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 3f
10-16 11:16:49.480 30549-30549/? I/native-scm: faslin
10-16 11:16:49.480 30549-30549/? I/native-scm: S_flush_instruction_cache
10-16 11:16:49.480 30549-30549/? I/native-scm: fasl_entry-- end
10-16 11:16:49.480 30549-30549/? I/native-scm: Sbuild_heap load 2
10-16 11:16:49.480 30549-30549/? I/native-scm: S_boot_read /data/local/tmp/chez/petite.boot 0x6fe8e608
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: uf read
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 97
10-16 11:16:49.480 30549-30549/? I/native-scm: faslin
10-16 11:16:49.480 30549-30549/? I/native-scm: S_flush_instruction_cache
10-16 11:16:49.480 30549-30549/? I/native-scm: fasl_entry-- end
10-16 11:16:49.480 30549-30549/? I/native-scm: S_boot_read /data/local/tmp/chez/petite.boot 0x6fe8e608
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: uf read
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread 1
10-16 11:16:49.480 30549-30549/? I/native-scm: gzread d6
10-16 11:16:49.480 30549-30549/? I/native-scm: faslin
10-16 11:16:49.480 30549-30549/? I/native-scm: S_flush_instruction_cache
10-16 11:16:49.480 30549-30549/? I/native-scm: fasl_entry-- end
10-16 11:41:58.699 32023-32023/? I/native-scm: Error: invalid memory reference
10-16 11:41:58.713 917-1342/system_process I/ActivityManager: Process org.evilbinary.chez (pid 32023) has died.

**Comment by Saigut** [comment]
How you compile chez? Are you using c language toolchain for android?

**Comment by evilbinary** [comment]
@Saigut  yeah~,that's right.

**Comment by evilbinary** [comment]
oh,solve this problem.
