### ISSUE TITLE
How to load irrespective of working directory?

### ISSUE THREAD

**Issue by Wysaard** [cisco/ChezScheme#109]
This is more a question than a real 'issue'; but I couldn't find it anywhere, and couldn't get any answers on regular support sites like stackoverflow, so I don't really know where else to ask.

Say I have a program in `~/documents/myproject/myprogram.ss`, and this program imports the file `mydefinitions.ss` in the same directory, with `(load "mydefintions.ss")`. Then this program only works if ran from `~/documents/myproject/`. If I run it in `~/documents/` for example, it will look for `~/documents/mydefinitions.ss` instead. How can I make it such that I can load the program into the interpreter, and it looks for it's own `load`s relative to where the program is, instead of my current directory when running the interpreter?

**Comment by jltaylor-us** [comment]
I guess waiting for 12 hours on a question posted on Friday night counts as "couldn't get any answers" these days.  I've posted an answer to your stackoverflow question.
http://stackoverflow.com/questions/40186213/how-to-import-files-relative-to-main-file-instead-of-current-directory-chez/40193812#40193812

To summarize my recommendation from the various options presented there, I'd make `mydefinitions.ss` a library, include it via `import`, and launch Chez with the `--libdirs` option to let it know where to look for libraries.  If for some reason I thought that was going to be too much typing or that I'd forget how to do it then I'd make a shell script for it.

**Comment by Wysaard** [comment]
Sorry if it seems a little impatient, but most of the time if you don't get an answer within a few hours, you're not gonna get one at all, at least in my experience. Thank you very much for your answer though, I'll see which of the proposed workarounds works best for me, but I at least know now that it's not possible without a workaround, something I was not sure of.
