### ISSUE TITLE
customize libdirs

### ISSUE THREAD

**Issue by LuKC1024** [cisco/ChezScheme#113]
How can I set `library-directories` to `/usr/local/lib/scheme/` system-wide?

I am using GNU/Linux.

**Comment by evilbinary** [comment]
scheme --libdirs 用这个就可以了，你是中国人吧。

[evil]$scheme --libdirs /usr/local/lib/scheme/
Chez Scheme Version 9.4.1
Copyright 1984-2016 Cisco Systems, Inc.

/> (library-directories)
(("/usr/local/lib/scheme/" . "/usr/local/lib/scheme/"))
/>

**Comment by evilbinary** [comment]
scheme --libdirs 用这个就可以了，你是中国人吧。

[evil]$scheme --libdirs /usr/local/lib/scheme/
Chez Scheme Version 9.4.1
Copyright 1984-2016 Cisco Systems, Inc.

/> (library-directories)
(("/usr/local/lib/scheme/" . "/usr/local/lib/scheme/"))
/>

**Comment by evilbinary** [comment]
scheme --libdirs 用这个就可以了，你是中国人吧。

[evil]$scheme --libdirs /usr/local/lib/scheme/
Chez Scheme Version 9.4.1
Copyright 1984-2016 Cisco Systems, Inc.

> (library-directories)
(("/usr/local/lib/scheme/" . "/usr/local/lib/scheme/"))
>

**Comment by evilbinary** [comment]
scheme --libdirs 用这个就可以了，你是中国人吧。

[evil]$scheme --libdirs /usr/local/lib/scheme/
Chez Scheme Version 9.4.1
Copyright 1984-2016 Cisco Systems, Inc.

\>(library-directories)
\>(("/usr/local/lib/scheme/" . "/usr/local/lib/scheme/"))

**Comment by KelvinLu1024** [comment]
是的。谢谢！

Thank you!
