### ISSUE TITLE
environment variable CHEZSCHEMELIBDIRS is ignored

### ISSUE THREAD

**Issue by KelvinLu1024** [cisco/ChezScheme#114]
I am using bash.

```
$ CHEZSCHEMELIBDIRS=/usr/local/lib/scheme-r6rs::/usr/local/lib/scheme-r6rs
$ scheme
Chez Scheme Version 9.4
Copyright 1984-2016 Cisco Systems, Inc.

> (library-directories)
(("." . "."))
> 
```

**Comment by jltaylor-us** [comment]
You are not actually setting the `CHEZSCHEMELIBDIRS` environment variable in the scheme process unless you have already marked it for export from the shell.  You can set it for just the invocation of scheme like this:
`CHEZSCHEMELIBDIRS=/usr/local/lib/scheme-r6rs::/usr/local/lib/scheme-r6rs scheme`
or use the shell's `export` form to have it set in all processes spawned by that shell.

**Comment by KelvinLu1024** [comment]
Thank you!

**Comment by Saigut** [comment]
@KelvinLu1024 Why not close solved issue?
