### ISSUE TITLE
typo in TeX-generated PDFs

### ISSUE THREAD

**Issue by dine2014** [cisco/ChezScheme#115]
In the PDF documentations, code is set in a typewriter font (namely cmtt), but the tildes, curly braces, and underscores within code are in the roman type (cmr), making them out of harmony.

**Comment by dybvig** [comment]
These substitutions are among several made by design via the scheme.sty style files in the csug and release_notes directories due to problems, at least historically, with various characters in the cmtt font.

**Comment by dybvig** [comment]
I just tried the tt versions and they no longer seem to be mistreated by cmtt, so Ive updated the style files accordingly.  Thanks for the suggestion.
