### ISSUE TITLE
Why different eol style of transcoder behave same for input port?

### ISSUE THREAD

**Issue by Saigut** [cisco/ChezScheme#118]
When us use open-bytevector-input-port with a transcoder to create a textual input port , If eol style of that transcoder is not none, then get-line that port will behave all  the same. But I think they shouldn't be.

From here : http://www.scheme.com/tspl4/io.html#./io:s66 , we can see, the eol style have several types.
From my understand, the lf eol style will only recognize \n as line ending,  the cr eol style will only recognize \r as line ending, and crlf eol style will only recognize \r\n as line ending.

But the fact is, whatever eol type of lf, cr, crlf you are using, get-line recognize \r, \n, and \r\n  all is as line ending!

Here is my Code:

```
(define buf-transcoder-ori (make-transcoder (utf-8-codec) 'none 'raise))
(define header-buf (string->bytevector "aaaa\r\nbbbb\r\ncccc\rdddd\neeee" buf-transcoder-ori))

(define buf-transcoder (make-transcoder (utf-8-codec) 'lf 'raise))
(define textual-input-port (open-bytevector-input-port header-buf buf-transcoder))

(get-line textual-input-port)
(get-line textual-input-port)
(get-line textual-input-port)
(get-line textual-input-port)
(get-line textual-input-port)
```

You can change eol style of buf-transcoder to any other for testing. They all behave same except none, just as that ducument said.

From my point, when you say lf is line ending, then \n is the only line ending, \r and \r\n shouldn't be. When you say crlf is line ending, then  \r\n is the only line ending, \r and \n shouldn't be. Other case is same.

So why does those eol style just have no meaning for input port?

**Comment by jltaylor-us** [comment]
> From here : http://www.scheme.com/tspl4/io.html#./io:s66 , we can see, the eol style have several types.
> From my understand, the lf eol style will only recognize \n as line ending, the cr eol style will only recognize \r as line ending, and crlf eol style will only recognize \r\n as line ending.
> 

The documentation says otherwise.  From http://www.scheme.com/tspl4/io.html#./io:h0

> The eol style affects input and output operations differently. For input, any eol style except `none` causes each of the line-ending characters or two-character sequences to be converted into a single line-feed character. For output, any eol style except `none` causes line-feed characters to be converted into the specific one- or two-character sequence associated with the eol style. In the input direction, all eol styles except `none` are equivalent, while in the output direction, the eol styles `none` and `lf` are equivalent.

This also matches the text following `eol-style` in the r6rs standard library specifications. http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-9.html

**Comment by Saigut** [comment]
r6rs standard library specifications mentioning this the same as The Scheme Programming Language do. Maybe this is to achieve biggest compatibility for reading files which be edited in different line ending, so not strictly restrict the form of line ending while inputting.

>  For a textual input port, any eol-style symbol other than none means that all of the above line-ending encodings are recognized and are translated into a single linefeed. For a textual output port, none and lf are equivalent.
