### ISSUE TITLE
Chez Scheme on Solaris OS

### ISSUE THREAD

**Issue by zonick** [cisco/ChezScheme#120]
Hello !
5 years ago I bought Chez Scheme 8.4 for Solaris 11 OS x86_64 (ta6s2) and (as bonus) Chez Scheme 8.3 for Solaris SPARC (tsp64). Worked nice for me and my learners on Intel and SPARC, Thank You !
Now, I found open source Chez Scheme 9.4, but without support Solaris OS. Despite the fact that the source files have Solaris specifics. I tried to create into the directory 'boot' subdirectory 'ta6s2' and copy 'petite.boot', 'scheme.boot' and 'scheme.h' files from 8.4 release into it. Poorly ((( I created/edited 'equated.h' from linux distr - poorly ((( Now the question - Why don't you make Solaris distribution ? Solaris isn't popular or what ? If you need help to do this, then I am willing to participate. I can even give one of my native (not virtual) Solaris 11.3 server for this. Via 'ssh'. With 'developerstudio' 12.5 c/c++ sun/oracle compilers or 'gcc'. Let's try to do it... Now SPARC not important to me because I have very old Sun SPARC servers (SunFire V210) without support Solaris 11. Now I am only interested x86_64 arch. When I buy a Oracle SPARC T or M based servers, then go back to the tsp64 release )))

Thank You.
--
sorry for bad english

**Comment by zonick** [comment]
Issue resolved. Now Chez Scheme can run on Oracle Solaris 11 OS (x86_64). And on SPARC too, I think...

Sun Meddle ~ # uname -a
SunOS Meddle 5.11 11.3 i86pc i386 i86pc

Sun Meddle ~ # isainfo -v
64-bit amd64 applications
	avx xsave pclmulqdq aes movbe sse4.2 sse4.1 ssse3 amd_lzcnt popcnt tscp 
	ahf cx16 sse3 sse2 sse fxsr mmx cmov amd_sysc cx8 tsc fpu efs rtm hle 
	bmi2 avx2 bmi1 f16c fma rdrand

Sun Meddle ~ # chez
Chez Scheme Version 9.4.1
Copyright 1984-2016 Cisco Systems, Inc.

> (+ 9 4 1)
14
> 

Thanks to all )))

**Comment by akeep** [comment]
For the record, Chez Scheme no longer has support for sparc or sparc64 processors, though it could be ported to support it again.

When we re-wrote the compiler between versions 8.x and 9.0, we completely replaced the old code generator and left out support for some of the older platforms.

As you note, however, we do support Solaris on x86 and x86_64.

**Comment by zonick** [comment]
Thanks
