### ISSUE TITLE
Exception information of subthread doesn't printed on console when load source file from command line

### ISSUE THREAD

**Issue by Saigut** [cisco/ChezScheme#121]
I find exception information of subthread will not printed on console when load using "scheme ./fils.ss", but if you just open a scheme and run the same code, then the exception information will be printed.

These code will raise Exception:
```
(define (f)
  (printf "I am in subthread.~%")
  (if (#f)
      1
      2))

(fork-thread f)
```

If you save the code in a file, here say "file.ss", then run:
```
scheme "./file.ss"
```
The exception information will not be printed.

But if you open a scheme interaction environment, and type the code and run:
```
scheme
> (define (f)
  (printf "I am in subthread.~%")
  (if (#f)
      1
      2))
> (fork-thread f)
```
Now the exception information will be printed.

I am confusing with these different behavior. And such behavior make it difficult to debug multithread program for me, because I use command line to load file for convenient. 

And I haven't find out how to print the exception information of subthread when load file from command line.
Is there any way to do it?

**Comment by dybvig** [comment]
The exception state inherited by the forked thread from the main thread within the call to `load` is probably causing the problem.  You might try resetting the exception state around the call to `fork-thread` as follows:

```
(parameterize ([current-exception-state (create-exception-state default-exception-handler)])
  (fork-thread f))
```

If that works, we should consider having all threads start with a reset exception state, since it's probably often a bad idea for a forked thread to inherit exception state.

**Comment by Saigut** [comment]
I tested to `load` the "file.ss":
```
scheme
> (load "./file.ss")
```
It can print the exception information, but it run into an infinite loop, print the exception endlessly.

Then I changed `(fork-thread f)` to
```
(parameterize ([current-exception-state (create-exception-state default-exception-handler)])
  (fork-thread f))
```
All the three methods running the code behave as expected.

**Comment by dybvig** [comment]
You might want to read the description of thread safety at the start of Chapter 15 of the user's guide if you haven't already.  Printing should be thread-safe if each thread writes to a different port or if the port is unbuffered, as is the initial value of `(current-output-port)` to which `pretty-print` writes when no port argument is provided.  `pretty-print` can block trying to write to a slow output device, but it should not block forever unless the output device is a full pipe or socket, and it should not prevent other threads from continuing to run.  bytevector->string should always be thread-safe and should never block.  So I suspect neither is the cause of your problem.  Is it possible your main thread is exiting before the thread has a chance to finish or that an error in the code is being suppressed as you described in [this issue](https://github.com/cisco/ChezScheme/issues/121)?
