### ISSUE TITLE
arm version foreign call pass float with wrong value

### ISSUE THREAD

**Issue by evilbinary** [cisco/ChezScheme#124]
I write function  and on arm version foreign call i pass wrong value

void glut_test_rotatef(float angel,float x,float y,float z){
    float zz=1.234234;
    LOGI("angle %lf %f %f %f %f",angel,x,y,z,zz);
}
 (define glut-test-rotatef
       (foreign-procedure "glut_test_rotatef" (float float float float) void))

(glut-test-rotatef 20.1 4.3 0.0 1.2)

The result is :
angle 4004753556512589601421700104192.000000 4004760810067507289196748341248.000000 4004765645770785747713447165952.000000 145632115491920414816128204800.000000 1.234234

**Comment by evilbinary** [comment]
I found that in arm cpu  when comes to float  it went worng.

Chez Scheme Version 9.4.1
Copyright 1984-2016 Cisco Systems, Inc.

> 2.3

Exception: invalid memory reference.  Some debugging context lost
Type (debug) to enter the debugger.
>

**Comment by cjfrisz** [comment]
The ARM backend for Chez Scheme was developed on a Raspberry Pi 2 running the ARMv7-A instruction set. ARM processors running other versions of the ARM instruction set or using a floating point coprocessor different from the one used for the Pi may not work properly with the current version of the ARM support for Chez.

Can you provide more information about the processor you're trying to target?

**Comment by evilbinary** [comment]
I'm using  

processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc0f
CPU revision	: 3

and this

Processor	: ARM926EJ-S rev 5 (v5l)
BogoMIPS	: 599.65
Features	: swp half thumb fastmult vfp edsp java 
CPU implementer	: 0x41
CPU architecture: 5TEJ
CPU variant	: 0x0
CPU part	: 0x926
CPU revision	: 5

Hardware	: ARM-Versatile PB
Revision	: 0000
Serial		: 0000000000000000

**Comment by cjfrisz** [comment]
Which operating system are you using? After my initial response, I remembered that we developed on a Fedora variant for ARM, and based on some preliminary research, it seems possible that other flavors of Linux might have different C calling conventions from the ones we implemented. In particular, it seems that Debian on ARM made a switch at some point from a mixture of hardware and software floating point with the armel sub-ABI (source [here](https://wiki.debian.org/ArmEabiPort)) to required hardware floating point support with the armhf ABI (source [here](https://wiki.debian.org/ArmHardFloatPort)).

Upon reflection, it seems to me that your "invalid memory reference" error is likely more consistent with mismatched calling conventions, as would be the case with conflicting Fedora/Debian ABIs, than with incompatible floating point instructions, which would probably result in an "illegal instruction" error. If this is the case, the only solution would be implement the calling conventions for your operating system.

**Comment by evilbinary** [comment]
I'm using Linux debian-armel 3.2.0-4-versatile #1 Debian 3.2.82-1 armv5tejl GNU/Linux
and android os (ARMv7 Processor rev 3).

**Comment by evilbinary** [comment]
Solved this problem by compiling with armhf version.

**Comment by cjfrisz** [comment]
Excellent! I'm glad that worked.

**Comment by ldfours** [comment]
I've got an error when compiled with the gcc-6.3.0 (current debian stable, armhf):
gcc  -Wpointer-arith -Wextra -Werror -Wno-implicit-fallthrough -O2  -rdynamic -o ../bin/arm32le/scheme ../boot/arm32le/kernel.o ../boot/arm32le/main.o -lm -ldl -lncurses -lrt 
/usr/bin/ld: ../boot/arm32le/kernel.o: relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
../boot/arm32le/kernel.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:37: recipe for target '../bin/arm32le/scheme' failed
make: *** [../bin/arm32le/scheme] Error 1

It is compiled successfully with the older gcc-4.6 (debian "weezy") on the same machine.

**Comment by evilbinary** [comment]
yes，grate！
