### ISSUE TITLE
Foreign library cycling dependency exception

### ISSUE THREAD

**Issue by alexzlov** [cisco/ChezScheme#126]
I'm trying to tinker with some graphics stuff involving foreign libraries on windows 10 (glfw.dll and opengl32.dll). I've tried to use the following wrappers:
[https://github.com/dharmatech/chez-gl](url)
[http://github.com/jhidding/chez-glfw](url)
and made a sketch wrapper of my own.
After successfull creation of a window and OpenGL context, I got the wollowing error, while calling some of the OpenGl functions:
1) First attempt to call:
`Exception in foreign-procedure: no entry for "random-foreign-function-name-that-i-did-not-call"`
2) Second attempt to call:
`Exception: cyclic dependency involving invocation of library (library-name-with-foreign-definitions)`
Could somebody point me out to the possible source of this error?

**Comment by dybvig** [comment]
When an exception causes the invocation of a library to be aborted, the library is left in a "currently being invoked" state so an attempt to invoke the library again will result in a cyclic dependency exception.  For example:
```
> (library (A) (export a) (import (chezscheme)) (define a (error #f "oops")))
> (import (A))
> (a)
Exception: oops
> (a)
Exception: cyclic dependency involving invocation of library (A)
```
We might be able to produce a better message, but it's actually tricky to tell the difference between this and a true cyclic dependency.

**Comment by alexzlov** [comment]
A-ha! Many thanks for the explanation. After a more careful look using 
`dumpbin.exe /EXPORTS opengl32.dll`
 I see that many definitions in available wrappers are not present as the exported symbols in the opengl32.dll library and chez is smart enough to point me at it. I need to access them as pointers via wglGetProcAddress and write a more convenient wrapper for such case.
I'm closing this issue as not related to chez-scheme.
