### ISSUE TITLE
Is bytevector->string or pretty-print possibly be causing blocking? Are they thread safe?

### ISSUE THREAD

**Issue by Saigut** [cisco/ChezScheme#127]
When I specially testing bytevector->string or pretty-print, program never blocking in it. But I find it can block the program in my a little complex code. My code is multithread. I can't find out why it block here. So I ask here, is bytevector->string or pretty-print can block the program?

Here is part of my code, and it's be Marked using pretty-print statement:
```
(pretty-print "not eof.")
(pretty-print bv-line)
(bytevector->string bv-line crlf-transcoder)
(pretty-print "bytevector->string can do.")
(set! line #f)
(pretty-print "line set to false.")
```
These code are in a loop, I use set! to update the bv-line bytevector every time.
And in my issue, the program output is:
```
"not eof."
#vu8(65 99 99 101 112 116 45 69 110 99 111 100 105 110 103
     58 32 103 122 105 112 44 32 100 101 102 108 97 116 101 44 32
     115 100 99 104 44 32 98 114)

```

And it just stop at here, you see can the "bytevector->string can do." sentence is not printed, so the code is blocking between (pretty-print bv-line) and  (pretty-print "bytevector->string can do."), but I'm not sure where. And if I type Ctrl+C then that "bytevector->string can do." can be printed, the program go end after do something.

So, Is bytevector->string or pretty-print possible can be blocking?

**Comment by Saigut** [comment]
I did some test just now. It look like both print precedures (include printf pretty-print format) and bytevector->string can cause blocking. I doubt is print precedures thread safe？ and is Chez Scheme stable enough for multithread?

**Comment by dybvig** [comment]
Sorry for the duplicate message---I misplaced the initial response in the earlier thread.

You might want to read the description of thread safety at the start of Chapter 15 of the user's guide if you haven't already. Printing should be thread-safe if each thread writes to a different port or if the port is unbuffered, as is the initial value of (current-output-port) to which pretty-print writes when no port argument is provided. pretty-print can block trying to write to a slow output device, but it should not block forever unless the output device is a full pipe or socket, and it should not prevent other threads from continuing to run. bytevector->string should always be thread-safe and should never block. So I suspect neither is the cause of your problem. Is it possible your main thread is exiting before the thread has a chance to finish or that an error in the code is being suppressed as you described in this issue?

**Comment by Saigut** [comment]
Thanks for your patient on my question!

Now I find that it's more like due to those print procedures causing the thread blocking. The blocking place often have no procedure defined by myself, it's often procedures provided by Chez, and I think print procedures have more possibility than others causing the blocking. Many times after I type Ctrl + C to stop the program, there often some mark words (I set using print procedure) printed before the program quit.
 And when I reduce print statements, the blocking chance also reduce, vice versa. 
Even I assign `current-output-port` parameter to new standard-output-port for each thread, the issue still exist.
```
(parameterize
	       ([current-exception-state (create-exception-state default-exception-handler)]
		[current-output-port (transcoded-port (standard-output-port) none-transcoder)])
			    (fork-thread thread-procedure)))
```
All my print statement are using their default output port. 
Maybe different standard-output-port are in fact the same? And maybe there are some thing which standard-output-port based on are buffered and causing print blocking?

**Comment by dybvig** [comment]
> Many times after I type Ctrl + C to stop the blocking program, there often some mark words (I set using print procedure) printed before the program quit.

That's a clue that the print operation has completed but the buffers have not been flushed.  Try inserting `(flush-output-port)` after each call to `pretty-print`

**Comment by Saigut** [comment]
I tried (flush-output-port) but problem is still exist.

I will reduce the code of my program or test some procedures specially to locate the real issue. Wishing I'm lucky enough to find out the problem.

**Comment by Saigut** [comment]
@dybvig  Hi, I got the minisize code to reproduce my problem!

```
(define (loop-print)
  (do ([i 0 (+ i 1)])
      (#f)
    (printf "count ~a~%" i)))

(do () (#f)
  (get-char (current-input-port))
  (fork-thread loop-print))
```
Run above code, then type a character then press Enter, and then type a character then press Enter again, you could see the print is blocking!
But if you comment the `(get-char (current-input-port))` line, then the code can run as expected, I don't know why.

**Comment by ovenpasta** [comment]
Hi, I have a similar maybe related problem
The following code does run as expected on a shell but not inside emacs repl (run-scheme).
Seems that the printf runs only once each time I enter a command on the repl.

```
(define x 0)
(define (sleep-sec s)
  (sleep (make-time 'time-duration 0 s)))

(begin (fork-thread new-cafe)
       (let loop ()
	 (printf "id:~d x:~d~n" (get-thread-id) x)
	 (sleep-sec 3)
	 (loop)))
```

**Comment by burgerrg** [comment]
If I read the code in s/io.ss correctly, the port handler for the thread-safe input/output console port holds the tc-mutex during the read operation. When another thread wants to write to the output side, it calls the put operation, which waits for the tc-mutex.

**Comment by burgerrg** [comment]
To get the behavior you desire, you would need to independent ports that do not use the tc-mutex.

**Comment by Saigut** [comment]
It seems standard-input-port and standard-output-port use the same tc-mutex, so the input and output would block each other. And in the problem program, it happened to want output after input, input port is waiting, so the output port only can chose waiting for input to be finished.
Is this right?

**Comment by Saigut** [comment]
I tried to set current port to new standard port for each thread, but it don't solve the problem.

```
(define none-transcoder (make-transcoder (utf-8-codec) 'none 'replace))

(define (loop-print)
  (do ([i 0 (+ i 1)])
      (#f)
    (printf "count ~a~%" i)))

(do () (#f)
  (get-char (current-input-port))
  (parameterize ([current-output-port (standard-output-port 'none none-transcoder)]
		 [current-input-port (standard-input-port 'none none-transcoder)])
		(fork-thread loop-print)))
```

**Comment by Saigut** [comment]
I Think the thread lock of standard-output-port(maybe and standard-input-port) is not properly set.
Even I create a new standard-output-port for each new thread, the standard-output-ports seem like can lock each other.
I think standard-output-port and standard-input-port should not have thread lock(I don't know if they really have).

**Comment by Saigut** [comment]
Hi, I'm sorry for I can't locate the key point. Now I still have something to say...

In fact, that "minisize code" I  write above may not be the same problem with my original problem. In the main thread loop, my original code is like this:
```
(do () (#f)
  (client-sd (accept-socket (server-sd)))
  (fork-thread loop-print))
```
So I am not using input port in my origin program, and there is no input at other place.

And for now, my suspicion had move on printf(maybe and pretty-print and fprintf), after I replace them using format, it seems the blocking is hardly to happen.

**Comment by Saigut** [comment]
Hi, I'm sorry for I can't locate the key point.

In fact, that "minisize code" I write above may not be the same problem with my original problem. In the main thread loop, my original code is like this:

(do () (#f)
  (client-sd (accept-socket (server-sd)))
  (fork-thread loop-print))
So I am not using input port in my origin program, and there is no input at other place.

**Comment by Saigut** [comment]
I feel that many thread mutex locks in the implementation of Chez Scheme maybe unnecessary. 
It should be the programmer's responsibility to make the program be thread safe when he create multi threads.
