### ISSUE TITLE
What's the correct way to cross compile

### ISSUE THREAD

**Issue by NalaGinrut** [cisco/ChezScheme#13]
I saw there's arm32 backend in s/ directory. Does it mean Chez can generated arm native code at present? But I failed to configure it for arm platform with ./configure -m=arm32, it says:
```
available machine types: a6le, a6nt, a6osx, i3le, i3nt, i3osx, ta6le, ta6nt, ta6osx, ti3le, ti3nt, and ti3osx
```

It seems that all of machine types are PC(i386/x86_64), so how to take advantage of arm backend?

**Comment by rain-1** [comment]
You could try the cross compile command here https://github.com/cisco/ChezScheme/issues/7

**Comment by NalaGinrut** [comment]
The problem is that there's no ARM in machine types as cross compile target. I'm asking if Chez has already supported ARM backend in a workable way because I saw the related backend code, and if yes, what's the proper way to make it work.

**Comment by NalaGinrut** [comment]
Oh I got the way, say, for a6le platform:
```
./configure
make
./workarea a6le
cd a6le/s
ln -s ../../s/Mf-arm32le .
make -f Mf-cross m=a6le xm=arm32le base=../../a6le
```

Cheers!
Could be better way to not make link by folks, anyway it works.

**Comment by dybvig** [comment]
The cross-compile needs to be run in a workarea for the target-machine type.  Try replacing `a6le` with `arm32le` in `./workarea a6le` and `cd a6le/s`, and skip `ln -s ../../s/Mf-arm32le`.

**Comment by NalaGinrut** [comment]
@dybvig Thanks for hint. However, maybe ```cd a6le/s``` is a typo? Should be ```cd arm32le```, or there's no Mf-arm32le.

 I've tried in these steps:
```
./configure
make
./workarea arm32le
cd arm32le/s
make -f Mf-cross m=a6le xm=arm32le base=../../a6le
```
And compiled Scheme code to arm32le successfully. 

But when I tried to compile arm32le/c in following steps:
```
make C=arm-linux-gnueabihf-gcc
```
It's almost done, but throw error in final step:
```
ld: segment.o: Relocations in generic ELF (EM: 40)
segment.o: error adding symbols: File in wrong format
Makefile:34: recipe for target '../boot/arm32le/kernel.o' failed
make: *** [../boot/arm32le/kernel.o] Error 1
```

How should I fix it?

**Comment by chneukirchen** [comment]
Works fine for me when I use a cross-linker instead of ld.

**Comment by NalaGinrut** [comment]
@chneukirchen 
Well, yes, I modified something in Makefile to use arm-linux-gnueabihf-ld, and cross compile zlib. the problem fixed.
But it still require cross compiled libncurses, maybe I can write a better cross compile framework for it. Or just compile it on Rpi.

And I would like to use Chez for bare metal, dunno if it's possible.

**Comment by dybvig** [comment]
This issue seems to have been resolved or at least requires no action at this point, so I'm going to close it.
