### ISSUE TITLE
minor csug typo

### ISSUE THREAD

**Issue by ovenpasta** [cisco/ChezScheme#132]
at https://cisco.github.io/ChezScheme/csug9.4/io.html#./io:s72
and https://cisco.github.io/ChezScheme/csug9.4/io.html#./io:s82
```
(open-fd-output-port path) 
(open-fd-output-port path b-mode)
(open-fd-output-port path b-mode ?transcoder)
```
and
```
(open-fd-input/output-port path)
(open-fd-input/output-port path b-mode)
(open-fd-input/output-port path b-mode ?transcoder)
```
 should be fd, not path....

**Comment by burgerrg** [comment]
Thanks for finding this! I pushed corrections to the master branch and the web pages.
