### ISSUE TITLE
Community section of webpage is partially blocked by bottom banner

### ISSUE THREAD

**Issue by code-ape** [cisco/ChezScheme#133]
I was recently looking through the community section of the Chez Scheme [website](https://cisco.github.io/ChezScheme/#community) in the hopes of finding a freenode channel. Did find the channel but only after going through the HTML code because the bottom banner blocks most of the Community section information.

Just thought I'd share as I'd imagine others have struggled to find help because of this.

Cheers,
code-ape

![http://3.1m.yt/h5n12vo.png](http://3.1m.yt/h5n12vo.png)

**Comment by akeep** [comment]
@code-ape Thanks for point this out!  I've put in a fix that should correct this problem.

I've test this on my Mac (Safari, Firefox, & Chrome) and on my iPad (Safari, Chrome---in both orientations).

If this is still failing, let me know what browser you are using, and I'll try to take a look.

**Comment by code-ape** [comment]
It is fixed for Opera, my default browser, as well! Thanks 👍
