### ISSUE TITLE
With foreign interface  how to call void myfunction(const char* format, …)

### ISSUE THREAD

**Issue by evilbinary** [cisco/ChezScheme#135]
With foreign interface scheme  how to define foreign-procedure and how to  call:
 void myfunction(const char* format, …);

**Comment by ovenpasta** [comment]
Hi, this works for me:
``` scheme
(load-shared-object "libc.so.6")
(define printf/int (foreign-procedure "printf"  (string int) void))
(printf/int "hi %d\n" 123)
```
You only need to define the foreign-procedure for the needed parameter types combination...

**Comment by evilbinary** [comment]
Yeah,you are right. But how can i define one function for use any argument? Guys ,are you trying to use ChezScheme write a gui? Recently, i seek for a gui can run in chez ,finnaly cannot find a property one ,so i ported imgui to android to develop scheme game. So you know ,there are many difficult and this multi parameter problem confuse me.

**Comment by evilbinary** [comment]
![gcnbysr1rjd ou mie736l](https://cloud.githubusercontent.com/assets/5143386/21376341/2497d1e4-c76f-11e6-8b33-cb5c8ef9eb0a.jpg)
![kpvnnyww ulh4th47eh7o](https://cloud.githubusercontent.com/assets/5143386/21376342/249c04c6-c76f-11e6-8f9e-884cca43320d.jpg)

**Comment by yjqww6** [comment]
This works for me(ti3nt)

(define (typeof val)
  (cond
   [(string? val) 'string]
   [(fixnum? val) 'int]
   [(flonum? val) 'double]
   [else (error 'typeof "unsupport")]))

(define (printf fmt . vals)
  (apply (eval `(foreign-procedure "printf" (string ,@(map typeof vals)) int)) fmt vals))


> (printf "%d %lf %s" 1 1.0 "test")
1 1.000000 test15

**Comment by evilbinary** [comment]
Ok,thanks

**Comment by yjqww6** [comment]
maybe better to cache the generated code with hashmap.
BTW, I have tried some gui libraries for chez scheme on Windows a few months ago, and I think iup is the most convinient one but it is single threaded and not for android.

**Comment by ecraven** [comment]
In this concrete case I suggest generating the full string in scheme, then call printf("%s", my_string)
