### ISSUE TITLE
Use structs directly as foreign-procedure parameters / return values.

### ISSUE THREAD

**Issue by ecraven** [cisco/ChezScheme#137]
I am trying to define a foreign-procedure that directly returns a struct. As an example, from the C version of SFML:
````
typedef struct
{
    sfInt64 microseconds;
} sfTime;

sfTime sfSeconds(float amount);
````

I have tried the following, but get the error shown:
````
(define-ftype sfTime
  (struct (microseconds integer-64)))
(define sf:seconds (foreign-procedure "sfSeconds" (float) sfTime))
=> Exception: invalid (non-base) foreign-procedure result ftype sfTime
````

I hope I haven't missed how to do this while reading the csug. Is there any way to achieve this short of writing a custom C function that wraps the struct value in a pointer?

**Comment by evilbinary** [comment]
Meet the same question for passing directly struct to a function.

**Comment by dybvig** [comment]
Passing and returning structs (rather than pointers to structs) is not presently supported.  To call a function that requires struct arguments or returns struct values, you'd need to create an appropriate C wrapper.  Or you'd need to extend `foreign-procedure` and `foreign-callable` to handle struct arguments and return values.

**Comment by evilbinary** [comment]
How to extend foreign-procedure and foreign-callable? I need passing struct and return the struct value.Could you show detail?

**Comment by dybvig** [comment]
If you want to tackle this, you'll need to study and understand the code for handling `foreign-procedure` and `foreign-callable` in syntax.ss, cpnanopass.ss, and (for starters) one of the machine-dependent files like x86.ss.  You'll also need to learn how the calling conventions for a particular target (architecture and O/S) dictate structs be passed and returned.  For documentation on calling conventions, look for an _Application Binary Interface_ description, at least on Unix-based systems.  Also look at the output of 'cc -S testfile.c", where testfile.c contains various C examples passing and returning structs with and without other arguments.  You can use these examples for testing later.  Once you understand how the compiler handles non-struct values as well as the calling conventions for struct values, you'll be ready to start modifying the expander and compiler.  Once you get struct values working and well tested (via tests added to foreign.ms) on one target, the others should be relatively straightforward.  You should be able to get help here or on the mailing list from @akeep, @cfrisz, and me with specific questions if you get stuck on particular issues.  While you'll be charting new ground, we all have experience with the compiler's handling of `foreign-procedure` and `foreign-callable`.

**Comment by evilbinary** [comment]
Oh,that maybe cost a lot of time, quickly I made of this [https://github.com/evilbinary/scheme-lib/blob/master/packages/cffi/cffi.ss](url).It can use struct parameter to call directly. @ecraven

**Comment by mflatt** [comment]
Passing and returning structs has been supported for a while now.
