### ISSUE TITLE
Documentation for get-bytevector-some! and get-string-some! is incorrect

### ISSUE THREAD

**Issue by ChrisVine** [cisco/ChezScheme#138]
The user manual describes the behavior of get-bytevector-some! as follows:

"If bytevector-input-port is at end of file, the eof object is returned. Otherwise, this procedure reads (as if with get-u8) as many bytes, up to n, as are available before the port is at end of file, stores the bytes in consecutive locations of bytevector starting at start, and returns the count of bytes read as an exact positive integer. The port's position is advanced past the bytes read.

"If the port is in nonblocking mode (see set-port-nonblocking!), the number of bytes read may be less than n even if the port is not at end of file after the operation has completed, if the system would have to block to wait for more bytes. Similarly, zero may be returned even if the port is ultimately determined to be at end of file, if this cannot be determined without blocking."

The description of get-string-some! is similar, but for characters rather than bytes.  These descriptions are incorrect, because in reality get-bytevector-some! and get-string-some! do what you would expect them to do, which is to behave like unix 'read': in other words, to act as a mutating version of R6RS get-bytevector-some rather than as an imitation of get-bytevector-n! and get-string-n!

The only difference in behavior as between a non-blocking port and a blocking port with these get-*-some! procedures is that with a blocking port, they (like unix 'read') will block until at least one byte or character is available.  If non-blocking, in such a case they will return immediately with a value of 0.

This is not a bug in the implementation, which is correct.  It is rather a bug in the documentation, which seems to have confused get-bytevector-some! and get-string-some! with get-bytevector-n! and get-string-n!.

**Comment by dybvig** [comment]
Thanks for pointing this out.  I've pushed updated descriptions; please check them out and see if they appear to be correct.

**Comment by ChrisVine** [comment]
They look fine.  Thanks.
