### ISSUE TITLE
"make install" broken on *NIX

### ISSUE THREAD

**Issue by crististm** [cisco/ChezScheme#142]
Commit  50c2b4ec1d83dd42722a32717e5940ce4da4009e   "added Windows installer using the WiX Toolset" added the folder "install" which conflicts with the "install" Makefile target.

On a fresh clone of the repository, "make install" will terminate with the following message without doing anything:

make: 'install' is up to date.

**Comment by burgerrg** [comment]
Thanks for finding this mistake! I'll fix it soon.

**Comment by burgerrg** [comment]
I pushed a change that renames the install folder to wininstall.
