### ISSUE TITLE
can not use _ in the literal list of (syntax-rules (...) ...)

### ISSUE THREAD

**Issue by xieyuheng** [cisco/ChezScheme#15]
thus, for example, can not use this pattern matcher :: synthcode.com/scheme/match.scm

**Comment by jltaylor-us** [comment]
This is required by the language specification:
http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_786
> It is a syntax violation if an ellipsis or underscore appears in `(<literal> ...)`.

**Comment by xieyuheng** [comment]
thank you @jltaylor-us, I am closing this issue, since chez is mainly r6rs.
