### ISSUE TITLE
64-bit Windows handling of varargs floating-point values

### ISSUE THREAD

**Issue by burgerrg** [cisco/ChezScheme#150]
The updated foreign.ms mats exposed a bug in the handling of floating-point varargs in 64-bit Windows. According to Microsoft, floating-point varargs values should be loaded into the XMM register as well as the integer register for the first four arguments: https://msdn.microsoft.com/en-us/library/dd2wa36c.aspx

> (load-shared-object "msvcrt.dll")
> (define f (foreign-procedure "printf" (string double) int))
> (f "(%g)" 3.5)
13
> (exit)
(1.4822e-323)

**Comment by burgerrg** [comment]
I have a fix on the rgburger/varargs branch. I wanted to set! the integer register to be the floating-point register, but it looks as though the x86_64 code generator does not distinguish between integer and XMM registers in the reg record. So I added a new primitive %move-double that does the sse.movd instruction. If there's a better way to do this, please comment!

**Comment by dybvig** [comment]
Although, as you say, you can't set! the integer register directly to the floating-point register, the integer register should still be assigned via set! for the benefit of the register allocator, so in place of `(inline ,(make-info-loadfl fpreg) ,%move-double ,ireg)` you might have `(set! ,ireg (inline ,(make-info-loadfl fpreg) ,%get-double))` where %get-double is a "value" version of %move-double.  It looks like you're already including ireg in the list of live registers, which is good.

**Comment by burgerrg** [comment]
Thanks, I updated rgburger/varargs with this change. I also found that Windows does not support single-precision floating-point arguments to varargs procedures, so I removed that change.

If this looks good, I'll update the suite of boot files.

**Comment by dybvig** [comment]
Looks good to me.

**Comment by burgerrg** [comment]
Thanks, I've tested the changes on Windows, Linux, and Mac OS X. They're now merged to master.
