### ISSUE TITLE
How do I correctly (import (srfi :42)) in Chez scheme?

### ISSUE THREAD

**Issue by TrailingDots** [cisco/ChezScheme#156]
(System: centos 7, 64 bits)

I am attempting to import srfi-42 into my program. This is the first srfi in Chez Scheme for me.

The srfi lib is at:

    /home/cecilm/play/ChezScheme/chez-srfi/srfi

I added this dir to my .emacs :

(setenv "CHEZSCHEMELIBDIRS"
    (concat
      "."    ":"
      (getenv "$HOME") /play/ChezScheme/chez-srfi" ":"
      (getenv "PATH")))

In emacs, geiser starts chez. emacs seems to know about this dir:

    > (library-directories)
    (("/home/cecilm/play/ChezScheme/chez-srfi"
       .
       "/home/cecilm/play/ChezScheme/chez-srfi"))

The repl seems to import srfi-42:

    > (import (srfi :42))
    > (list-ec (: i 5) (* i i))

Exception: attempt to reference out-of-context identifier error
I thought "i" was a problem, so I defined "i" in a let:

    > (let ((i 0)) (list-ec (: i 5) (* i i)))
    
    Exception: attempt to reference out-of-context identifier error
What do I need to do to actually use an import? This is the first time I have used any imports in Chez Scheme.

Does "list-ec" need a qualifier?

I obtained the srfi's from [git]: 1 https://github.com/dharmatech/chez-srfi.git Is this a "standard"? Is there a more "official" repo for Chez scheme?

Using other repos in github such as arcfide/chez-srfi always resulted in:

    > (import (srfi :42))
    Exception: library (srfi :42) not found

**Comment by ovenpasta** [comment]
Hi, I think you need to `(import (srfi :42 eager-comprehensions))`

In my case I use this code
```
> (import (srfi s42 eager-comprehensions))
> (list-ec (: i 5) (* i i))
(0 1 4 9 16)
```
I'm using my own fork of srfi's.... but I think it should work with the other repositories also.

It's located here:  https://github.com/ovenpasta/thunderchez

or better: https://pizzahack.eu/fossil/thunderchez/

**Comment by TrailingDots** [comment]
YES! This works - at least on thunderchez.
Thank you VERY much!
