### ISSUE TITLE
Is all procedures using 'with-tc-mutex' share one same $tc-mutex?

### ISSUE THREAD

**Issue by Saigut** [cisco/ChezScheme#157]
I find that that many places in chez scheme source code using `with-tc-mutex`. In my understanding, `with-tc-mutex` maybe used to ensure the code to be thread safe.
I find the definition of `with-tc-mutex` in cmacro.ss, it shows that `with-tc-mutex` using `$tc-mutex` as the mutex to acquire/release.
`$tc-mutex`  is defined and set in prims.ss: `(define $tc-mutex)`, `(set! $tc-mutex ($make-mutex ($raw-tc-mutex)))`. And `$tc-mutex` is defined as symbol flag in primdata.ss.

I'm not sure what data type `$tc-mutex` really is, just thinking it maybe some thing like a global variable.

If `$tc-mutex` is some thing like a global variable, then all procedures using `with-tc-mutex` will using one same `$tc-mutex`, so they will block each other whether it need or not.

If all procedures using `with-tc-mutex` are using one same mutex, I think it is not reasonable.
Say there are two type task A and B. Task A1, A2 are of type A; task B1, B2 are of type B.
And say, tasks of same type should block each other but tasks of different type should not block each other.
If A1, A2, B1 and B2 all using `with-tc-mutex`, then A1, A2 will block B1, B2 while they should not be.

So is this as my understanding, all procedures using `with-tc-mutex` share one same `$tc-mutex`?

**Comment by dybvig** [comment]
You're right that tc-mutex is shared by all threads; it must be, to serve its purpose.  You're also right that using a single mutex causes unnecessary synchronization.  Using multiple mutexes, however, can lead to deadlock where each of two threads holds a mutex the other needs.  So when we added native threading to Chez Scheme, we opted to use a single mutex to protect system-level data structures, with the thinking that where we found it to cause performance problems, we would carefully use different mutexes for different purposes.  We haven't observed it to cause performance problems, though that doesn't mean it hasn't.

**Comment by Saigut** [comment]
Thanks for answering my question. I mistakenly wrote procedure as process, now I corrected them.

In my original thinking, if many places using one same mutex, it may be difficult to find where is the error when one place blocking the program, especially when i/o task blocked by calculate or other type task. And I think if the code between the acquiring and releasing of a mutex don't to include another mutex, then the code can never to be deadlock. But there should be too many cases that I'm not considered.

The question of this issue has been clearly answered, so I am to closing this issue.
