### ISSUE TITLE
mutex and condition objects are never freed

### ISSUE THREAD

**Issue by burgerrg** [cisco/ChezScheme#158]
The storage for mutex and condition objects allocated by malloc in c/thread.c is never freed. What would it take to place them under the garbage collector's control? Perhaps a guardian like file-guardian that detects when they're no longer used? And we'll have to be careful about the places where the c code is called with the raw addresses and the wrapper Scheme object is no longer referenced.

**Comment by burgerrg** [comment]
I have a proposed fix on branch rgburger/threads. @dybvig or @akeep, what do you think? I added a $keep-live primitive to keep the mutex and condition Scheme records live across calls that deactivate the thread (mutex-acquire and condition-wait), and then keep track of the inaccessible mutexes and conditions with guardians that get cleaned out with $close-resurrected-mutexes&conditions.

**Comment by dybvig** [comment]
The changes look solid to me, with one concern.  If a program registers a mutex or condition object with a guardian and attempts to use the mutex or condition object after retrieving it from the guardian, what happens?  We have a similar issue with file ports, for which we use a similar mechanism.  The port will be closed by the time it's retrieved and an attempt to read from or write to it will cause an exception to be raised.  That bothers me a bit, but not as much as, say, an invalid memory reference or memory corruption.

**Comment by burgerrg** [comment]
We could change the Scheme condition and mutex records to use a mutable addr and set it to 0 when the C data structure is freed. It would then be easy to detect this situation and report an exception. Shall I make that change?

**Comment by dybvig** [comment]
Yes, I think so.

**Comment by burgerrg** [comment]
I've made the changes and added a mat for this case. Is there anything else?
