### ISSUE TITLE
chez doesn't recognize command line argument passthrough "--"

### ISSUE THREAD

**Issue by bjoli** [cisco/ChezScheme#159]
running 

chez -- --flag 1

should, according to the man page, pass --flag 1 through as (command-line) or (command-line-arguments). but running that at the shell raises

> chez -- --flag 1
Chez Scheme Version 9.4.1
Copyright 1984-2016 Cisco Systems, Inc.

Exception in load: failed for --flag: no such file or directory

I pulled everything from master today, and compiled with --threads --installschemename=chez

**Comment by burgerrg** [comment]
Chez Scheme's default scheme-start procedure treats each argument as a filename to load. If you want different behavior, you'll need to specify a scheme-start procedure.

**Comment by burgerrg** [comment]
Another option is to use the --script argument to Chez Scheme. Suppose script.ss has the following in it: (pretty-print (command-line))

Then chez --script script.ss -- --flag 1 will print:
("script.ss" "--" "--flag" "1")

**Comment by bjoli** [comment]
Thanks for the info. However: this is not very clear in the man page, and should maybe be clarified.

**Comment by dybvig** [comment]
Agreed.  I have attempted such a clarification with [this commit](https://github.com/cisco/ChezScheme/commit/a963a4dbc872be084cbe0ede3f7c361bcabedea5).

**Comment by bjoli** [comment]
@dybvig That is indeed more clear, but the explanation for "--" still says "pass all remaining command line arguments through to scheme" (which was what confused me in the first place. I was writing a getopt-long clone and needed to play with the command line interactively). In the perfect world, everyone  would read the whole man-page, but as it is now it is often just a quick fix to look up things on the command line. 

Maybe "When --program or --script is present, pass all remaining arguments through to scheme".
