### ISSUE TITLE
Guardian loses objects when alternate thread exits

### ISSUE THREAD

**Issue by laqrix** [cisco/ChezScheme#162]
It looks like start_thread fails to process the guardian entries when calling destroy_thread. It appears as though guardians store entries in the current thread context.  If an object is registered with a guardian on a thread that then exits, calling the guardian never results in the objects.
```
(with-interrupts-disabled
 (let ([g (make-guardian)])
   (fork-thread
    (lambda ()
      (disable-interrupts)
      (g (list 'a 'b))))
   (sleep (make-time 'time-duration 100000000 0))
   (collect 0 0)
   (g)))
```
This should return (a b) but returns #f.

**Comment by dybvig** [comment]
You're right.  I will implement a fix unless someone beats me to it.

**Comment by burgerrg** [comment]
Kent, I've got a possible fix on rgburger/threads.

**Comment by dybvig** [comment]
Looks good Bob, though it's probably not necessary to set `GUARDIANENTRIES(tc)` to `Snil` before freeing it.  Incidentally, it seems like there is a missing`break;` after `status = 1;`, which you might also want to fix.

**Comment by burgerrg** [comment]
Thanks, I'll make those two edits and push to master.
