### ISSUE TITLE
cp0: problem with folding and non-constant propagation

### ISSUE THREAD

**Issue by gus-massa** [cisco/ChezScheme#166]
For example in:

    (let ([x '#&7]) (set-box! x 2) (unbox x))

 The result is `7` but it "must" be `2`.

I’m not sure if this is a bug, or it’s just undefined behavior. (Messing with the boxes created by the reader extension is never a good idea.)

Other expressions like `#(1 2)`, `'(1 2)`, ... have similar problems.

**Comment by akeep** [comment]
Quoted data is constant in R6RS, so modifying it is undefined.  Chez's run time does not have a way to differentiate between constant and non-constant boxes (or vectors or pairs for that matter), so it does not raise an error when you modify a constant.  However, the optimizer does assume that a quoted constant will be constant and optimizes accordingly.

If you want a mutable box, you should not define it as a constant, and use box instead:

```
> (let ([x (box 7)]) (set-box! x 2) (unbox x))
2
```

This also came up in #149.

**Comment by gus-massa** [comment]
ok, thanks
