### ISSUE TITLE
mats/summary vs ta6le/mats/summary

### ISSUE THREAD

**Issue by adamsmd** [cisco/ChezScheme#17]
Currently `make test` prints the following as its last line:

```
test run complete.  check mats/summary for error
```

However, `mats/summary` does not exist.  The user actually needs to check something like `ta6le/mats/summary`.  While it is a small usability improvement, it would be nice if `make test` printed the actual filename or at the very least hinted that there is an extra directory layer.

**Comment by dybvig** [comment]
Fixed with latest commit.
