### ISSUE TITLE
gcc 7 - implicit fallthrough

### ISSUE THREAD

**Issue by gwatt** [cisco/ChezScheme#172]
gcc 7 has a new warning brought in by -Wextra: -Wimplicit-fallthrough. https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/
I can make a pull request, but I wasn't sure if you prefer just adding `-Wno-implicit-fallthrough` to the compiler flags (clang and older gcc versions seem to ignore it) or adding a break or fallthrough comment for each case label.

**Comment by beneyal** [comment]
Did you tinker with it? This issue's been silent for a month, and I'm wondering what to do. This also breaks the `chez-scheme` AUR package for Arch Linux since -Werror is on.

@dybvig , @burgerrg any preference?

**Comment by gwatt** [comment]
I ran the configure script with `CFLAGS=-Wno-implicit-fallthrough` and that worked. I looked at adding breaks or `/* fallthrough */` comments, but there are many more switch statements than makefiles.

**Comment by beneyal** [comment]
@gwatt Worked like a charm. Thank you very much! 😄

**Comment by gwatt** [comment]
https://github.com/cisco/ChezScheme/pull/183
