### ISSUE TITLE
occasional invalid memory reference from operations on complex numbers on 64-bit machines

### ISSUE THREAD

**Issue by burgerrg** [cisco/ChezScheme#182]
The code below sometimes raises an invalid memory reference when run on a6nt, a6osx, and a6le:
```
(current-eval interpret)
(run-cp0 (lambda (cp0 x) x))
(do ([n 2000 (- n 1)] [ls (iota 2000)])
      ((= n 0))
    (map (lambda (x) (let ([x (exact (sqrt -2.0))]) x)) ls))
```

I distilled this example from a mat that fails occasionally.

It does not happen on i3nt, so the bug may be related to the x86_64 code generator.

**Comment by dybvig** [comment]
It looks like we might be using an 8-byte memory read where we should be using a 4-byte read to extract a flonum exponent, and this can sometimes run beyond accessible memory.  I'll take a deeper look and try to fix it.

**Comment by dybvig** [comment]
@burgerrg: I have a fix for this ready to push.  I'm holding off for now in case you're planning to pull the date-dst? request so @samth need not rebase again.

**Comment by burgerrg** [comment]
@dybvig: I would like to pull the date-dst? request, but there's no need to do the bootfiles twice. Can you rebase your fix onto the first commit of the date-dst? request, then make the fix, and rebuild the boot files?

**Comment by dybvig** [comment]
Fixed with [this commit](https://github.com/cisco/ChezScheme/commit/97bd75bcedbcf32b77c59615a638ea1528ebe26b).
