### ISSUE TITLE
Issues building on Windows 10

### ISSUE THREAD

**Issue by Arcryalis** [cisco/ChezScheme#185]
I have Cygwin installed and a copy of https://github.com/cisco/ChezScheme inside it under C:\cygwin64\home\Arcryalis, I've been following the instructions at https://github.com/cisco/ChezScheme/blob/master/BUILDING for windows as well as a similar closed issue at https://github.com/cisco/ChezScheme/issues/155 and I'm using a 64 bit version of Windows 10 Home.

Everything seems to work fine till I run 'make' upon which I'm presented with this:
![image](https://user-images.githubusercontent.com/24389511/27488473-11302de4-582f-11e7-979e-ead69723928d.png)
I've run this with and without admin rights, using both unthreaded 64 and 32 bit versions (this is the same error for each) and I've been unable to find the file in question before or after './configure' or 'make' are run. Within the Cygwin launcher, the only 'rc' package available is "An implementation of the AT&T Plan 9 Shell" under the category 'Interpreters', which is currently not installed.

Is there anything I'm missing / that I should try to remedy this?

**Comment by burgerrg** [comment]
rc is the Windows resource compiler. It's part of the Windows 10 SDK (https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk). Make sure you've installed it.

**Comment by Arcryalis** [comment]
Downloaded and ran the .exe, used the 'winsdksetup.exe' it created confirm everything was installed, restarted the system and tried the installation steps - returned the same error unfortunately.

**Comment by burgerrg** [comment]
So your computer already had it installed? Did you repair the installation? That might shake it loose.

**Comment by Arcryalis** [comment]
I'm not entirely sure. The original .exe downloaded from the website linked runs the same each time I execute it, but it did take siginificantly longer the first time it was run. After the original .exe finishes it points me to a new subdirectory it created after the first run, containing all of the installers which each return 'latest version installed'. 

Not entirely sure what I should be doing to repair the installation, have tried uninstalling, reinstalling and restarting the system to no effect.

**Comment by burgerrg** [comment]
Open "Programs and Features". Find Windows Software Development Kit in the list. Select it and click Change. Then select the Repair radio button. See if that shakes it loose.

**Comment by Arcryalis** [comment]
Repair seemed to fix the issue, everything else went on without an issue.

Thanks so much for the help!
