### ISSUE TITLE
Configure still fails with the zipped tarball of the source but not with the git cloned sources.

### ISSUE THREAD

**Issue by haziz** [cisco/ChezScheme#187]
I did report this in December, but that report was closed, and I am unsure of how to reopen it. See also the prior report for details.

Actually this still happens. I once again could not install from the "zipped" tarball downloaded from Github but was able when I just git cloned the repository. The system on which this failed is a fresh install of Debian 9 ("Stretch") 64 bit. I did install the X11 and ncurses dev libraries and headers since Debian does not install them by default.

My terminal output:

haziz@stretch:~/src/ChezScheme-master$ ./configure
rmdir: failed to remove 'nanopass': No such file or directory

**Comment by haziz** [comment]
A few comments: You may need to be logged OUT of Github to see the zipped tarball button that I am referring to. 

.configure when it does succeed (with the cloned repository) downloads 2 other repositories, this does not happen with the zipped tarball and it fails immediately as you can see with the above message:

rmdir: failed to remove 'nanopass': No such file or directory

the above message appears instantly after I "configure".

**Comment by burgerrg** [comment]
Try updating the section of the configure script (shown below) so that, in the case without a .git folder, it handles the situation when there is no nanopass or zlib or stex folder.
```
if [ -d '.git' ] ; then
  git submodule init && git submodule update || exit 1
else
  if [ ! -f 'nanopass/nanopass.ss' ] ; then
    rmdir nanopass && (curl  -L -o v1.9.tar.gz https://github.com/nanopass/nanopass-framework-scheme/archive/v1.9.tar.gz && tar -zxf v1.9.tar.gz && mv nanopass-framework-scheme-1.9 nanopass && rm v1.9.tar.gz) || exit 1
  fi

  if [ ! -f 'zlib/configure' ] ; then
    rmdir zlib && (curl -L -o v1.2.11.tar.gz https://github.com/madler/zlib/archive/v1.2.11.tar.gz && tar -xzf v1.2.11.tar.gz && mv zlib-1.2.11 zlib && rm v1.2.11.tar.gz) || exit 1
  fi

  if [ ! -f 'stex/Mf-stex' ] ; then
    rmdir stex && (curl -L -o v1.2.1.tar.gz https://github.com/dybvig/stex/archive/v1.2.1.tar.gz && tar -zxf v1.2.1.tar.gz && mv stex-1.2.1 stex && rm v1.2.1.tar.gz) || exit 1
  fi
fi

```

**Comment by dybvig** [comment]
When I unzip the zip file, the empty nanopass, zlib, and stex directories are present as expected, so `rmdir` does not fail.   Nevertheless, I've just committed a version of configure modified per @burgerrg's suggestion to handle the case where these directories are not present.

**Comment by haziz** [comment]
I have not retested this again, but will consider this closed.
