### ISSUE TITLE
regular development release?

### ISSUE THREAD

**Issue by marcomaggi** [cisco/ChezScheme#195]
I am trying to build a local package for Chez using the Slackbuilds infrastructure for Slackware, but it needs to download a proper release tarball.  It has been quite some time since the last release; would it be possible to regularly tag a development release that package maintainers can pull?  Maybe every 4 months?

**Comment by dybvig** [comment]
I don't know whether one every set number of months is appropriate, but it is past time for us to create a release.  I'll start the conversation with the other committers.

**Comment by marcomaggi** [comment]
Thanks.  It would also be useful to have an automation to build packages easily installed from the Travis CI configuration; it would significantly speed up Travis jobs run times.
