### ISSUE TITLE
request: arm32le included in build architectures

### ISSUE THREAD

**Issue by Silverbeard00** [cisco/ChezScheme#202]
After looking through all the issues pertaining to ARM here it looks like Chez should build on the raspberry pi 3. 

I'm having issues trying to figure out how you're supposed to compile it.   There don't seem to be any build instructions for ARM, although some of the issues include snippets of ways it might be done.

Is there anyway it can be supported to build it using ./configure m=arm32le?  Or can someone give me an overview of the process.  I'm assuming you have to compile it on a supported arch (like x86_64) first and then move it over to the ARM device but I didn't seem to find much luck with that recently.

**Comment by InfiniteTape** [comment]
Here's the approach that's worked for me. To run the mats, I have to add -fomit-frame-pointer to the compilation of the foreign?.c files. Even then, there are a handful of failed mats, but @burgerrg and I didn't feel the failures were critical. REPL comes up just fine. I'm away from the Pi right now, or I'd mention the exact errors.

You may need to add additional apt packages based what your distros already have installed on both the host PC and the Pi.

On Linux PC:
	• sudo apt install ncurses-dev
	• sudo apt install libx11-dev
	• git clone https://github.com/cisco/ChezScheme.git 
	• cd ChezScheme/
	• ./configure
	• sudo make install
	• mkdir boot/arm32le
	• cd a6le
	• make -f Mf-boot arm32le.boot
	• cd ..
	• ./configure  -m=arm32le
	• ./configure --workarea=arm32le
	• cd arm32le/s
	• make -f Mf-cross m=a6le xm=arm32le base=../../a6le
	• cd ../../

On Raspberry Pi
	• mkdir ChezScheme
	• sudo  apt install rsync

On Linux VM
	• rsync -avz ChezScheme/ user@pi-address:/home/user/ChezScheme

On Raspberry Pi
	• sudo apt install gcc
	• sudo apt install make
	• sudo apt install ncurses-dev
	• sudo apt install libx11-dev
	• cd ChezScheme/arm32le/c
	• make
	• ../bin/scheme  -b ../boot/arm32le/petite.boot -b ../boot/arm32le/scheme.boot

**Comment by Silverbeard00** [comment]
It appears to be up and running now.  Thanks!
