### ISSUE TITLE
build fails on fedora 26 with fall through warning treated as error in schsig.c

### ISSUE THREAD

**Issue by nduane** [cisco/ChezScheme#210]
I haven't looked deeply into this yet.  I have built chez scheme on fedora 25 and didn't run into this issue.  That was several months back so I'm not sure if something in chez scheme has changed or something in fedora 26.  Here is a snippet of the error when running 'make install':

schsig.c: In function ‘handle_signal’:
schsig.c:590:13: error: this statement may fall through [-Werror=implicit-fallt\
hrough=]
             S_abnormal_exit();
             ^~~~~~~~~~~~~~~~~
schsig.c:592:9: note: here
         case SIGILL:
         ^~~~
schsig.c:594:13: error: this statement may fall through [-Werror=implicit-fallt\
hrough=]
             S_error_reset("illegal instruction");
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
schsig.c:595:9: note: here
         case SIGFPE:
	 ^~~~
schsig.c:597:13: error: this statement may fall through [-Werror=implicit-fallt\
hrough=]
             S_error_reset("arithmetic overflow");
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
schsig.c:599:9: note: here
         case SIGBUS:
         ^~~~
schsig.c:603:16: error: this statement may fall through [-Werror=implicit-fallt\
hrough=]
             if (S_pants_down)
		^
schsig.c:607:9: note: here
         default:
         ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:29: schsig.o] Error 1
make[1]: *** [Makefile:20: build] Error 2
make: *** [Makefile:22: install] Error 2

**Comment by nduane** [comment]
Here is info on the version of gcc I'm using:

[root@squiddy ChezScheme-9.4]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,objc,obj-c++,fortran,ada,go,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.1.1 20170622 (Red Hat 7.1.1-3) (GCC)

**Comment by akeep** [comment]
What version of Chez Scheme are you trying to build?  I believe this was fixed by @gwatt in commit e0d965aab30a745157a0c89010bbf5017901d4a7

-andy:)

**Comment by nduane** [comment]
went here:

https://cisco.github.io/ChezScheme/

and that page had a link to the current release, 9.4, at:

https://github.com/cisco/ChezScheme/archive/v9.4.tar.gz

**Comment by akeep** [comment]
Yes, the current release (which is now a bit old) does not have this fix in it.  We are working on getting a new release out in the not to distant future.

In the meantime, I suggest using the git version.  Alternatively, you can patch the``Mf-a6le`` (or ``Mf-i3le``) in the ``c`` directory to include the ``-Wno-implicit-fallthrough``

The core issue is that the C compiler is trying to be helpful, but it doesn't know that ``S_abort`` and ``S_error_reset`` are functions that do not return (they are part of the exception handling in the run time).  The C compiler is trying to be clever, but it isn't quite clever enough, and because we see warnings as errors we either need to turn off some of the warning features or add ``pragma`` or ``__attribute__`` in the C code.

**Comment by nduane** [comment]
Thanks.  Yes, I assumed that was the problem.  I guess I will clone the master branch and build from there.

**Comment by nduane** [comment]
I guess this should be marked as a duplicate of https://github.com/cisco/ChezScheme/issues/193.

**Comment by nduane** [comment]
By the way, I did clone the master branch and was able to successfully build scheme on fedora 26.  In case whoever might be reading this, I'm wondering why the output of configure has changed.  Previously when I ran it it seemed to be testing performance of the system.  Now I don't see that anymore.

**Comment by JoshuaRLi** [comment]
Kali GNU/Linux Rolling x86_64 (debian) here, can confirm this occurs with the 9.4 tagged release tarball.

```
gcc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -O2  -c -DX86_64 -I../boot/a6le -I../zlib schsig.c
schsig.c: In function ‘handle_signal’:
schsig.c:590:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
             S_abnormal_exit();
             ^~~~~~~~~~~~~~~~~
schsig.c:592:9: note: here
         case SIGILL:
         ^~~~
schsig.c:594:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
             S_error_reset("illegal instruction");
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
schsig.c:595:9: note: here
         case SIGFPE:
         ^~~~
schsig.c:597:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
             S_error_reset("arithmetic overflow");
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
schsig.c:599:9: note: here
         case SIGBUS:
         ^~~~
schsig.c:603:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
             if (S_pants_down)
                ^
schsig.c:607:9: note: here
         default:
         ^~~~~~~
cc1: all warnings being treated as errors
Makefile:29: recipe for target 'schsig.o' failed
make[2]: *** [schsig.o] Error 1
Makefile:20: recipe for target 'build' failed
make[1]: *** [build] Error 2
Makefile:22: recipe for target 'install' failed
make: *** [install] Error 2
```

**Comment by JoshuaRLi** [comment]
However, `make install` is indeed successful with the latest git commit as of the time of posting (a629477).
