### ISSUE TITLE
Build failed on Cent OS 7.2

### ISSUE THREAD

**Issue by realwhz** [cisco/ChezScheme#216]
Hello.  I pulled an update today.  The build failed to make.  The error messages are at the end of the output.

Thank you for your time.

$ make
(cd a6le && make build)
(cd c ; make)
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib statics.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib segment.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib alloc.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib symbol.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib intern.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib gcwrapper.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib gc-ocd.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib gc-oce.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib number.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib schsig.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib io.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib new-io.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib print.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib fasl.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib stats.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib foreign.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib prim.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib prim5.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib flushcache.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib schlib.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib thread.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib expeditor.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib scheme.c
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib i3le.c
ld -melf_x86_64 -r -X -o ../boot/a6le/kernel.o statics.o segment.o alloc.o symbol.o intern.o gcwrapper.o gc-ocd.o gc-oce.o number.o schsig.o io.o new-io.o print.o fasl.o stats.o foreign.o prim.o prim5.o flushcache.o schlib.o thread.o expeditor.o scheme.o i3le.o ../zlib/libz.a
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -c -DX86_64 -I../boot/a6le -I../zlib main.c
cp -p main.o ../boot/a6le/main.o
cc  -m64 -msse2 -Wpointer-arith -Wall -Wextra -Werror -Wno-implicit-fallthrough -O2  -rdynamic -o ../bin/a6le/scheme ../boot/a6le/kernel.o ../boot/a6le/main.o -lm -ldl -lncurses -lrt 
(cd s ; make bootstrap)
make allx
rm -f *.a6le xpatch patch *.patch *.so *.asm script.all header.tmp *.html
rm -rf nanopass
cp -p -f ../boot/a6le/petite.boot ../boot/a6le/sbb
cp -p -f ../boot/a6le/scheme.boot ../boot/a6le/scb
make all
echo '(reset-handler abort)'\
             '(base-exception-handler (lambda (c) (fresh-line) (display-condition c) (newline) (reset)))'\
             '(keyboard-interrupt-handler (lambda () (display "interrupted---aborting\n") (reset)))'\
             '(optimize-level 3)'\
             '(debug-level 0)'\
             '(generate-inspector-information #f)'\
             '(subset-mode (quote system))'\
             '(compile-file "cmacros.ss" "cmacros.so")'\
             | ../bin/a6le/scheme -q
compiling cmacros.ss with output to cmacros.so
Exception: invalid memory reference.  Some debugging context lost
make[4]: *** [cmacros.so] Error 255
make[3]: *** [allx] Error 2
make[2]: *** [bootstrap] Error 2
make[1]: *** [build] Error 2
make: *** [build] Error 2

**Comment by akeep** [comment]
Hmmm... I tried to reproduce this on a CentOS 7 VM today (I couldn't find the 7.2 iso anymore, it looked like CentOS has moved to just providing one version 7 VM).

Some things to try:

1. Make sure you don't have a ``SCHEMEHEAPDIRS``, ``CHEZSCHEMELIBDIRS``, ``CHEZSCHEMELIBEXTS`` defined
2. Try to do a ``make distclean`` and then configure and build again.

Something that can happen is if the C run time and Scheme boot files have different expectations around how they should communicate, you can end up with some pretty serious problems, like the invalid memory reference.  This is part of the reason for making sure your ``SCHEMEHEAPDIRS`` is not set, if it is, you might end up with the new C run time trying to load the old ``*.boot`` files.

**Comment by Yongjin0919** [comment]
Mm

**Comment by realwhz** [comment]
Thank you Andy!  Your suggestion works!
