### ISSUE TITLE
Update build instructions

### ISSUE THREAD

**Issue by ChrisVine** [cisco/ChezScheme#219]
Can you update the build instructions to say that CHEZSCHEMELIBDIRS should be unset in order to build Chez Scheme, at least on unix-like OSs?  I came across this when compiling version 9.5 and it was a nuisance to have to google the answer, which pointed me to previous issues posted here.

**Comment by dybvig** [comment]
Done.  I've also added a set of CHEZSCHEMELIBDIRS to the affected make files so this should not be a problem for 9.5.1 and after.

**Comment by ChrisVine** [comment]
On Thu, 12 Oct 2017 13:50:52 +0000 (UTC)
"R. Kent Dybvig" <notifications@github.com> wrote:
> Done.  I've also added a set of CHEZSCHEMELIBDIRS to the affected
> make files so this should not be a problem for 9.5.1 and after.

Thanks.
