### ISSUE TITLE
Incorrect floating point parsing edge case

### ISSUE THREAD

**Issue by leppie** [cisco/ChezScheme#22]
```
(define (get-bits fps)
  (define fp (string->number fps))
  (define bv (make-bytevector 8)) 
  (bytevector-ieee-double-native-set! bv 0 fp)
  (number->string (bytevector-u64-native-ref bv 0) 2))

(get-bits "2.2250738585072011e-308")
```
Prints: `"10000000000000000000000000000000000000000000000000000"` instead of `"1111111111111111111111111111111111111111111111111111"`

First detected on Windows with 8.4, and retested on Linux with 9.4.

**Comment by dybvig** [comment]
This is one instance of a general problem with rounding denormalized numbers and has been fixed by my latest commit.

Thanks for bringing this and the other numeric issues to my attention.

**Comment by dybvig** [comment]
Hearing no objections, I'm marking this closed.
