### ISSUE TITLE
Full list of exported syntactic identifiers

### ISSUE THREAD

**Issue by marcomaggi** [cisco/ChezScheme#222]
With the purpose of generating a completion list for  use with `rlwrap` (the GNU Readline wrapper), I would like a way to compose a full list of the syntactic identifiers exported by `(chezscheme)`.  I do **not** need this feature built into the boot image, it would suffice to have a script to run from the source directory distribution.

**Comment by jltaylor-us** [comment]
`(environment-symbols (environment '(chezscheme)))`
http://cisco.github.io/ChezScheme/csug9.5/system.html#./system:h3

**Comment by marcomaggi** [comment]
> (environment-symbols (environment '(chezscheme)))

Thanks!
