### ISSUE TITLE
Multiple installation of boot files when requesting different executable names

### ISSUE THREAD

**Issue by marcomaggi** [cisco/ChezScheme#224]
On my `x86_64-slackware-linux-gnu` running a build from commit `1558dca8c23284d5718715ff0b1950204794f086`, I see the following boot files installed:

```
ls -l /opt/chez-scheme/9.5.1/lib64/csv9.5.1/a6le/
total 4.3M
-r--r--r-- 2 root root 823K Oct 14 20:33 chez.boot
-r--r--r-- 2 root root 1.4M Oct 14 20:33 petite.boot
-r--r--r-- 2 root root 1.4M Oct 14 20:33 petite-chez.boot
-r--r--r-- 2 root root 823K Oct 14 20:33 scheme.boot
-r--r--r-- 1 root root 9.1K Oct 12 06:16 scheme.h
lrwxrwxrwx 1 root root   54 Oct 14 20:37 scheme-script.boot -> /opt/chez-scheme/9.5.1/lib64/csv9.5.1/a6le/scheme.boot
```

when using this build script:

```
export CHEZSCHEMELIBEXTS=.chezscheme.sls:.chezscheme.ss:.sls:.ss
#export CHEZSCHEMELIBDIRS=:
unset CHEZSCHEMELIBDIRS
unset SCHEMEHEAPDIRS

VERSION=${VERSION:=9.5.1}
prefix=/opt/chez-scheme/${VERSION}${CHEZ_INSTALL_SUFFIX}
if test -d /lib64
then libdir=${prefix}/lib64
else libdir=${prefix}/lib
fi

make clean
make distclean
git clean -xfd
./configure \
    --installprefix="$prefix"			\
    --installlib="$libdir"			\
    --installowner=root				\
    --installgroup=root				\
    --installschemename=chez			\
    --installpetitename=petite-chez		\
    CFLAGS='-O3 -Wno-maybe-uninitialized'	\
    CPPFLAGS='-I/usr/local/include'		\
    LDFLAGS='-L/usr/local/lib64 -liconv'
make
make docs

(umask 0 ; sudo install -m 0755 -d "${prefix}/bin")
(umask 0 ; sudo install -m 0755 -d "${prefix}/share")
(umask 0 ; sudo install -m 0755 -d "${libdir}")
(umask 0 ; sudo make install)
```

**Comment by akeep** [comment]
Again you are seeing hard links which reflect the names you chose to call your Chez Scheme executables.  ``petite-chez.boot`` is a hard link to ``petite.boot`` and ``chez.boot`` is a hard link to ``scheme.boot``.  These hard links are needed because as I explained in #221 when you run ``chez`` it will look for a boot file called ``chez.boot`` and when you execute ``petite-chez`` it will look for a boot file called ``petite-chez.boot``.  Internally though, ``chez.boot`` will still be looking for a file called ``petite.boot``, so these are simply hard linked to avoid changing the underlying generation of the boot files.

**Comment by marcomaggi** [comment]
>  you are seeing hard links which reflect the names you chose to call your Chez Scheme executables

I see now.

>  Internally though, `chez.boot` will still be looking for a file called `petite.boot`, so these are simply hard linked to avoid changing the underlying generation of the boot files.

That is confusing from the package maintainer point of view.  An executable `ciao-chez` will look for a boot file `ciao-chez.boot`:  I understand this and I agree with this choice.  But why are the original file pathnames still needed?  The pathname is just a Chez Scheme's compile-time string.

**Comment by akeep** [comment]
The only part of the build process that is aware of the installation names is the installation step, so effectively the ``scheme.boot`` has already been built with a requirement on ``petite.boot``, so at the very least the ``petite.boot`` file must be there for your system to work.
