### ISSUE TITLE
How do I create a release tarball?

### ISSUE THREAD

**Issue by smcallis** [cisco/ChezScheme#227]
I'd like to roll my own release tarballs that only support the platforms I'm interested for size reasons (currently, only x86-64).  Can anyone fill me in on how to do this?  Also, I'm curious if there'd be interest in just using a regular configure/make/make install flow with normal automake/autoconf tools, rather than the homemade scripts currently in use?  IMHO "make dist" would be a nice way to do things...

**Comment by akeep** [comment]
The release tar ball is created directly from the git repository directory (wth submodules) excluding the hidden (``.git*`` and ``.travis*``) files and directories.

One way to do this is to do the following:

1. Make sure you have a clean git checkout with the submodules checked out.  You can clone the repository with ``--recursive`` to have it clone the submodules as well, or you can run ``git submodule update --init`` after you clone to get the directories.
1. If you want to make the tar ball on a specific version, checkout the version (for instance if you want to make a v9.5 tar ball: ``git checkout tags/v9.5`` (you can create a branch when you do this by also doing ``-b <branch name>``)
1. Use git to clean the directory (this will delete everything that is not part of the git repository, so be careful with this): ``git clean -xdf``, **Remember: this will delete everything not in the git repo!**
1. Create a staging directory, this will be the base of your tar ball: ``mkdir /tmp/csv9.5``
1. Use rsync, excluding the hidden files: ``rsync -arv --exclude '.git*' --exclude '.travis*' ChezScheme/ /tmp/csv9.5``  (Note: the trailing ``/`` after the git directory is significant.)
1. Optionally, remove any boot files you don't want to include: ``rm -rf /tmp/csv9.5/boot/<mt>/* ...`` (Note: these could also be excluded with rsync.)
1. Build the tar ball from the ``/tmp`` directory: ``cd /tmp && tar czvf my-csv9.5.tar.gz csv9.5``

You could also add additional boot files if you wanted to create a binary with a different mix of boot files.  Note that the directories listed here are suggestions only.

Alternatively, you could grab the ``csv9.5.tar.gz``, extract the contents, remove the boot files you don't want, then create your new tar ball from that directory.

**Comment by smcallis** [comment]
Awesome, thank you for the help!  Looking to make Chez the basis for a new plotter I'm working on, very excited about the possibility.
