### ISSUE TITLE
Interaction of foreign procedure and transcoder

### ISSUE THREAD

**Issue by svenha** [cisco/ChezScheme#228]
I have to fetch a string via a foreign procedure:

```
(define tchdbget2 (foreign-procedure "tchdbget2"  ((* tchdb) string) string))
(define (tchdb-get db key)
  (tchdbget2 db key))
```

Then, I have to read from a returned string s with a given transcoder (here: latin-1), which is not the default transcoder:

```
(call-with-input-string s read)

(define (call-with-input-string s pred)
  (let* ((tc (make-transcoder (latin-1-codec)))
         (port (open-bytevector-input-port (string->bytevector s tc) tc)))
    (pred port)))
```

But any non-ascii character will be replaced by #\?
Is there a way to get a bytevector from a foreign-procedure?
Are there other solutions?

**Comment by gwatt** [comment]
If you specify the return type as `u8*` it should be a null terminated bytevector

**Comment by svenha** [comment]
Thanks. It solved my issue.
