### ISSUE TITLE
0.0e3000 returns +inf.0

### ISSUE THREAD

**Issue by leppie** [cisco/ChezScheme#23]
Should be `0.0`

First detected on Windows with 8.4, and retested on Linux with 9.4.

Related: https://github.com/racket/racket/issues/1140

**Comment by dybvig** [comment]
I've reproduced this and will fix.

**Comment by dybvig** [comment]
My latest commit includes the fix.

**Comment by dybvig** [comment]
Hearing no objections, I'm marking this closed.
