### ISSUE TITLE
Control for evaluation order of function arguments

### ISSUE THREAD

**Issue by svenha** [cisco/ChezScheme#230]
Is there a way to control the evaluation order of function arguments? (it seems to be right-to-left, while
all Schemes I came across choose the more natural order left-to-right. I know: Scheme standards leave the order unspecified.)

Why am I asking? I am porting a large code base from Bigloo/Chicken/Gauche to Chez and such a fundamental difference make comparisons and comparative debugging really hard.

**Comment by akeep** [comment]
The Scheme standard does not define the order of evaluation of function arguments, so if you want to write portable Scheme code you cannot depend upon the order of evaluation being fixed.

**Comment by dybvig** [comment]
Like R6RS, Chez Scheme leaves unspecified the evaluation order of application subforms, `let` right-hand-side expressions, and `letrec` right-hand-side expressions.  The order in which `map` applies its procedure argument to the elements of its list arguments is also unspecified.  The same is true for various other primitives.  The sets of values to which hashtable hash and equality procedures are applied during hashtable ref and set operations is unspecified, let alone the order of application.

The actual evaluation order is affected by various optimizations, the introduction of temporaries to handle nested operations, and other code transformations in the compiler.  It is also affected indirectly by different compiler settings such as optimize and debug levels.  So while the order might be right-to-left in some cases, it isn't generally.

There is no flag you can set to impose a fixed evaluation order universally.  You could, however, hack the `build-call` and `build-letrec` definitions in syntax.ss to enforce a particular evaluation order, plus define your own versions of `map`, etc., that do the same, if necessary.  This will disable various important optimizations, so it's not something you'd want to leave in.  Also, evaluation order bugs per se would actually be masked by such a hack.

It might be easier and a better long-term solution to insert let bindings as necessary in the application source code to enforce evaluation order across all implementations.  You might find that only a small number of added let bindings are needed.

**Comment by svenha** [comment]
Thanks for the thorough explanations! I expected that the order cannot be easily changed, but I wanted to be sure before spending too much time on changing some 'let' to 'let*' etc. As you indicated, the number of changes required to get the overall execution more easily comparable to Schemes with other evaluation order choices was smaller than expected.
