### ISSUE TITLE
why call/cc loop forever?

### ISSUE THREAD

**Issue by netmany** [cisco/ChezScheme#232]
in my code test.ss
```
(import (chezscheme))
(define c)
(printf "before call/cc\n")
(printf "mid call/cc ~a\n" (+ 2 (* 3 (call/cc (lambda (k) (set! c k) 10)))))
(printf "after call/cc\n")
(c 100)
```

it comes different of the output between (scheme --script test.ss) and (scheme --program test.ss):
```
$ scheme --script ./test.ss
before call/cc
mid call/cc 32
after call/cc
mid call/cc 302
=======================
$ scheme --program ./test.ss
before call/cc
mid call/cc 32
after call/cc
mid call/cc 302 
after call/cc
mid call/cc 302
after call/cc
mid call/cc 302
after call/cc
mid call/cc 302
after call/cc
mid call/cc 302
after call/cc
...
```

what call/cc captured? 
is it remain of current stack or current program?

**Comment by gwatt** [comment]
When you run the code interactively the surrounding continuation - rest of the program - is different. The continuation of each top-level expression in the repl is "print out the value(s) and then wait for more expressions". When executing code from a file the continuation of each top-level expression is the next expression.
You can see the same result running interactively if you wrap your code in a begin:
```
(begin
  (define c)
  (printf "before call/cc\n")
  (printf "mid call/cc ~a\n"  (+ 2 (* 3 (call/cc (lambda (k) (set! c k) 10)))))
  (printf "after call/cc\n")
  (c 100))
```
