### ISSUE TITLE
How should I treat C String?

### ISSUE THREAD

**Issue by ta2gch** [cisco/ChezScheme#234]
Hi, I try to write an extension of ChezScheme in C++,

- replace.cpp

```c++
#include <regex>

extern "C" {
  const char* regex_replace_all(const char* s, const char* e, const char* fmt) {
    return strdup(std::regex_replace(s, std::regex(e), fmt).c_str());
  }
}
```

- Building

```sh
$  g++ replace.cpp --shared -fPIC -std=c++11 -o replace.so
```
- Calling

```scheme
(import (chezscheme))
(load-shared-object "replace.so")
(define regex-replace-all (foreign-procedure "regex_replace_all" (string string string) string))
(display (regex-replace-all "scheme" "s.*e" "chez"))
```

I have a question about the result of this replacement which is displayed. I guess the result has never been freed. Is it correct? How should I treat the result as C string in ChezScheme?

Thanks.

**Comment by gwatt** [comment]
Chez doesn't track the original string from foreign procedures. It instead copies the contents of that string into a managed scheme string. Simply returning the result of `.c_str()` may work, but probably isn't reliable as the c++ string will be deconstructed as part of exiting your function. I suspect the best way is to declare the return value of the C function as `ptr` and use the `Sstring(const char *)` function to convert the C string to a scheme string.

**Comment by ta2gch** [comment]
I got it. I'll try to use `Sstring` of `scheme.h`.  However, It seems that `scheme.h` is installed in `/usr/local/lib/csv9.5/<ARCH>/`. Historically, c header file must be located in `include` directory, for example /usr/local/include. Is this an expected work?

**Comment by ta2gch** [comment]
Okey. Thanks a lot!
The following code works  for me.

```cpp
#include <scheme.h>
#include <regex>

EXPORT ptr regex_replace(char* s, char* e, char* fmt, int flags) {
  auto regex = std::regex(e);
  auto once = flags
    ? std::regex_constants::format_first_only
    : std::regex_constants::match_default;
  auto result = std::regex_replace(s, regex, fmt, once);
  return Sstring(result.c_str());
}
```

I can build the code by this command.

```sh
$(CXX) regex.cpp \
	-Wl,-undefined,dynamic_lookup \
	-I$(SCHEME_INCLUDE_PATH) \
	-fPIC \
	-shared \
	-std=c++11 \
	-o regex.so
```
