### ISSUE TITLE
Simplifications for redistributors

### ISSUE THREAD

**Issue by weinholt** [cisco/ChezScheme#236]
Hello schemers,

I have some wishlist items for making redistribution of a program along with Petite Chez Scheme easier. This is in reference to the instructions at the end of csug 9.5 section 2.8, _Building and Distributing Applications_.

Previously, redistributions needed to include a Petite distribution in its entirety. Nowadays it's possible to do compile-whole-program and get a binary that just needs petite and petite.boot. While making a program that creates such a minimal distribution for a program of mine, I ran into some things that should be easier.

- Please provide procedures for locating the running binary and the boot files. I'm copying these and including them in a tarball.
- Please install LICENSE and NOTICE and provide procedures to find them (or perhaps just provide procedures that print their contents). According to the license these must be included in redistributions. Right now I need access to the Chez Scheme source code when building.

I also suggest updating csug section 2.8 where it says "the _Petite Chez Scheme_ distribution". I might be mistaken, but I don't think there is such a distribution today.

/Göran

**Comment by weinholt** [comment]
After having some more experience in this area I've realized that solving the copyright notice problem for Chez Scheme is only one part of a bigger puzzle. Other software that gets bundled by compile-whole-program will also need their notices, and that's not really something Chez can solve.
As for locating the system's boot files, that can be done more or less by searching $PATH.
Judging by the responses this got I don't think anyone else cares about it, so I'm closing the issue.

**Comment by burgerrg** [comment]
One way to find the location of the system boot files is to parse the output from:
`scheme -q --verbose < /dev/null`
