### ISSUE TITLE
 cannot open file 'csv94.dll' 

### ISSUE THREAD

**Issue by zmyspc** [cisco/ChezScheme#24]
I have to create `bin/$m`folder under ChezScheme,if not I'll get this error:
`LINK : fatal error LNK1104: cannot open file 'csv94.dll' NMAKE : fatal error U1077: 'link.exe' : return code '0x450'`
build under windows10 x64, $m=a6nt
Am I did it in a wrong way?

**Comment by metab0t** [comment]
I met the same error. I tried to compile `a6nt` in my Linux virtual machine, there is `csv94.dll` in `bin`folder, but it is a symlink. So if you do this on Windows, there will not be `csv94.dll`.
I guess it is impossible to compile the executable on Windows now.

**Comment by akeep** [comment]
Yes, the windows build is a bit rickety, but it actually was recently tested and working.  Part of the trick (as noted in the BUILDING document) is that you need to put the ChezScheme directory on a shared file system (for example on a samba share) and mount it from Windows.  This lets the Linux side of the build do its part (running configure and setting up symlinks and the like) and the Windows side see it as though it was a just a normal file system.

It is suboptimal, but it was recently tested.  Our setup for testing has been a Windows VM running on an older Fedora 13 machine, with the chezscheme directory hosted on the Fedora machine and Windows mounting the directory through samba.

**Comment by metab0t** [comment]
@akeep 
Does it means that you cannot use the compiled binary in a REAL Windows system (not a guest OS) now?
Can we figure out a way to compile without using symlinks?

**Comment by akeep** [comment]
@metab0t No, the symlinks are only needed for the build process.  Once things are complete you can copy the contents of the bin and boot directories (which are now the files that have been produced by the Windows C and Chez Scheme compilers).

**Comment by gggin** [comment]
same problem

**Comment by gggin** [comment]
can we just release an pre-build exe then we can use this to build our production!

**Comment by metab0t** [comment]
@gggin 
agree with you.
There should be a pre-build binary for windows.

**Comment by burgerrg** [comment]
I updated the build procedure for Windows so that a virtual machine is no longer required. It uses the Cygwin software on Windows to provide bash, make, etc.

**Comment by jltaylor-us** [comment]
Is this issue resolved?

**Comment by mflatt** [comment]
Similar to #19, I think we can probably close this, since Windows build support was overhauled in the v9.9.9 merge.
