### ISSUE TITLE
Possibly erroneous comment (cut-and-paste error)?

### ISSUE THREAD

**Issue by rxg** [cisco/ChezScheme#244]
https://github.com/cisco/ChezScheme/blob/3f65788b5422693f3648a9e2fe575f464eb31ccd/c/main.c#L336

**Comment by burgerrg** [comment]
Thanks for finding this! It's corrected in commit https://github.com/cisco/ChezScheme/commit/abb991bcd87f64eeae9a3848959191a4da5d6542.
