### ISSUE TITLE
how to not exit on typo in eval loop

### ISSUE THREAD

**Issue by glycerine** [cisco/ChezScheme#250]
I'm following the example of embedding given by https://github.com/cisco/ChezScheme/blob/abb991bcd87f64eeae9a3848959191a4da5d6542/examples/crepl.c#L77

for embedding Chez and running a home-made repl. But if I make a typo at the repl, I exit immediately.  How do I get a normal return from the eval call, rather than exit on error?  I see that s/exceptions.ss is somehow getting control under the non-embedded normal `scheme` binary repl, but I'm not sure how to load that same kind of thing in my custom repl.

~~~
jaten@Jasons-MacBook-Pro ~/go/src/github.com/glycerine/chezgo (master) $ make run
cd chez_scheme_9.5.1/c; make
make[1]: Nothing to be done for `doit'.
go build && ./chezgo
> a

 about to eval

Exception: variable a is not bound
abnormal_exit procedure did not exit
make: *** [run] Error 1
jaten@Jasons-MacBook-Pro ~/go/src/github.com/glycerine/chezgo (master) $ 
~~~

code to repro is https://github.com/go-interpreter/chezgo but since its embedded in Go you would need to install a Go toolchain first. (And its really just a super slim version of examples/crepl.c anyway)

versus nice recovery:
~~~
 $ scheme
Chez Scheme Version 9.5.1
Copyright 1984-2017 Cisco Systems, Inc.

> a

Exception: variable a is not bound
Type (debug) to enter the debugger.
> 
~~~

**Comment by gwatt** [comment]
@glycerine You should look at `with-exception-handler` https://www.scheme.com/tspl4/exceptions.html#./exceptions:s7

You could write a wrapper around eval that uses with-exception-handler.

**Comment by burgerrg** [comment]
You can see what Chez Scheme's repl does by reading the new-cafe procedure in s/cafe.ss.

**Comment by glycerine** [comment]
Thanks guys!

**Comment by mflatt** [comment]
Closing as answered.
