### ISSUE TITLE
Avast and virustotal report malware in Windows version

### ISSUE THREAD

**Issue by java4devgmail** [cisco/ChezScheme#252]
Hello

I reported this on the google groups but was told to report here.

I want to install the windows version but my antivirus reports every time I try to download the file that there is a malware on the windows version
https://github.com/cisco/ChezScheme/releases/download/v9.5/ChezScheme9.5.exe

and so does the
https://www.virustotal.com/

Any idea on how to get a clean installation file.
I have no windows development environment to build from sources.
On FreeBSD I installed it from the ports and it works fine.

Best Regards
Nikolas

**Comment by burgerrg** [comment]
I'm sorry that some anti-virus programs think the Windows install contains a virus. I've checked that ChezScheme9.5.exe with SHA-256 hash e69b93ea800cd85ab6de10473d88d8cc6f2a7338e71fe4bb37cd5b534454d866 is clean.

**Comment by java4devgmail** [comment]
Thank you very much for your response.
I will download and install

Happy New Year
Nikolas

**Comment by burgerrg** [comment]
You're welcome! Avast updated its detector. I haven't heard back from AVG yet. Happy New Year!
