### ISSUE TITLE
about r7rs define-library

### ISSUE THREAD

**Issue by xaengceilbiths** [cisco/ChezScheme#259]
I discovered the support of r7rs **define-library** by chez, but I couldn't find the any code that **define** **define-library**. I think the reason is that the code is compiled into a boot file in a close-source way. 
I tried to find something by **git grep**, but found nothing. I haven't dissect boot file yet.

**Comment by akeep** [comment]
Chez Scheme does not support r7rs at this time and there is no ``define-library`` in Chez.  Perhaps what you saw is ``define-library-entry`` which is an internal macro used in the file ``library.ss`` for populating some metadata for core-library routines.

**Comment by lixuzhang** [comment]
When will Chez Scheme support R7RS?

**Comment by akeep** [comment]
There are currently no plans to support R7RS.
