### ISSUE TITLE
Support network programming

### ISSUE THREAD

**Issue by W4anD0eR96** [cisco/ChezScheme#265]
The most nearly stuff I've found is http://cisco.github.io/ChezScheme/csug9.5/foreign.html#./foreign:h9

However, for what reason chez itself does not support procedure on network programming?

**Comment by akeep** [comment]
This is somewhat philosophical, in that Chez Scheme seeks to provide the tools for building things like a network programming library, not to be a programming environment that includes everything plus the kitchen sink.

The foreign function interface provides the tools needed to write a network programming library, and there is an example of using it to do socket programming in the examples directory (see [socket.ss](https://github.com/cisco/ChezScheme/blob/master/examples/socket.ss) and [csocket.c](https://github.com/cisco/ChezScheme/blob/master/examples/csocket.c) in the [example](https://github.com/cisco/ChezScheme/tree/master/examples) directory).

There are also libraries that have already been written for this including: @arcfide's [chez-sockets](https://github.com/arcfide/chez-sockets) library, @evilbinary's [scheme-lib](https://github.com/evilbinary/scheme-lib) that supports a wide variety of FFI-based features, and @becls' [swish-win](https://github.com/becls/swish-win) and [swish](https://github.com/becls/swish) which provide a framework for writing Scheme programs with Erlang-style concurrency and supports network programming (amongst other things) for Windows or *nix operating systems.

**Comment by W4anD0eR96** [comment]
OK so I could either write it by myself or use an exist lib. Thank you. I feel good with such philosophy.
