### ISSUE TITLE
c/expeditor.c includes xlocale.h and it shouldn't

### ISSUE THREAD

**Issue by ebenbruyns** [cisco/ChezScheme#268]
remove the include to xlocale.h it breaks the build on later versions of glic since it was removed. locale.h is included right above it. xlocale.h is redundant as it's a subset of locale.h

once removed it builds fine.

**Comment by weinholt** [comment]
This was already fixed in https://github.com/cisco/ChezScheme/commit/b04e9123a427034a39fc9084ba2a8b04608bbb3b
