### ISSUE TITLE
Compile on Windows: cannot find "winver.h"

### ISSUE THREAD

**Issue by metab0t** [cisco/ChezScheme#27]
When I try to build it on Windows, I met the following error.

```
rc -r /fo ..\boot\ta6nt\scheme.res -DWIN32 scheme.rc
Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation.  All rights reserved.

scheme.rc(1) : fatal error RC1015: cannot open include file 'winver.h'.
NMAKE : fatal error U1077: “"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\rc.EXE"”:
 return “0x1”
Stop.
```

It seems that some header files cannot be found.

My environment:
Windows 10 1511 Professional
Microsoft Visual Studio 2015 Update 1

**Comment by burgerrg** [comment]
I updated the build procedure so that it automatically loads the environment variables required by Visual Studio 2015. See if the updated procedure resolves this issue for you.
