### ISSUE TITLE
String chez scheme passed to c can not operate?

### ISSUE THREAD

**Issue by guenchi** [cisco/ChezScheme#276]
```scheme
  (define request
    (lambda (info)
        (let ((code (foreign-callable info (string string string) string)))
            (lock-object code)
            (foreign-callable-entry-point code))))

(define handle_get
     (request
           (lambda (request_header path_info payload)
                (here_back_the_value_of_respone_to_C_function))))
```
```c
typedef char* (*res)(char* request_header, char* path_info, char* payload); 


res res_get;

int handle_request(res response_get)
{
		res_get = response_get;
}
```
```scheme
 (handle_request req_get)
```
in a  C function

```c
char* respone = res_get(request_header, path_info, query_stirng);
```

if strcpy() the respone

```bash
Exception: invalid memory reference.  Some debugging context lost
```

I can't do any thing to operate to respone or get its value.

**Comment by akeep** [comment]
I'm not sure from your example what the problem you are running into is.

I created a library ``t.c`` based on the test code in your example:

```c
typedef char* (*res)(char* request_header, char* path_info, char* payload); 

res res_get;

int handle_request(res response_get)
{
  res_get = response_get;

  return 0;
}

char* call_request(char* request_header, char* path_info, char* query_string)
{
  return res_get(request_header, path_info, query_string);
}
```

Then I compiled it (on macOS):

```
gcc -dynamiclib -o t.dylib t.c
```

And finally, I loaded it and called it from the Chez Scheme repl (again based on your example, though I didn't see the ``handle_request`` definition in the email I got from GitHub:

```
% scheme
Chez Scheme Version 9.5.1
Copyright 1984-2017 Cisco Systems, Inc.

> (load-shared-object "./t.dylib")
> (define res
    (lambda (f)
      (let ([code (foreign-callable f (string string string) string)])
        (lock-object code)
        (foreign-callable-entry-point code))))
> (define handle-request (foreign-procedure "handle_request" (void*) int))
> (define call-request (foreign-procedure "call_request" (string string string) string))
> (define foo (lambda (a b c) (string-append c "::" b "::" a)))
> (handle-request (res foo))
0
> (call-request "this" "is" "test")
"test::is::this"
```

So, maybe the example will be helpful.

-andy:)

**Comment by guenchi** [comment]
thx for your response.

so here is the original code that I got the problem.

https://github.com/guenchi/Igropyr/blob/master/igropyr/src/httpc.c

line 291:

char* respone = res_get(request_header, path_info, query_stirng);

when I use "strcpy" to respone, or anything to operating it. like 

```
char* end = respone;
end++;
*end = '\0';
```

the programme will crash.

**Comment by akeep** [comment]
I'm not sure I understand exactly what code is leading to the problem.  Maybe you could post a more complete example with the igropyr code?  Or if it is too long, you could put a snippet of the ``httpc.c`` change that causes the error to occur?

**Comment by guenchi** [comment]
@akeep 

I can't reproduce the problem, maybe it because

`(define handle-request (foreign-procedure "handle_request" (void*) int))`

i have used iptr instead of void*.

 I have changed it since "https://github.com/cisco/ChezScheme/issues/272"

now i can use 
```
char* end = respone;
end++;
*end = '\0';
```

but the strcpy isn't work:

if you want try:

https://github.com/guenchi/Igropyr/blob/master/igropyr/src/httpc.c

line 296 change to: 
```
char* file_path;
strcpy(file_path, respone);
```
and change 
https://github.com/guenchi/Igropyr/blob/master/igropyr/http.sc
line 57 
change procedure to:
```
(define sendfile
        (lambda (type content)
            (string-append " " content " application/octet-stream")))
```
now use this code to run:
```
(import (igropyr http))

    (define test
        (lambda (request-header path-info query-string)
            (sendfile 200 "filename.postfix" )))

(server 
    (request test)
    (request test)     
    (set 
        ('staticpath "/file/path/"))
    (listen 8080))
```
you will got:
Exception: invalid memory reference.  Some debugging context lost


By the way, would you please to look a little line 46 - 47.
https://github.com/guenchi/Igropyr/blob/master/igropyr/src/httpc.c
if I free the memory by hand, the programme will crash.
the programme running good if I don't free it. 
I'm not sure if it's Chez Scheme manage this memory or here will cause a memory leak. thx
