### ISSUE TITLE
typo in TSPL4

### ISSUE THREAD

**Issue by ocyzl** [cisco/ChezScheme#278]
https://www.scheme.com/tspl4/objects.html#./objects:h10 says:
> `bytevector-copy!` overwrites the _n_ bytes of _dst_ starting at _dst-start_ with the _n_ bytes of _dst_ starting at _src-start_.

The second _dst_ should be _src_ instead.

**Comment by ocyzl** [comment]
https://www.scheme.com/tspl4/objects.html#./objects:h5 says:

> _Fixnums_ represent exact integers in the fixnum range, which is required to be a closed range [-2<sup>_w_-1</sup>,2<sup>_w_-2</sup> - 1], where _w_ (the _fixnum width_) is at least 24.

The right endpoint of the range should be 2<sup>_w_-1</sup> - 1, not 2<sup>_w_-2</sup> - 1.

**Comment by ocyzl** [comment]
https://www.scheme.com/tspl4/objects.html#./objects:h4 says:

> A mantissa width <tt>|<i>w</i></tt> may appear as the suffix of a real number or the real components of a complex number written in floating-point or scientific notation. The mantissa width <tt><i>m</i></tt> represents the number of significant bits in the representation of the number.

<tt><i>m</i></tt> should be <tt><i>w</i></tt>.  (Or vice versa.)

**Comment by ecraven** [comment]
Are the sources of TSPL online anywhere (like csug is)? That might make actual PRs easier.

**Comment by dybvig** [comment]
Thanks for the corrections, @ocyzl.   I've updated the online version at [https://www.scheme.com/tspl4/](https://www.scheme.com/tspl4/) and the errata at [https://www.scheme.com/tspl4-errata.html](https://www.scheme.com/tspl4-errata.html).  If you'd like the errata to acknowledge you by name rather than by github handle, let me know.

@ecraven, I do not have permission from MIT Press to put the sources online.

**Comment by ocyzl** [comment]
https://www.scheme.com/tspl4/objects.html#./objects:s144 says:
> If <tt><i>exint<sub>2</sub></i></tt> is negative, <tt>bitwise-arithmetic-shift</tt> returns the
result of arithmetically shifting <tt><i>exint<sub>1</sub></i></tt> right by <tt><i>exint<sub>2</sub></i></tt> bits.

The last <tt><i>exint<sub>2</sub></i></tt> should be <tt>-<i>exint<sub>2</sub></i></tt>.

**Comment by ocyzl** [comment]
https://www.scheme.com/tspl4/objects.html#./objects:s260

For both `bytevector->uint-list` and `bytevector->sint-list`, in the description of the return value, "_`size`_-bit" should be "_`size`_-byte".

**Comment by ocyzl** [comment]
https://www.scheme.com/tspl4/objects.html#./objects:s224 says:

> <tt><i>start</i></tt> and <tt><i>end</i></tt> must be exact nonnegative integers;<tt><i>start</i></tt> must be less than the length of <tt><i>string</i></tt>, while <tt><i>end</i></tt> may be less than or equal to the length of <tt><i>string</i></tt>. If <tt><i>end</i></tt>&nbsp;&le;&nbsp;<tt><i>start</i></tt>, a string of length zero is returned.

But R6RS allows <tt><i>start</i></tt> to be equal to the length of <tt><i>string</i></tt>, and does not allow it to be greater than <tt><i>end</i></tt>.

(The actual behavior of Chez Scheme follows R6RS and not TSPL4.)

**Comment by ocyzl** [comment]
The last example at https://www.scheme.com/tspl4/objects.html#./objects:s216 is:
> <tt>(string-ci=?&nbsp;"Stra\sse"&nbsp;"Strasse")</tt>

I guess it should be:
> <tt>(string-ci=?&nbsp;"Straße"&nbsp;"Strasse")</tt>

**Comment by ocyzl** [comment]
http://cisco.github.io/ChezScheme/csug9.5/io.html#./io:s55 says:
> The buffer mode <tt><i>b-mode</i></tt> defaults to <tt>block</tt>, which differs from <tt>block</tt> in <i>Chez&nbsp;Scheme</i> only for textual output ports. See the lead-in to Section&nbsp;<a href="http://scheme.com/tspl4/./io.html#g123">7.2</a> of <i>The Scheme Programming Language, 4th Edition</i> for a description of the constraints on and effects of the other arguments.

> The Revised<sup>6</sup> Report version of this procedure does not accept the optional <tt><i>b-mode</i></tt> and <tt><i>?transcoder</i></tt> arguments, which limits it to an implementation-dependent buffering mode (<tt>block</tt> in <i>Chez&nbsp;Scheme</i>) and binary output.

1) <tt>block</tt> differs from <tt>block</tt>?
2) We're describing <tt>(standard-input-port)</tt> here, so why talk about textual output ports or binary output?
3) There are no other arguments.

**Comment by ocyzl** [comment]
https://www.scheme.com/tspl4/libraries.html#./libraries:h2 says:

> If code is intended for use with systems that do not automatically determine
when a library's bindings must be made available, however, the <tt>for</tt>
must be used if the importing library's bindings would not otherwise be
available at the right time.

I'm not sure, but I think "importing" should be "imported".

**Comment by ocyzl** [comment]
https://www.scheme.com/tspl4/libraries.html#./libraries:h2 says:
> Similarly, a <tt>&lt;=</tt> <tt><i>subversion-reference</i></tt> matches a <tt><i>version</i></tt>'s <tt><i>subversion</i></tt> if the <tt><i>version</i></tt>'s <tt><i>subversion</i></tt> is less than or equal to the <tt><i>subversion</i></tt> appearing within the <tt>&gt;=</tt> form.

"the <tt>&gt;=</tt> form" should be "the <tt>&lt;=</tt> form".

**Comment by ocyzl** [comment]
https://www.scheme.com/tspl4/libraries.html#./libraries:h4 says:
> The syntactic extension <tt>set</tt> expands into a reference to the variable <tt>list-&gt;set</tt>, and <tt>member?</tt> similarly expands into a reference to the variable <tt>$member?</tt>. While <tt>list-&gt;set</tt> is explicitly exported, <tt>$member?</tt> is not. This makes <tt>$member?</tt> an indirect export.

There is no variable called <tt>$member?</tt>. Apparently it was changed to <tt>member-help?</tt>.

**Comment by dybvig** [comment]
I've updated TSPL (and in the case of the standard-input-port entry, CSUG) and added errata entries for the tspl fixes (all but the "Straße" issue, since that was an html formatting problem).  Thanks for the corrections!
