### ISSUE TITLE
Consider hosting csug somewhere

### ISSUE THREAD

**Issue by michaellenaghan** [cisco/ChezScheme#28]
scheme.com has docs up to version 8.4. Obviously a lot has happened since then. It would be great if the docs for the most recent version—and, ideally, any intervening versions—were hosted there or elsewhere. (The point isn't so much that the intervening versions would be of great use today, it's that going forward people may lag, and it's nice to be able to find the docs for the version you're actually using. So as general policy it would be nice if all versions were hosted, past or future.)

**Comment by hyln9** [comment]
pdf version:
[mirror](http://cdn.virgil.xyz/csug9/csug.pdf)

html version:
[mirror 1](http://gwatt.github.io/csug/csug.html)
[mirror 2](http://cdn.virgil.xyz/csug9/csug.html)

**Comment by akeep** [comment]
I've created an official post of the (recently released) Chez Scheme Users Guide for version 9.4, both in [html](http://cisco.github.io/ChezScheme/csug9.4/index.html) and [pdf](http://cisco.github.io/ChezScheme/csug9.4/csug9_4.pdf).

In addition, I've created a Chez Scheme project page at: http://cisco.github.io/ChezScheme with links to additional resources (such as The Scheme Programming Language and the official Chez Scheme mailing list).
