### ISSUE TITLE
typo in CSUG9.5

### ISSUE THREAD

**Issue by ocyzl** [cisco/ChezScheme#280]
http://cisco.github.io/ChezScheme/csug9.5/numeric.html#./numeric:h1 says:

> The Revised<sup>6</sup> Report distinguishes two types of special numeric objects: fixnums and flonums. <i>Chez&nbsp;Scheme</i> additionally distinguishes <i>bignums</i> (exact integers outside of the bignum range) and <i>ratnums</i> (ratios of exact integers).

Bignums are outside the fixnum range, not outside the bignum range.

**Comment by ecraven** [comment]
I believe https://github.com/cisco/ChezScheme/blob/master/csug/csug.stex is the source of csug, maybe if you added a pull request, that might be easier to merge?

**Comment by dybvig** [comment]
Thanks.  I have updated the sources and pushed new html/pdf files to the project page.

**Comment by ocyzl** [comment]
http://cisco.github.io/ChezScheme/csug9.5/use.html#./use:h3 says:

<blockquote>For example, assuming that <tt>yin</tt> and <tt>yang</tt> have not
been defined,
<p>
<p><tt>(define&nbsp;yin&nbsp;(lambda&nbsp;()&nbsp;(-&nbsp;(yang)&nbsp;1)))</tt>
<p>defines <tt>yin</tt> at top level as a variable to a procedure that calls
the value of the top-level variable <tt>yang</tt>, even though <tt>yang</tt>
has not yet been defined.</blockquote>

Probably, "a variable to a procedure" should be "a variable bound to a procedure".
