### ISSUE TITLE
build failing on NetBSD

### ISSUE THREAD

**Issue by jessup** [cisco/ChezScheme#281]
Following #7, I generated boot files for M=a6nb on W=i3le using the method that is now described in BUILDING:

(cd $W ; make -f Mf-boot $M.boot)

This seemed to go well, so I moved boot/a6nb to the BSD machine, then called configure with no flags.

Building stats.c fails in this situation. I have done some tinkering with a6nb/c/Makefile, to see if this is just a problem with my system libraries being in strange places, but to no avail.

uname -prs: NetBSD 8.0_BETA x86_64
Here's the output from gmake --debug:

GNU Make 4.1
Built for x86_64--netbsd
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating goal targets....
 File 'build' does not exist.
Must remake target 'build'.
(cd a6nb && gmake build)
GNU Make 4.1
Built for x86_64--netbsd
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating goal targets....
 File 'build' does not exist.
Must remake target 'build'.
(cd c ; gmake)
GNU Make 4.1
Built for x86_64--netbsd
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating goal targets....
 File 'doit' does not exist.
   File '../bin/a6nb/scheme' does not exist.
     File '../boot/a6nb/kernel.o' does not exist.
         Prerequisite '../zlib/configure.log' is newer than target '../zlib/zconf.h'.
         Prerequisite '../zlib/configure.log' is newer than target '../zlib/zlib.h'.
       File 'stats.o' does not exist.
      Must remake target 'stats.o'.
gcc  -m64 -Wpointer-arith -Wextra -Werror -O  -c -DX86_64 -I../boot/a6nb -I../zlib -I/usr/X11R7/include -I/usr/pkg/include -I/usr/pkg/include/ncurses -I/usr/local/include -I/usr/X11R6/include stats.c
In file included from system.h:17:0,
                 from stats.c:26:
externs.h:324:49: error: 'struct timespec' declared inside parameter list [-Werror]
 extern void S_gettime PROTO((INT typeno, struct timespec *tp));
                                                 ^
../boot/a6nb/scheme.h:12:18: note: in definition of macro 'PROTO'
 #define PROTO(x) x
                  ^
externs.h:324:49: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
 extern void S_gettime PROTO((INT typeno, struct timespec *tp));
                                                 ^
../boot/a6nb/scheme.h:12:18: note: in definition of macro 'PROTO'
 #define PROTO(x) x
                  ^
stats.c:231:6: error: conflicting types for 'S_gettime'
 void S_gettime(INT typeno, struct timespec *tp) {
      ^
In file included from system.h:37:0,
                 from stats.c:26:
externs.h:324:13: note: previous declaration of 'S_gettime' was here
 extern void S_gettime PROTO((INT typeno, struct timespec *tp));
             ^
cc1: all warnings being treated as errors
Makefile:30: recipe for target 'stats.o' failed
gmake[2]: *** [stats.o] Error 1
Makefile:20: recipe for target 'build' failed
gmake[1]: *** [build] Error 2
Makefile:19: recipe for target 'build' failed
gmake: *** [build] Error 2

**Comment by jessup** [comment]
including "sys/time.h" in externs.c fixes this

**Comment by ismaell** [comment]
Just for completeness, in addition to NetBSD, the issue affects most musl-based systems (musl 1.2.x).
