### ISSUE TITLE
Can any boy integrate the GMP Bignum Library into ChezScheme?

### ISSUE THREAD

**Issue by yezhiqiu1998** [cisco/ChezScheme#285]
Can any boy integrate the GMP Bignum Library into ChezScheme? 
I find that ChezScheme is so fast in simple addition and subtraction, almost fast as C, but too slow in bignum's operation!

**Comment by akeep** [comment]
@ye-Zhiqiu Unfortunately, GMP's license is incompatible with Chez Scheme's license.  As @dybvig mentioned in Issue #14:

> Using gmp would indeed speed up programs that operate on large numbers, particularly programs that multiply and divide very large numbers. Licensing is the primary issue blocking us from using it. Another is that our own, different representation of bignums is baked into the compiler and run-time system in a couple of ways.

We are open to alternative suggestions, I know there was a group involved in Issue #14 that was starting to look into this, but I've not heard if they've come to any conclusions.

**Comment by nosefouratyou** [comment]
What about using [bsdnt](https://github.com/wbhart/bsdnt) or [LibBF](https://bellard.org/libbf/)?

**Comment by akeep** [comment]
Again from #14, if I may quote myself:

>As we think about trying to improve the bignum implementation in Chez, it might be interesting to take a look at the Glasgow Haskell Compiler (GHC) work around the same issue: https://ghc.haskell.org/trac/ghc/wiki/ReplacingGMPNotes.
>
> They started from a different point, in that GHC had been using the GNU MP, but there were uses of GHC for whom the LGPL licensing of GNU MP was problematic (see: https://ghc.haskell.org/trac/ghc/ticket/601). They experimented with a number of other fast arbitrary precision libraries with more permissive licenses, as well as creating a "fast enough" implementation in Haskell. One (or more) of these more permissively licensed libraries might be an interesting option for improving Chez's bignum performance. As of 7 years ago (when the GHC community went through this exercise), there were quite a few interesting trade offs in performance given the libraries available at the time. I found an additional library, [bigz](https://sourceforge.net/projects/bigz/), listed on the [wikipedia arbitrary precision page](https://en.wikipedia.org/wiki/List_of_arbitrary-precision_arithmetic_software). Since it has been 7 years since the GHC community did these experiments, it is probably worth evaluating the options again.

I would recommend comparing some of the available options, would be a good starting point to choosing a new bignum implementation.  [bsdnt](https://github.com/wbhart/bsdnt) is a fine place to start.  I would note that [LibBF](https://bellard.org/libbf/) is a library for arbitrary precision floating point numbers, so it is not appropriate for the bignum implementation, which is for integers.  Chez Scheme does not currently have arbitrary precision floating point support.

**Comment by ye-Zhiqiu** [comment]
@akeep Thank you very much, I am so foolish! I am learning SICP book recently, when i try to compute fib function，ChezScheme took about 0.6sec for n=1000,000, and more than 80sec for n=10,000,000, is slower than mit-scheme. 
I tried to use python3 for the same algorithm, it takes about 2sec for n=10,000,000.
I also tried to use GMP Library  to compute fib function, it takes about 1.2sec for n=100,000,000. 
I was using Chez to compute the sum of 0->n, found it is so fast even faster than using C language. So I think Chez is really very fast, but could be improved at bignum's computation.

I just think Chez is limited, at bignum's computation, no other meanings. maybe I should learn more about git/github and variant Open Source Licenses and improve English before come here to ask question!

**Comment by akeep** [comment]
@yezhiqiu1998 No worries, you are right that Chez Scheme is not as fast as it could be at bignum math.  The bignum support is pretty baked in though, so we wouldn't be able to get around the requirements of LGPL's licensing if we used it.

As @nosefouratyou noted, there are some more liberally licensed alternatives that might be good alternatives to our current implementation.  It looks like the group that had been taking a look at this in #14 did not get to a place where they had something they wanted to share.

Hopefully, I'll get a little free time to look at some of this stuff at some point.  There are always things to improve in a compiler :)
