### ISSUE TITLE
How to set ChezScheme to support a utf-8 encoding path?

### ISSUE THREAD

**Issue by yezhiqiu1998** [cisco/ChezScheme#286]
When I use Chezscheme to run a scheme file whose absolute path contain utf-8 encoding in sublime_text, Chez will report an error:
Exception in load: the_file_absolute_path: no such file or directory!
 But if I run the file with Chez in a terminal with a relative path, it well done. Please tell me whether Chez doesn't support a utf-8 encoding directory or I didn't set it well to work!

**Comment by burgerrg** [comment]
You are correct. Chez Scheme currently handles only ASCII-encoded paths. See Issue https://github.com/cisco/ChezScheme/issues/81 for details. I plan to fix this.

**Comment by yezhiqiu1998** [comment]
Thanks!

**Comment by burgerrg** [comment]
Commit https://github.com/cisco/ChezScheme/commit/aa1c2c4ec95c286a12730ea75588a18dd9fb9d59 should fix this. Please re-open this issue if it does not.

**Comment by yezhiqiu1998** [comment]
Thanks, I tested it on linux, it worked well.
