### ISSUE TITLE
Difference in error semantics with cp0 enabled

### ISSUE THREAD

**Issue by laqrix** [cisco/ChezScheme#293]
Using commit `0be4cfd` (the current tip of master):

```
Chez Scheme Version 9.5.1
Copyright 1984-2017 Cisco Systems, Inc.

> (let ([v (values 1 2)]) v)
1
2
> (run-cp0 (lambda (f x) x))
> (let ([v (values 1 2)]) v)
Exception: returned two values to single value return context
> 
```

**Comment by gwatt** [comment]
This behavior is actually OK. It's explicitly called out in r6rs here: http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_sec_11.20 at the bottom of the page. It's exactly the same in r5rs and r7rs as well.

However, you have disabled cp0 and thus Chez Scheme does not reduce the let expression to the values form.

**Comment by laqrix** [comment]
Practically, this hasn't been a problem. I was surprised to find one of my own macros could reduce to an expression where multiple values seem valid.  Disabling cp0 was just to demonstrate the difference in error behavior.

**Comment by mflatt** [comment]
There's no difference, anymore, as of the v9.9.9 merge.
