### ISSUE TITLE
the result list of map is out of order

### ISSUE THREAD

**Issue by maihengrui** [cisco/ChezScheme#294]
I used chez sheme to process my lab data for gnuplot plot, but it seens there is a bug. 
```scheme
(define range
  (lambda (start end step)
    (let loop ((result '())
	       (start start)
	       (end end)
	       (step step))
      (if (> (+ start step) end)
	  (reverse (cons start result))
	  (loop (cons start result)
		(+ start step)
		end
		step)))))

(define format-pair-for-gnuplot
  (lambda (x y)
    (display (format "~,3f ~,2f" x y))
    (newline)
    (flush-output-port (current-output-port))))

(let ((outV '(0 1.26 2.39 2.96 3.42 3.81 4.19 4.53 4.93 5.26 5.41 5.49 5.54 5.58 5.62 5.65 5.68 5.71
		5.73 5.76 5.78 5.80 5.82 5.84 5.86 5.88 5.92 5.93 5.94 5.96 5.97 5.98 5.97 5.98 5.98))
      (inX (range 0 3.500 0.1)))
  (map (lambda (x y) (format-pair-for-gnuplot x y))
       inX outV))
```

I would like the output x is rise from 0 to 3.4, but it is out of order:

> 3.400 5.98
3.200 5.97
3.300 5.98
3.000 5.97
3.100 5.98
2.800 5.94
2.900 5.96
2.600 5.92
2.700 5.93
2.400 5.86
2.500 5.88
2.200 5.82
2.300 5.84
2.000 5.78
2.100 5.80
1.800 5.73
1.900 5.76
1.600 5.68
1.700 5.71
1.400 5.62
1.500 5.65
1.200 5.54
1.300 5.58
1.000 5.41
1.100 5.49
0.800 4.93
0.900 5.26
0.600 4.19
0.700 4.53
0.400 3.42
0.500 3.81
0.200 2.39
0.300 2.96
0.000 0.00
0.100 1.26

**Comment by svenha** [comment]
The processing order of `map` is not specified in RnRS.

**Comment by maihengrui** [comment]
oh, yeah I get it. Thank you.
