### ISSUE TITLE
.gitignore includes "Makefile", masking out Makefiles that are part of the distribution

### ISSUE THREAD

**Issue by michaellenaghan** [cisco/ChezScheme#30]
For example:

 * https://github.com/cisco/ChezScheme/blob/master/csug/Makefile
 * https://github.com/cisco/ChezScheme/blob/master/release_notes/Makefile

**Comment by michaelballantyne** [comment]
Including `Makefile` in `.gitignore` only hides any `Makefile` found in the top directory of the project; it does not apply to subdirectories. The `.gitignore` file would only hide the files you list if a pattern like `**/Makefile` was included.

The top-level Makefile is generated by the `configure` script, so hiding it is appropriate.

**Comment by michaellenaghan** [comment]
Thanks, you're right; the problem was that my editor was applying .gitignore incorrectly.

**Comment by burgerrg** [comment]
The .gitignore file should use /Makefile instead of Makefile, just as you suggested. Thanks so much for finding this!

**Comment by burgerrg** [comment]
Fixed in commit 7097480fb77931ea9bc47849d555a6295cf659d7.
