### ISSUE TITLE
interpreter

### ISSUE THREAD

**Issue by velkyel** [cisco/ChezScheme#309]
hello,

is it interpreter still available?  It would be nice to have embeddable scheme on ios.

**Comment by akeep** [comment]
Yes the interpreter is part of the Chez Scheme system (and is tested as part of the automated tests).

The executable for both Chez Scheme and Petite Chez Scheme (the interpret) is the same, with the default names of `scheme` and `petite` where `petite` is a hard link to `scheme`.  If you look at the installed files with Chez Scheme you'll see that there is a `petite.boot` and `scheme.boot` when `petite` is run, only `petite.boot` is loaded.  This boot file contains the core Chez Scheme libraries and the interpreter.  When `scheme` is run, it loads both the `petite.boot` file and the `scheme.boot` file, and the `scheme.boot` file contains the compiler.

It is worth noting that both use the same C run time and the interpreter (as well as compiler for that matter) is written in Scheme, as are many of the basic Scheme libraries, with support from the run time.

I'm not sure how the interpreter existing helps with making Chez Scheme embeddable on iOS, but I've not looked at the iOS constraints in a while.

**Comment by velkyel** [comment]
thanks for info. closing.
