### ISSUE TITLE
How can I access C macro definitions from Chez?

### ISSUE THREAD

**Issue by bmansurov** [cisco/ChezScheme#312]
I'd like to access [M_E](https://www.gnu.org/software/gsl/doc/html/math.html#mathematical-constants) from Chez, for example. Is there anything similar to `foreign-procedure` for macros?

**Comment by gwatt** [comment]
Well, you can't. That would require Chez Scheme to parse C header files, which it does not do. However, the [(exp x)](https://scheme.com/tspl4/objects.html#./objects:s129) function returns e<sup>x</sup> So you can get a value of `e` with `(exp 1)`

**Comment by bmansurov** [comment]
Thank you.
