### ISSUE TITLE
Released version not compiling on the latest Ubuntu due to breaking change in glibc

### ISSUE THREAD

**Issue by jaseemabid** [cisco/ChezScheme#313]
I'm effectively reopening a previous issue, https://github.com/cisco/ChezScheme/issues/220.

The latest release v9.5 from tag adb3b7b is from Oct 12, 2017 and the commit that fixed the issue https://github.com/cisco/ChezScheme/commit/b04e9123a427034a39fc9084ba2a8b04608bbb3b happened 2 days later. Package maintainers are forced to do odd hacks [like this](https://github.com/jaseemabid/chez-scheme/blob/master/PKGBUILD#L21) to make this work as of now. 

There are over 100 commits on master since the fix, so will it be possible to make a new release with this fix? Maybe a patch version like v9.5.1?

**Comment by amirouche** [comment]
master does build on ubuntu 18.10 (cosmic)

**Comment by mflatt** [comment]
Closing, since the repair has made it into a released version by now.
