### ISSUE TITLE
How to create a foreign procedure for this C code?

### ISSUE THREAD

**Issue by bmansurov** [cisco/ChezScheme#314]
Given this C code:
```lang=C
float  cblas_sdot(const int N, const float  *X,
    const int incX, const float  *Y, const int incY);
```
what would the equivalent Scheme foreign-procedure look like? I'm not sure how to represent `float *X`.

**Comment by gwatt** [comment]
Any time you need to represent a pointer in the FFI you do `(* type)`.
The full foreign-procedure expression would be
```
(foreign-procedure "cblas_sdot" (int (* float) int (* float) int) float)
```

**Comment by gwatt** [comment]
I think you'll need to manually allocate the memory for an ftype-pointer and fill it from the vector using `ftype-set!`

**Comment by bmansurov** [comment]
OK, thanks.
