### ISSUE TITLE
exact->inexact not in rnrs?

### ISSUE THREAD

**Issue by trivialfis** [cisco/ChezScheme#316]
Chez Scheme Version 9.5
Running the following code snippet:
```
(library (test)
  (export inexact-number->string)
  (import (rnrs))

  (define (inexact-number->string x) (number->string (exact->inexact x))))
```

results in 
> Exception: attempt to reference unbound identifier exact->inexact at line 5, char 55 of test.scm

I tried to read up r6rs, and it's in there. I know (import (chezscheme)) would make it right, but I think importing rnrs would brought the procedure into scope. Am I wrong?

**Comment by akeep** [comment]
In r6rs `exact->inexact` is defined in the r5rs compatibility library, which is not included in the overall `rnrs` library, so you need to import `(rnrs r5rs)`:

```scheme
(library (test)
    (export inexact-number->string)
    (import (rnrs) (rnrs r5rs))
    (define (inexact-number->string x) (number->string (exact->inexact x))))
```

See [Chapter 19: R5RS Compatibility](http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-20.html#node_chap_19) which defines the `(rnrs r5rs (6))` library and [Chapter 15: Composite Library](http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-16.html#node_chap_15), which lists `(rnrs r5rs (6))` as one of the excluded libraries.

Incidentally, the r6rs name for `exact->inexact` is `inexact`, if you'd prefer to use the r6rs naming.

**Comment by trivialfis** [comment]
@akeep Thanks.
