### ISSUE TITLE
[documentation] Wrong/missing library load in Chez Scheme 9.5 FFI example Socket Operations

### ISSUE THREAD

**Issue by superboum** [cisco/ChezScheme#319]
I was reading the [Chez-Scheme documentation - Section 4.9 - Example: Socket Operations](https://cisco.github.io/ChezScheme/csug9.5/foreign.html#./foreign:h9) and was a bit surprised by the following code: 

```scheme
;;; Requires csocket.so, built from csocket.c.
(case (machine-type)
  [(i3le ti3le) (load-shared-object "libc.so.6")]
  [(i3osx ti3osx) (load-shared-object "libc.dylib")]
  [else (load-shared-object "libc.so")])

;;; Requires from C library:
;;;   close, dup, execl, fork, kill, listen, tmpnam, unlink
(load-shared-object "libc.so") 
```

Shouldn't it be this instead?

```scheme
;;; Requires from C library:
;;;   close, dup, execl, fork, kill, listen, tmpnam, unlink
(case (machine-type)
  [(i3le ti3le) (load-shared-object "libc.so.6")]
  [(i3osx ti3osx) (load-shared-object "libc.dylib")]
  [else (load-shared-object "libc.so")])

;;; Requires csocket.so, built from csocket.c.
(load-shared-object "csocket.so") 
```

It seems to be necessary to load our own library and doesn't make sense to load the libc twice...

**Comment by guenchi** [comment]
yes

**Comment by burgerrg** [comment]
Thanks for finding this inconsistency with the code in the examples folder. I updated the documentation to be in sync with the code and added 64-bit Linux to the machine-case. See https://github.com/cisco/ChezScheme/commit/5bdf715809e5847dfa0807216bcc6d0dac2f10ea.

**Comment by burgerrg** [comment]
We update the web pages more frequently than stable releases. Since the last update was from March, I just checked in a new update. Thanks for pointing this out!
