### ISSUE TITLE
Invalid memory reference in foreign-callable clause 29 of foreign.ms in a6nt

### ISSUE THREAD

**Issue by burgerrg** [cisco/ChezScheme#322]
@mflatt The a6nt `foreign.mo` foreign-callable clause 29 mat fails:
```
(eqv?
  (let ()
    (define-ftype foo (function (fixnum fixnum ptr) fixnum))
    (define f
      (lambda (n m k)
        (if (fx= n 0)
            (k m)
            (if (fx= (fxmodulo n 10) 0)
                (k (call/cc (lambda (k) (g (fx- n 1) (fx+ m 1) k))))
                (g (fx- n 1) (fx+ m 1) k)))))
    (define fptr (make-ftype-pointer foo f))
    (define g (ftype-ref foo () fptr))
    (let ([v ($with-exit-proc
               (lambda (k) (f $stack-depth $base-value k)))])
      (unlock-object
        (foreign-callable-code-object (ftype-pointer-address fptr)))
      v))
  (+ $stack-depth $base-value))
Error in mat foreign-callable clause 29: "invalid memory reference.  Some debugging context lost" at line 2364, char 3 of foreign.ms
```

When run in isolation, this particular test passes. It seems to require a couple of the previous expressions. It passes on ta6nt, i3nt, and ti3nt.

Commit https://github.com/cisco/ChezScheme/commit/aa1c2c4ec95c286a12730ea75588a18dd9fb9d59 triggered this failure on a6nt, but I don't think it caused it. When I cherry-pick this commit back to a branch from the foreign-procedure changes (de860f2f4c50eeda7e540b7b44fd7d0d1b7dad90), the `foreign.mo` mats pass. Immediately after those changes, it fails. I suspect some heap corruption in the foreign-procedure/callable code on 64-bit Windows.

**Comment by mflatt** [comment]
I'm still looking at this one, but I haven't been able to provoke it by running `make foreign.so` by itself – only by running `make test`. Do you have a shorter way that `make test` that crashes?

**Comment by burgerrg** [comment]
I get it by running `make foreign.mo` and then looking for the word `clause` in foreign.mo.

**Comment by burgerrg** [comment]
I am using Visual Studio 2017 Version 15.7.1.

**Comment by burgerrg** [comment]
I'm now using Visual Studio 2017 version 15.7.3 on Windows 10 version 1803.
```
$ git clean -fxd .
$ ./configure -m=a6nt
$ cd a6nt
$ make
$ cd mats
$ make foreign.mo
```

I don't get the invalid memory reference if I compile in Debug mode.

**Comment by burgerrg** [comment]
I don't get the invalid memory reference if I compile with /Os (optimize for space) instead of /Ox (optimize for speed). This may indicate a problem with the C code.

**Comment by burgerrg** [comment]
No invalid memory references when compiled with Visual Studio 2015. Hmmm, we might be tickling a Visual Studio 2017 compiler bug here.

**Comment by mflatt** [comment]
Is it possible that in `S_call_help`, copying the `tc` argument to a `volatile` variable will help?

From my understanding of the C spec, neither `code` nor `tc` need to be declared `volatile`, because they don't change after the `setjmp`. But I think GCC declares an incompatibility with the standard and requires `code` and `tc` to be `volatile`. Maybe MSVC has a similar limitation.

Concretely, after changing `S_call_help` to

```
void S_call_help(tc_in, singlep, lock_ts) ptr tc_in; IBOOL singlep; IBOOL lock_ts; {
  /* declaring code volatile should be unnecessary, but it quiets gcc */
  void *jb; volatile ptr code;
  volatile ptr tc = tc_in;
```

then I can no longer provoke a crash with `make test`. But since the crashes are less consistent for me, I'm not sure that means anything.

The change is probably a good idea to accommodate GCC's stated limitations, in any case.

**Comment by mflatt** [comment]
PS - I can get invalid references with VS 2015, just not as easily as you apparently do with VS 2017.

**Comment by burgerrg** [comment]
I looked at the assembly output with various combinations of volatile. The one you recommend does not use rsp after setjmp except when it exits. I think we bumped into a bug with setjmp/longjmp and the MSVC compiler. It also worked for me when no variable was declared volatile. I recommend declaring both volatile.

**Comment by burgerrg** [comment]
@mflatt Thank you very much for the fix! Now all the mats pass on all platforms. See commit https://github.com/cisco/ChezScheme/commit/c2d2467d48eea145455124343c8819dfb683c39e.
