### ISSUE TITLE
Gensyms may contain public IP addresses

### ISSUE THREAD

**Issue by weinholt** [cisco/ChezScheme#338]
Hello schemers,

While going over the code for porting to GNU Hurd (yeah, I know), I found that gensyms may contain public IP addresses. This isn't mentioned in the documentation anywhere that I could find and it surprised me. I'm probably not alone, so I'm opening this issue to have a discussion about whether it's ok or not.

Here's code that extracts the info in gensyms (with some examples from csug): https://gist.github.com/weinholt/7f06739113f1fa78a894ea2ef3945331

People may wish to keep their public IP address hidden and are likely not aware that gensyms can contain them.

**Comment by jltaylor-us** [comment]
> This isn't mentioned in the documentation anywhere that I could find

You mean, like in the description for `(gensym)`?
> Globally unique names are constructed (lazily---see below) from some combination of a unique machine identifier (**such as the network address**), the current process identifier (PID), and the time at which the Scheme session began, along with an internal counter

http://cisco.github.io/ChezScheme/csug9.5/objects.html#./objects:s88

(which is not to say that I disagree with changing the source for the seed used for the unique prefix - just that it is in the documentation)

**Comment by weinholt** [comment]
Oops, my eyes skipped right over that. :)

**Comment by burgerrg** [comment]
I have a proposed update on branch rgburger/uuid, but I don't know how to configure the Travis CI server to find the 32-bit uuid-dev libraries on Linux. Any ideas?

**Comment by burgerrg** [comment]
Thanks, that worked!

**Comment by burgerrg** [comment]
This issue is fixed in 2fd3db68230d094a0d396348a8140a4d3693b120.
