### ISSUE TITLE
Shebang invocations fail when using relative paths

### ISSUE THREAD

**Issue by RhysU** [cisco/ChezScheme#339]
Shebang invocations employing relative paths are not handled correctly.  I expect using a relative path to chezscheme9.5 to work like using a relative path to /bin/sh.  I observe that using a relative path causes Chez to fail during a read operation.  Recreate follows.

> $ which chezscheme9.5 
> /usr/bin/chezscheme9.5
> 
> $ cat foo
> #!/usr/bin/chezscheme9.5 --script
> (display "Hello world")
> (newline)
> 
> $ ./foo
> Hello world
> 
> $ cat bar
> #!../../usr/bin/chezscheme9.5 --script
> (display "Hello world")
> (newline)
> 
> $ file ../../usr/bin/chezscheme9.5
> ../../usr/bin/chezscheme9.5: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=f3f8f4f183b742ebea996f95446b65ccd6c8a4d4, stripped
> 
> $ ./bar
> Exception in read: invalid syntax #!../../usr/bin/chezscheme9.5 at line 1, char 1 of ./bar
> 
> $ cat baz
> #!../../bin/sh
> echo "Relative works for non-Chez"
> 
> $ ./baz
> Relative works for non-Chez

**Comment by jltaylor-us** [comment]
http://cisco.github.io/ChezScheme/csug9.5/use.html#./use:h5
> To support executable shell scripts, the system ignores the first line of a loaded script if it begins with #! followed by a space or forward slash.

**Comment by RhysU** [comment]
Thank you for suggesting a workaround (adding a space). Any reason to not include a leading period in that special treatment?

**Comment by RhysU** [comment]
Also, why the space special treatment?

**Comment by RhysU** [comment]
Space special treatment is consistent with bash (I never knew!):

> $ cat baz
> #! ../../bin/sh
> echo "Relative works with leading space outside Chez"
> 
> $ ./baz
> Relative works with leading space outside Chez

As you suggested, adding a leading space for Chez also works:

> $ cat bar
> #! ../../usr/bin/chezscheme9.5 --script
> (display "Hello world with a space")
> (newline)
> 
> $ ./bar
> Hello world with a space

Please do consider making a leading period treated specially.  I could take a stab at doing so if you'd kindly point me to the right place in the repository.

**Comment by jltaylor-us** [comment]
Looks like that's here
https://github.com/cisco/ChezScheme/blob/master/s/7.ss#L239

However, using a relative path for a shebang is... prone to failure.  The path is interpreted relative to the current directory, not the directory containing the script, as shown in this transcript:
```
tmp$ find shebang
shebang
shebang/foo
shebang/foo/relative
shebang/foo/abs
shebang/ksh

tmp$ cat shebang/foo/abs
#!/tmp/shebang/ksh
echo $KSH_VERSION

tmp$ cat shebang/foo/relative 
#!../ksh
echo $KSH_VERSION

tmp$ shebang/foo/abs
Version AJM 93u+ 2012-08-01

tmp$ shebang/foo/relative 
-bash: shebang/foo/relative: ../ksh: bad interpreter: No such file or directory

tmp$ cd shebang/foo/
foo$ ./relative 
Version AJM 93u+ 2012-08-01
```

If you're going to attempt changes anyway, I'd recommend (personally, not speaking for any of the maintainers) looking for `./` and `../`, rather than `.`.
