### ISSUE TITLE
Now, how to build chez scheme?

### ISSUE THREAD

**Issue by ltoddy** [cisco/ChezScheme#341]
I download the released source code(Chez Scheme Version 9.5).

I type `./configure`. and then I want to type `sudo make install` , but there is no `Makefile` here.

**Comment by ltoddy** [comment]
> cat /etc/os-release

```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
```

**Comment by TisonKun** [comment]
@ltoddy could your please post how you solved this problem here?

**Comment by ltoddy** [comment]
https://github.com/ltoddy/ltoddy.github.io/wiki/%E5%85%B3%E4%BA%8EChez-Scheme%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%E9%97%AE%E9%A2%98

解决方案，以及更改那个 configure 文件。

更改内容为：

https://github.com/cisco/ChezScheme/pull/342/files

**Comment by ltoddy** [comment]
@TisonKun
