### ISSUE TITLE
build fail on windows

### ISSUE THREAD

**Issue by xiaomingfun** [cisco/ChezScheme#344]
I build error on windows cygwin or Microsoft Ubuntu  at first  with output message:

: not found: 2: ./configure:
: not found: 17: ./configure:
: not found: 18: ./configure:
./configure: 19: ./configure: Syntax error: word unexpected (expecting "do")

I guess it's windows text file endline different from linux txt file
so to fix this problem by using vi : 

vi configure
:set fileformat=unix
:wq

vi workarea
:set fileformat=unix
:wq

**Comment by burgerrg** [comment]
Is git configured to use Windows line endings? If so, it may checkout configure with CRLF line endings.

**Comment by xiaomingfun** [comment]
@burgerrg  you are right. it's git settting cause this problem.
after I set git config :

git config --global core.autocrlf false

then git clone again. It can  build right

**Comment by burgerrg** [comment]
Great!

**Comment by burgerrg** [comment]
I added a sentence about this in 1c3a605c6218303f651eec1a8afa5d0bc91337ee.
