### ISSUE TITLE
Get environment variable in ChezScheme

### ISSUE THREAD

**Issue by TisonKun** [cisco/ChezScheme#345]
as title, does ChezScheme support to get environment variable like `HOME`/`PATH`?

**Comment by qzivli** [comment]
(getenv “HOME”) works well.

在 2018年9月5日，20:34，陈梓立 <notifications@github.com<mailto:notifications@github.com>> 写道：


as title, does ChezScheme support to get environment variable like HOME/PATH?

**Comment by qzivli** [comment]
(getenv “HOME”) works well.

**Comment by TisonKun** [comment]
@qzivli thanks for the quick reply! it works as expected. now I am wondering where it is documented.

**Comment by TisonKun** [comment]
found it.

@qzivli you're quite helpful!
