### ISSUE TITLE
Compiling with Visual Studio 2017 and Cygwin

### ISSUE THREAD

**Issue by gus-massa** [cisco/ChezScheme#347]
_FYI:_ I got a new computer and I installed Visual Studio 2017 (Community) and Cygwin. When I compiled Chez Scheme I got this error:

    $ make
    (cd a6nt && make build)
    (cd c ; make)
    cmd.exe /c make.bat
    \cygwin64\cygwin\tmp\dd_vsdevcmd15_preinit_env.log was unexpected at this time.
    make[2]: *** [Makefile:28: ../bin/a6nt/scheme] Error 255
    make[1]: *** [Makefile:20: build] Error 2
    make: *** [Makefile:19: build] Error 2

After a lot of debugging, guessing and searches in Google, I discovered that the problem was that I installed Cygwin as an administrator and I was trying to compile with a normal user. The problem was that the temporary folder was not writable by my user, so some of the .bat files got a weird error when trying to save some temporary data. (The problem was in VsDevCmd.bat that is called by vcvarsall.bat.)

I fixed the problem following the advice of https://cygwin.com/cygwin-ug-net/using.html#usertemp , i.e. 
 
> The usertemp file system can be configured in /etc/fstab like this:

    none /tmp usertemp binary,posix=0 0 0

So I think my problem was a case of a bad cygwin configuration, not a bug in the Chez Scheme compilation. Anyway, the error is too cryptic and it was very difficult to find the solution, so I'm posting this in case someone else has the same problem in the future. 

(I think you can just close this issue, unless you know a much better solution.)

**Comment by burgerrg** [comment]
Thanks for posting this in case others run into the same thing.
