### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by michaelballantyne** [cisco/ChezScheme#35]
I'd like to package Chez for [Homebrew](http://brew.sh/), but Homebrew requires that the upstream project have tagged a stable version as a release before they'll accept the package.

**Comment by turbopape** [comment]
+1 for this !

2016-05-02 10:29 GMT+01:00 Michael Ballantyne <notifications@github.com>:

**Comment by hiddenlotus** [comment]
+1 for this !

**Comment by dybvig** [comment]
We started to tag a release v9.4 but ran into a couple of problems.  We'll try again once we resolve them.

**Comment by dybvig** [comment]
I just tagged a release (v9.4) and will update the main branch via `newrelease` to be 9.4.1 when I get a chance.  The source bundle one can get from github for the release does not include sources for the submodules, but configure will pull them down via curl.

**Comment by michaelballantyne** [comment]
Thanks! Will the 9.4 tag be modified to refer to new releases of 9.4 as they are made, or should I understand it to immutably refer to the first release of 9.4, with patch releases appearing as separate tags?

For packaging with Homebrew I'm after an immutable tag for a specific patch release.

**Comment by dybvig** [comment]
Our intent is that tags be unique.  The next tag will likely be either 9.4.1 or 9.5.
