### ISSUE TITLE
(file-exists? "x/")

### ISSUE THREAD

**Issue by ocyzl** [cisco/ChezScheme#358]
If a regular file named "x" exists, `(file-regular? "x/")` is false and `(with-input-from-file "x/" read)` raises an "invalid argument" exception, yet `(file-exists? "x/")` is true.

**Comment by burgerrg** [comment]
The Windows version of `file-exists?` strips the trailing directory separator. I don't know why. Thanks for reporting this!

**Comment by burgerrg** [comment]
This should be fixed in commit 9017943cdba8c54c8f0acf20b037174780c10039.
