### ISSUE TITLE
Broken links on https://www.scheme.com/resources.html

### ISSUE THREAD

**Issue by andregrigon** [cisco/ChezScheme#363]
The links on https://www.scheme.com/resources.html to http://www.cs.indiana.edu/chezscheme/ appear to be broken (file not found):

- [How to Debug Chez Scheme Programs](http://www.cs.indiana.edu/chezscheme/debug/) ([wayback archive](https://web.archive.org/web/20170328045820/http://www.cs.indiana.edu/chezscheme/debug/))
- [Emacs support for (Petite) Chez Scheme](http://www.cs.indiana.edu/chezscheme/emacs/) ([wayback archive](https://web.archive.org/web/20160826073229/http://www.cs.indiana.edu/chezscheme/emacs/))
- [Publications related to Chez Scheme](http://www.cs.indiana.edu/chezscheme/pubs/) ([wayback archive](https://web.archive.org/web/20170502193933/http://www.cs.indiana.edu:80/chezscheme/pubs/))
- [Portable implementation of syntax-case](http://www.cs.indiana.edu/chezscheme/syntax-case/) ([wayback archive](https://web.archive.org/web/20180911053044/https://www.cs.indiana.edu/chezscheme/syntax-case/))

Would it be possible to fix them?

Thank you for Chez Scheme! I have been using and studying it and it's incredible.

**Comment by andregrigon** [comment]
The pages seem like simple HTML. I would be happy to translate them to Markdown so they could be added to the wiki, if you like.

**Comment by guenchi** [comment]
> The pages seem like simple HTML. I would be happy to translate them to Markdown so they could be added to the wiki, if you'd like.

could you send me a copy? thx

louis.deguenchy WITH gmail.com

**Comment by andregrigon** [comment]
@guenchi 

I created the following gists of the Markdown versions:

[Emacs support for (Petite) Chez Scheme](https://gist.github.com/andregrigon/5f99c76939e6c9f9994a1b01b01b077b)
[How to Debug Chez Scheme Programs](https://gist.github.com/andregrigon/2e5d921e3fa7a188e4066ad313318a91)
[Portable syntax-case](https://gist.github.com/andregrigon/3ed2d2399d69f21aa24eb6439fcdc440)
[Publications related to Chez Scheme](https://gist.github.com/andregrigon/36317c271f05b82dce4efa4f3fa224b1)

**Comment by guenchi** [comment]
> @guenchi
> 
> I created the following gists of the Markdown versions:
> 
> [Emacs support for (Petite) Chez Scheme](https://gist.github.com/andregrigon/5f99c76939e6c9f9994a1b01b01b077b)
> [How to Debug Chez Scheme Programs](https://gist.github.com/andregrigon/2e5d921e3fa7a188e4066ad313318a91)
> [Portable syntax-case](https://gist.github.com/andregrigon/3ed2d2399d69f21aa24eb6439fcdc440)
> [Publications related to Chez Scheme](https://gist.github.com/andregrigon/36317c271f05b82dce4efa4f3fa224b1)

Oh thx it's quite helpful since they original link failed

**Comment by dybvig** [comment]
The links on scheme.com are now fixed.  Thanks!
