### ISSUE TITLE
Mutli-thread test fails when run with boot file

### ISSUE THREAD

**Issue by donaldcallen** [cisco/ChezScheme#383]
This test code lives in the file testit.scm:
```
(top-level-program
  (import (chezscheme))
  (define (main)
    (define begin-mutex (make-mutex))
    (define begin-condition (make-condition))
    (define end-mutex (make-mutex))
    (define test-thunk
      (lambda ()
        (display "hello from the thread\n")
        (mutex-acquire begin-mutex) ;; Acquirable when main thread executes condition-wait
        (mutex-release begin-mutex) ;; Make available to main thread so condition-wait can return
        (mutex-acquire end-mutex) ;; Acquire the mutex that tells the main thread, when released, that the open-positions thread is done
        (condition-broadcast begin-condition) ;; And let the main thread continue
        ;; processing would occur here
        (mutex-release end-mutex)))

    (mutex-acquire begin-mutex) 
    (write (fork-thread test-thunk))
    (newline)
    ;; Wait for thread to acquire the end-mutex
    (display "waiting\n")
    (condition-wait begin-condition begin-mutex)
    (display "ok\n")
    (mutex-acquire end-mutex) ;; Wait until the open positions thread completes
    (display "we're done\n")
    )
  (main)
  )
```

When the source file is loaded into scheme (I am running 9.5.1 acquired within the last few days from github on an up-to-date Arch Linux system; the released version does not build correctly), the output is as expected:

```
Chez Scheme Version 9.5.1
Copyright 1984-2017 Cisco Systems, Inc.

> (load "testit.scm")
#<thread 1>
waiting
hello from the thread
ok
we're done
>
```

I then compile as follows:

```
> (generate-wpo-files #t)
> (compile-file "testit.scm")
compiling testit.scm with output to testit.so
> (compile-whole-program "testit.wpo" "testit.so")
()
> (make-boot-file "testit.boot" '("petite") "testit.so")
>
```

If I load the testit.so produced by this into scheme, again it works correctly, as it did when I loaded the source file.

But after creating the link
```
dca@igor:/tmp$ ln -s /usr/local/bin/petite testit
```
and then 
```
[root@franz tmp]# cp testit.boot /usr/local/lib/csv9.5.1/ta6le/
```
running the program
```
dca@igor:/tmp$ ./testit
#<thread 1>
waiting
```
hangs after printing 'waiting', as shown above. top -H shows both threads suspended.

I ran into this problem while trying to use Chez to build a report generator for a personal finance system I've written. This simple example was derived from that code.

**Comment by donaldcallen** [comment]
On Fri, 18 Jan 2019 at 02:24, R. Kent Dybvig <notifications@github.com>
wrote:

> Generally speaking, it's not a good idea to run a program directly from a
> boot file but instead to have the boot file set the parameter scheme-start
> <http://cisco.github.io/ChezScheme/csug9.5/system.html#./system:s162> to
> call entry point for your program. This is because the system is not fully
> initialized until after the boot files have been loaded. In this case, I
> suspect what's happening is that the child thread is waiting for a garbage
> collection while the main thread is refusing to do one. That is, interrupts
> are disabled in the main thread (which they are by default until after the
> boot files have been loaded) but not in the forked thread (since
> fork-thread initializes the disable count to 0), so the forked thread will
> see that a collection is needed (which it surely is with the amount of
> allocation that occurs at boot time) and suspend itself, while the main
> thread will just keep running, or in this case, hang waiting for a
> condition signal that can never arrive.
>

Thank you for the quick response. I just did as you suggested -- set
scheme-start to invoke 'main' -- and that does work.

May I suggest a small addition to the "*Building and Running the
Application" *section of the User Manual that explains that the use of
scheme-start to invoke programs is not optional when using boot files (yes,
it's implicit in the current text, especially with the hindsight provided
by reading your message, but I think it ought to be explicit, with at least
the first sentence of what you told me above included) and also gives an
example of building a boot file (it's currently not clear where the setting
of scheme-start belongs; my first interpretation of the text was to load
the whole-program .so file, set the scheme-start parameter and then call
make-boot-file, which is completely wrong; I think a little example, which
would include showing that the setting of scheme-start needs to be a
side-effect of loading the prepared boot file, would be very helpful).

I would also like to say that my experience with Chez, other than my
boot-file hiccups, has been very positive. The system is rock solid,
generally well-documented and the generated code is very fast. It seems
that ~30 years of hard work have paid off :-)

Thanks again for your help.

/Don Allen

**Comment by dybvig** [comment]
Thanks for the suggestion, which I have taken.
