### ISSUE TITLE
foreign-callable fails in boot file

### ISSUE THREAD

**Issue by donaldcallen** [cisco/ChezScheme#392]
If I compile this file

```
(top-level-program
  (import (chezscheme))

  (define (main)
    (let ([code (foreign-callable (lambda ()
                                    (display "Hello world\n")
                                    ) () void)])
      (display "back from foreign-callable\n")
      (lock-object code)
      (foreign-callable-entry-point code))

    (exit 0)
    )
  (scheme-start
    (lambda ()
      (main)))
  )
```
like so

```
(begin
  (generate-wpo-files #t)
  (compile-file "testit.scm"))
```
and then create a boot file
```
(begin
  (compile-whole-program "testit.wpo" "testit.so")
  (make-boot-file "testit.boot" '("petite") "testit.so")
  )
```
and run the boot file, I get 
```
dca@dido:/tmp$ scheme -b testit.boot
Petite Chez Scheme Version 9.5.1
Copyright 1984-2017 Cisco Systems, Inc.

Exception: invalid memory reference.  Some debugging context lost
```
But, if I replace the setting of scheme-start with a call to main, compile and load the .so, it works:

```
dca@dido:/tmp$ scheme testit.so
Chez Scheme Version 9.5.1
Copyright 1984-2017 Cisco Systems, Inc.

back from foreign-callable
dca@dido:/tmp$
```

I suspect this has something to do with the code in the boot file being loaded into "static" memory, as discussed in Section 2.8 of the User Guide. Regardless of whether my guess is right, I am trying to build an application that involves callbacks (from gtk3) and calling to Scheme from C is essential. I would also like to use the packaging, efficiency and invocation advantages of boot files. This does not appear to be possible, unless there is a workaround for this problem, or I have done something incorrect. I would appreciate some guidance. Thank you.

**Comment by dybvig** [comment]
Just putting this into testit.scm fails:

```
(scheme-start
  (lambda ()
    (foreign-callable void () void)))
```

so it's something about evaluating a `foreign-callable` form at boot time.

**Comment by dybvig** [comment]
You suspicion that this is connected with static memory is correct.  When any code object is relocated into the static generation, its relocation table is dropped, since it won't ever need to be relocated again.  Each time a foreign-callable form is evaluated, however, a copy of the original code object is created with a pointer to the Scheme procedure to be invoked embedded in it.  The relocation table is needed both to find the proper location for the embedded pointer and because the freshly allocated code object might be relocated by the collector.  Since the static code object in your example is missing its relocation table, the code that creates the copy of the foreign-callable code object crashes.

Solving this probably involves setting a flag on each foreign-callable code object to say its relocation table should not be dropped.  In the meantime, a workaround is to arrange for the foreign-callable form to be evaluated at boot time (before the relocation table has been dropped), not when `(scheme-start)` is invoked.   For example, the following variation of your example doesn't crash:

```
(top-level-program
  (import (chezscheme))

  (define code (foreign-callable (lambda ()
                                   (display "Hello world\n")
                                   ) () void))

  (define (main)
    (display "back from foreign-callable\n")
    (lock-object code)
    (foreign-callable-entry-point code)

    (exit 0)
    )
  (scheme-start
    (lambda ()
      (main)))
  )
```

**Comment by donaldcallen** [comment]
On Wed, 6 Feb 2019 at 21:03, R. Kent Dybvig <notifications@github.com>
wrote:

> You suspicion that this is connected with static memory is correct. When
> any code object is relocated into the static generation, its relocation
> table is dropped, since it won't ever need to be relocated again. Each time
> a foreign-callable form is evaluated, however, a copy of the original code
> object is created with a pointer to the Scheme procedure to be invoked
> embedded in it. The relocation table is needed both to find the proper
> location for the embedded pointer and because the freshly allocated code
> object might be relocated by the collector. Since the static code object in
> your example is missing its relocation table, the code that creates the
> copy of the foreign-callable code object crashes.
>
Thanks for figuring this out so quickly. Rather than using the workaround
below, which would involve some re-arrangement of my code, because the
callbacks I am writing reference things defined in main as free variables,
I can just temporarily not use a boot file and instead test it by loading
the application .so file into petite and call main instead of setting
scheme-start. This will allow me to continue development. I can switch back
to use of the boot file when your fix becomes available.

/Don

**Comment by dybvig** [comment]
This should be fixed by [this commit](https://github.com/cisco/ChezScheme/commit/71d3abba684e04b134720ea1bd9a8c847c38ac5f).

**Comment by donaldcallen** [comment]
On Thu, 7 Feb 2019 at 01:28, R. Kent Dybvig <notifications@github.com>
wrote:

> This should be fixed by this commit
> <https://github.com/cisco/ChezScheme/commit/71d3abba684e04b134720ea1bd9a8c847c38ac5f>
> .
>
Wow, that was fast! I have an appointment this first thing this morning,
but I should be able to test this later in the morning. I will let you know
how things go.

**Comment by donaldcallen** [comment]
On Thu, 7 Feb 2019 at 07:46, Donald Allen <donaldcallen@gmail.com> wrote:

>
>
> On Thu, 7 Feb 2019 at 01:28, R. Kent Dybvig <notifications@github.com>
> wrote:
>
>> This should be fixed by this commit
>> <https://github.com/cisco/ChezScheme/commit/71d3abba684e04b134720ea1bd9a8c847c38ac5f>
>> .
>>
> Wow, that was fast! I have an appointment this first thing this morning,
> but I should be able to test this later in the morning. I will let you know
> how things go.
>

I've tested it with the code I've written thus far, with just one callback.
This is the code that previously failed, which led to my opening this
issue. That code now works correctly, with the latest github version of
Chez.

Thanks again for the quick turn around on this.

/Don

**Comment by amirouche** [comment]
@donaldcallen Maybe close the issue if it finished?

**Comment by donaldcallen** [comment]
Done!
