### ISSUE TITLE
Threads blocked in Emacs REPL

### ISSUE THREAD

**Issue by tommaisey** [cisco/ChezScheme#394]
The following code works as expected in a terminal REPL, but not from an Emacs REPL:

```
(fork-thread
 (lambda ()
  (let loop ()
    (sleep (make-time 'time-duration 0 1))
    (display "Hello")
    (flush-output-port)
    (loop))))
```

I've tried `run-scheme`, `comint-run`, `shell`, and `ansi-term`. Strangely, if I evaluate some stuff at the Emacs REPL, the thread seems to run briefly, then stops again.

This isn't a problem with printing or output ports. My actual code pushes OSC via UDP to SuperCollider, so the side-effect is audible - the behaviour is the same.

I have been looking at similar issues, such as [this one](https://github.com/cisco/ChezScheme/issues/127), where @ovenpasta mentions this exact problem, but I don't really understand the conclusions. Apologies if this is obvious!

**Comment by burgerrg** [comment]
If you use scheme --eedisable, you should see the same blocking behavior at a terminal REPL.

I think the problem is caused by the REPL's blocking read to stdin holding the tc-mutex, although I'm not yet sure why that happens. Any other thread that needs this mutex (and it's used for lots of operations) would have to wait for the read to complete.

**Comment by tommaisey** [comment]
Thanks for the quick reply! Yes I do see the same behaviour in that case.

I suppose enabling the expression editor is probably a pretty bad idea in the Emacs environment (if it's even possible). It's a shame, as this is the only thing holding me back from a very nice live-coding music environment. I don't suppose there are any other workarounds you can think of?

**Comment by burgerrg** [comment]
I'm looking into the root cause of the problem.

In the meantime, you could try [Swish](https://github.com/becls/swish), an extension of the single-threaded Chez Scheme that performs asynchronous I/O. Swish doesn't support UDP, so you'd have to code it.

**Comment by tommaisey** [comment]
Wonderful! I'll give Swish a try. I put together the UDP myself anyway with modifcations [this socket implementation](https://github.com/theschemer/socket). I can't thank you enough for your response, I've been stuck on this for a few days.

**Comment by burgerrg** [comment]
Here's a work-around for Chez Scheme:
```
(define (fix-stdin)
  (let ([stdin (transcoded-port (standard-input-port)
                 (make-transcoder (utf-8-codec)))])
    (current-input-port stdin)
    (console-input-port stdin)))

(fix-stdin)
(fork-thread
 (lambda ()
   (let loop ()
     (sleep (make-time 'time-duration 0 1))
     (display "Hello")
     (flush-output-port)
     (loop))))
```

**Comment by burgerrg** [comment]
Chez Scheme sets the console input and output ports to be the same input/output port. The port handler (see s/io.ss) holds the tc-mutex around blocking calls. As a result, you must create a separate port if you want to do blocking reads without holding the tc-mutex.

**Comment by burgerrg** [comment]
Section 15.6 of the [user guide](https://scheme.com/csug8/threads.html#./threads:h6) explains this:

> The initial console and current input and output ports are thread-safe, as are transcript ports, so it is safe for multiple threads to print error and/or debugging messages to the console. The output may be interleaved, even within the same line, but the port will not become corrupted. Thread safety for these ports is accomplished at the high cost of acquiring a mutex for each I/O operation.

@dybvig, perhaps the guide should also say that the same mutex is used for other system operations. As a result, if you're doing a blocking read on the initial console input port, beware that operations on other threads that require this mutex will block.

**Comment by tommaisey** [comment]
> Here's a work-around for Chez Scheme:

It works, thank you so much! I did read that line while investigating the issue, but I didn't realise it applied here.

I'll still take a look at Swish, though I'm still downloading mactex (3.2GB!).

**Comment by tommaisey** [comment]
@burgerrg You enabled me to get going and I'm making terrific progress on my music system, thanks! I'm running into a problem now that I believe is related. If anything goes wrong on my background thread, it stops altogether, and doesn't print any error messages. I'd like it to print an error and continue gracefully, by simply resetting the thunk that it's performing regularly. I tried this:

```
(define (my-thread-thunk)
  (with-exception-handler
      (lambda (x)
	(display x)
	(newline)
	(flush-output-port)
	(define-top-level-value 'p1 (lambda () (void))))
    p1)
```

Where `my-thread-thunk` is the thunk passed to `fork-thread` and `p1` is a thunk that does my work. But no dice - the thread just stops as before with no printout if `p1` raises an exception.

**Comment by burgerrg** [comment]
The exception handler needs to invoke a continuation so that Chez Scheme doesn't subsequently raise a non-continuable error.

```
(fork-thread
 (lambda ()
   (call/cc
    (lambda (done)
      (with-exception-handler
       (lambda (e)
         (pretty-print e)
         (flush-output-port)
         (done (void)))
       (lambda ()
         (let loop ()
           (sleep (make-time 'time-duration 0 1))
           (display "Hello")
           (flush-output-port)
           (error #f "boom!")
           (loop))))))))
```

Using the `guard` form is more succinct:
```
(fork-thread
 (lambda ()
   (guard (x [else (display-condition x) (newline) (flush-output-port)])
     (let loop ()
       (sleep (make-time 'time-duration 0 1))
       (display "Hello")
       (flush-output-port)
       (error #f "boom!")
       (loop)))))
```

**Comment by tommaisey** [comment]
The thread now seems to behave nicely, although I don't see an error printout. Actually, a simple call to `display` or `write` in the guard handler doesn't seem to work either. I'm sure I can figure that out though. 

This prevents me needing to restart Chez when something goes wrong, which is a huge improvement. Thanks so much!

**Comment by dybvig** [comment]
Try displaying to `(console-output-port)` rather than the default `(current-output-port)`.  It could be that the current output port has been redirected at the point where the error occurs.  You might also want to use `display-condition` rather than display for the condition.

**Comment by tommaisey** [comment]
That didn't seem to be it.

**Comment by tommaisey** [comment]
Actually, I've noticed that when the code is invoked directly from the Geiser REPL, I _do_ get error printouts. When it's invoked using Geiser's `geiser-eval-last-sexp` or similar inside a buffer, I don't see them. 

I guess this is an issue with Geiser, and therefore consider this issue closed.
