### ISSUE TITLE
Cannot find compatible scheme.boot in search path

### ISSUE THREAD

**Issue by nulldatamap** [cisco/ChezScheme#395]
Hello,

After the commit 7be1d190, a fresh build of Chez Scheme fails with the following error:
```
cannot find compatible scheme.boot in search path
  "${InstallPrefix}/lib/csv%v/%m"
```

Here's the replication process for `a6le`:
```bash
git clone https://github.com/cisco/ChezScheme
cd ChezScheme
./configure
make install
cd ..
echo '(printf "Works\n")' | scheme
```

**Comment by burgerrg** [comment]
It looks like the changes to configure broke the way $w/c/config.h generates DEFAULT_HEAP_PATH on non-Windows systems. In particular, $installlib contains the literal ${InstallPrefix} instead of resolving it.

**Comment by dybvig** [comment]
Thanks for mentioning this...I'll look into it and push a fix shortly.

**Comment by dybvig** [comment]
This should be fixed by [this commit](https://github.com/cisco/ChezScheme/commit/21c8b40bbe4431795824e48042112820872a1fe5).

**Comment by nulldatamap** [comment]
That fixed it, thanks.
And thank you for the quick response.
