### ISSUE TITLE
Executable should not be called 'scheme'

### ISSUE THREAD

**Issue by johnwcowan** [cisco/ChezScheme#4]
Anyone who has MIT Scheme installed expects 'scheme' to invoke that executable.  Chez should respect this historical precedent by installing under a different name.  This affects the man page as well as the executable.

**Comment by ecraven** [comment]
I've dealt with this in the ArchLinux PKGBUILD by renaming it to chez-scheme. The following files are affected:
- /usr/bin/scheme
- /usr/share/man/man1/scheme.1.gz
- /usr/lib/csv9.4/ta6le/scheme.boot
- maybe also /usr/lib/csv9.4/ta6le/scheme.h
(csv9.4 and ta6le depend on version and machine type).

**Comment by troydm** [comment]
why not just call it chez?

**Comment by dybvig** [comment]
Chez Scheme's executable has been called "scheme" since before the 1.0 release in 1985, and my fingers could not survive the change.  It's straightforward to change the name on install by passing, e.g., `InstallSchemeName=chez-scheme` on the `make install` command line.

**Comment by Earnestly** [comment]
And what of `petite`?

**Comment by jltaylor-us** [comment]
Why would anyone want to run MIT scheme when they could run Chez scheme instead? :trollface: 

On a more serious note, historical precedent demands that `scheme` be the executable name, much like `cc` is the C compiler name regardless of vendor, and `javac` is the java compiler name, whether it came from Oracle or OpenJDK.

**Comment by Earnestly** [comment]
Then it is up to downstream to provide necessary symlinks, as is done with `cc`, `as`, etc.

**Comment by johnwcowan** [comment]
@dybvig: Thanks for the install switch.  I'll do that next time.

@jltaylor-us: As someone who has 50 Schemes installed on his system (for good reason), I would go nuts if they were all named `scheme`.  As for precedent, `cc` is a symlink on all the systems I have access to right now; it points to `gcc`, but could be changed to point to `clang` or for that matter `lcc` or `tcc` if I had them installed.  The whole Debian `/etc/alternatives` system (now available in Fedora and elsewhere as well) depends on each alternative executable having a unique name.  In addition, the AOT Java compiler is named `gjc`, not `javac`; they don't do the same thing, but then different Schemes are not exactly plug-replaceable either.

**Comment by Earnestly** [comment]
That leaves `scheme-script` then, which is unchanged with `InstallSchemeName`.

**Comment by jltaylor-us** [comment]
@johnwcowan:  I'm not especially familiar with the `/etc/alternatives` system, but it seems obvious from a quick read of the `update-alternatives` man page that each alternative for any given command has to have a unique _path_, not filename.  Maybe all your problems could be solved pretty simply if #6 / #16 were fixed and you could then set up symlinks into the install directory using whatever names you like?

**Comment by johnwcowan** [comment]
@jltaylor-us: Yes, in principle I could install every Scheme into a separate install path, and then flipflop either /etc/alternatives or my own symlinks like crazy.  The fact is, I don't have to in any other case, and I shouldn't have to here, and given the install option, I don't have to.  I also removed the MIT Scheme symlink, and "scheme" on my system now runs a script that shows concisely the startup invocations for all my Schemes.

@Earnestly: I certainly hope nobody depends on `scheme-script`, which is only provided for compatibility with non-normative Appendix D of R6RS, written at a time when R6RS was expected to have a much broader reach, and compatibility between R6RS systems was expected to be closer than it actually is.

**Comment by dybvig** [comment]
This discussion seems to have run its course, and the resolution to use the `make install` option to select a different name seems to be acceptable, so I'm marking the issue closed.
