### ISSUE TITLE
Build failed on Win10 

### ISSUE THREAD

**Issue by mirxy** [cisco/ChezScheme#415]
**environment**
- Win10 64-bit
- Bash in git-bash
- VS2017

**Problem**
My VS was not installed in the default path, so I change the **"Applications"** value in **vs.bat** to my path.

$ make workareas
cd ..; ./configure -m=a6nt; D:/Develop/MinGW/bin/make -C a6nt
make[1]: Entering directory 'G:/csv9.5.2/a6nt'
(cd c && D:/Develop/MinGW/bin/make)
cmd.exe /c make.bat
The specified configuration type is missing.  The tools for the
configuration might not be installed.
'nmake' is not recognized as an internal or external command,
operable program or batch file.
make[2]: *** [Makefile:28: ../bin/a6nt/scheme] Error 1
make[1]: *** [Makefile:20: build] Error 2
make[1]: Leaving directory 'G:/csv9.5.2/a6nt'
make: *** [Makefile:24: workareas] Error 2

27 ${Scheme}: make.bat
**28** 	cmd.exe /c make.bat
29 	cp ../bin/$m/scheme.exe ../bin/$m/petite.exe
30	cp ../bin/$m/scheme.pdb ../bin/$m/petite.pdb

**make.bat**
@echo off
set MAKEFLAGS=
vs.bat amd64 && nmake /f Makefile.a6nt /nologo %*

I think something doesn't work correctly  in the last line in **make.bat** file.

Any help will be appreciated!

**Comment by burgerrg** [comment]
It looks like git-bash installs the MinGW environment, which is not supported for building Chez Scheme. There are two Unix-like environments supported: Cygwin and Windows Subsystem for Linux. See BUILDING for details.

**Comment by melted** [comment]
I always build ChezScheme in MSYS2 (another mingw variant) and it works pretty well out of the box. So I don't think it has to do with mingw.
And in fact, I can recreate this with a custom path to Visual Studio. I got exactly the same error if I used quotes around the BATDIR path in vs.bat. They will interact badly with the quotes in the last line of vs.bat.

**Comment by burgerrg** [comment]
The SET statement in Windows batch files handles spaces, so try removing the double-quotes to your modification to the set Applications line and see if that resolves it.

**Comment by mirxy** [comment]
How stupid I was. 
**The double-quotes account for the failure.**
I forget to show how I had modified the SET statement.
Thank you all!

Here comes another problem.
When I executed the command `make` ,which is the last setup before making a window installer, the process got stuck. And the prompt became cmd's style. 
But if I execute `make` in cmd, it will succeed.
I don't know the reason.

**$ make**
cmd.exe /c candle.bat -nologo -dVersion=9.5.2 -ext WixUIExtension -ext WixBalExtension bundle.wxs -out x86/bundle.wixobj
bundle.wxs
cmd.exe /c candle.bat -nologo -dVersion=9.5.2 -ext WixUIExtension -ext WixBalExtension product.wxs -out x86/product.wixobj
product.wxs
cmd.exe /c candle.bat -nologo -dVersion=9.5.2 -ext WixUIExtension -ext WixBalExtension examples.wxs -out x86/examples.wixobj
examples.wxs
cmd.exe /c candle.bat -nologo -dVersion=9.5.2 -ext WixUIExtension -ext WixBalExtension i3nt.wxs -out x86/i3nt.wixobj
i3nt.wxs
cmd.exe /c candle.bat -nologo -dVersion=9.5.2 -ext WixUIExtension -ext WixBalExtension ti3nt.wxs -out x86/ti3nt.wixobj
ti3nt.wxs
cmd.exe /c locate-vcredist.bat
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.9
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'
Built vcredist.wxs
cmd.exe /c candle.bat -nologo -dVersion=9.5.2 -ext WixUIExtension -ext WixBalExtension vcredist.wxs -out x86/vcredist.wixobj
vcredist.wxs
cmd.exe /c candle.bat -nologo -dVersion=9.5.2 -ext WixUIExtension -ext WixBalExtension ui.wxs -out x86/ui.wixobj
ui.wxs
cmd.exe /c light.bat -nologo -ext WixUIExtension -ext WixBalExtension x86/product.wixobj x86/examples.wixobj x86/i3nt.wixobj x86/ti3nt.wixobj x86/vcredist.wixobj x86/ui.wixobj -sice:ICE64 -sice:ICE03 -sice:ICE82 -sice:ICE61 -out "ChezScheme32.msi"
Microsoft Windows [Version 10.0.17763.379]
(c) 2018 Microsoft Corporation. All rights reserved.

**G:\csv9.5.2\wininstall>**

BTW, it would be better if Windows binary installer is supplied.

**Comment by burgerrg** [comment]
I don't know why the build ended with a CMD prompt. Perhaps the light.bat it's finding isn't the one from WiX?

The Chez Scheme releases tab now includes a Windows install.

**Comment by mirxy** [comment]
Anyway, I succeed to build the windows installer .
Thank you again.
