### ISSUE TITLE
typo in TSPL4 (and R6RS)

### ISSUE THREAD

**Issue by ocyzl** [cisco/ChezScheme#417]
At least, I think it's a typo.  If not, can someone explain what it means?

https://www.scheme.com/tspl4/syntax.html#./syntax:h2 says, in the next-to-last bullet:
> <tt><i>P</i></tt> is of the form <tt>#(<i>P<sub>1</sub></i>&nbsp;...&nbsp; <i>P<sub>k</sub></i>&nbsp;<i>P<sub>e</sub></i>&nbsp;<i>ellipsis</i>&nbsp;<i>P<sub><i>m</i>+1</sub></i>&nbsp;...&nbsp;<i>P<sub>n</sub></i>)</tt>, where <tt><i>ellipsis</i></tt> is the identifier <tt>...</tt> and <tt><i>F</i></tt> is a vector of <i>n</i> or more elements whose first <i>k</i> elements match <tt><i>P<sub>1</sub></i></tt> through <tt><i>P<sub>k</sub></i></tt>, whose next <i>m</i> - <i>k</i> elements each match <tt><i>P<sub>e</sub></i></tt>, and whose remaining <i>n</i> - <i>m</i> elements match <tt><i>P<sub><i>m</i>+1</sub></i></tt> through <tt><i>P<sub>n</sub></i></tt>

Shouldn't "_n_ or more elements" be just "_n_ elements" instead?

(Section 11.19 of R6RS says the same thing.)

**Comment by burgerrg** [comment]
Would this be clearer?

P is of the form #(P1 ...  Pk Pe ellipsis S1 ... Sm), where ellipsis is the identifier ... and F is a vector of n elements with n >= k+m whose first k elements match P1 through Pk, whose next n-m elements each match Pe, and whose remaining m elements match S1 through Sm.

**Comment by ocyzl** [comment]
Hmm.  That doesn't seem right either.  If the first _k_ elements match _P<sub>1</sub>_ through _P<sub>k</sub>_, and the last _m_ match _S<sub>1</sub>_ through _S<sub>m</sub>_, and there are _n_ altogether, the number of elements left to match _P<sub>e_ is _n_ - _k_ - _m_, not _n_ - _m_.

**Comment by burgerrg** [comment]
Thanks! Second try:

P is of the form #(P1 ... Pk Pe ellipsis S1 ... Sm), where ellipsis is the identifier ... and F is a vector of n elements with n >= k+m whose first k elements match P1 through Pk, whose next n-k-m elements each match Pe, and whose remaining m elements match S1 through Sm.

**Comment by dybvig** [comment]
@ocyzl is correct that "_n or_ more elements" should read "_n_ elements".  @burgerrg's version is probably clearer, but I'm going to go with the more minimal change.  Thanks!

**Comment by dybvig** [comment]
I have updated the [online version of TSPL](https://scheme.com/tspl4/syntax.html#./syntax:s14) and the [errata](https://scheme.com/tspl4-errata.html).
