### ISSUE TITLE
Is there any high quality 3rd libraries for Chez?

### ISSUE THREAD

**Issue by lamcee** [cisco/ChezScheme#42]
I used to use Python because it's more convenient in finding some libraries, such as json library, networking library.

Besides the [stdlib](http://www.r6rs.org/corrected/html/r6rs-lib/r6rs-lib.html), I was wondering if there are some high quality 3rd libraries for Chez Scheme? 

I personally still prefer Chez Scheme, but missing libraries is a real problem.

**Comment by NalaGinrut** [comment]
Chez has great FFI support, IMO it's not so hard to write bindings of other C libs.

**Comment by dybvig** [comment]
While the tools exist to create new libraries, including, as @NalaGinrut points out, those that involve leveraging libraries written in C and other languages, a large set of existing high-quality libraries and a standard way to locate them would make Chez Scheme much more useful.

**Comment by obriencj** [comment]
A standard or recommended way to define and version a project (analogous to setuptools or distutils, since this started with a Python comparison) as well as a way to group and discover modules (PyPI) would certainly be a boon.

**Comment by soegaard** [comment]
Have you tried this?
    https://github.com/dharmatech/chez-gl

(Note: I haven't myself)

**Comment by dharmatech** [comment]
@soegaard 

That OpenGL library is used by this 2D physics library:

https://github.com/dharmatech/box2d-lite

It seems to work well on the latest Chez on Linux.

**Comment by obriencj** [comment]
I thought the original post meant "3rd party" rather than "3D" but maybe I'm wrong?

**Comment by NalaGinrut** [comment]
oh, I thought "3D" too, maybe I need new glasses. ;-)

**Comment by evilbinary** [comment]
https://github.com/evilbinary/scheme-lib  chez lib

**Comment by Samired** [comment]
https://github.com/ovenpasta/thunderchez

**Comment by guenchi** [comment]
we start a project to provide a standard Chez Scheme library:

A Package Manager for Chez Scheme, it can easily  download, initial the Scheme library, and automatelly compile c library.

We are now starting to refine some of the commonly used scheme libraries, including wrapping some c libraries, and we urge everyone to submit your scheme library.

so the GitHub of project :https://github.com/guenchi/raven

website: http://ravensc.com

Packages list: http://ravensc.com/list

**Comment by evilbinary** [comment]
@guenchi  You should add scheme-lib to the packages,it's a eazy lib to use c and other lib that provide opengl mysql and so many libraries.
