### ISSUE TITLE
Request: add prebuilt boot file for ARM

### ISSUE THREAD

**Issue by zaoqi** [cisco/ChezScheme#420]

**Comment by evilbinary** [comment]
ha?

**Comment by zaoqi** [comment]
@evilbinary ??

**Comment by zaoqi** [comment]
@evilbinary 在https://github.com/cisco/ChezScheme/tree/master/boot增加arm的...

**Comment by evilbinary** [comment]
@zaoqi Just compile youself.

**Comment by zaoqi** [comment]
@evilbinary

我無意間看到了https://github.com/racket/racket/commit/e337c65204402ef4faf09f6a848d2d873d0e63a7
現在不需要交叉編譯了。

**Comment by mflatt** [comment]
Addressed by bootstrapping via pb.
