### ISSUE TITLE
make-record-type-descriptor appears twice in the index

### ISSUE THREAD

**Issue by burgerrg** [cisco/ChezScheme#426]
See https://cisco.github.io/ChezScheme/csug9.5/csug_1.html

**Comment by burgerrg** [comment]
Fixed in 23833c7d0194248143af425dd22e34a760e81505.

**Comment by gwatt** [comment]
I think it's because one of those references the appearance of `make-record-type-descriptor` in the preamble for section 9.2 and the other entry references the procdeure's description.
