### ISSUE TITLE
Where the keyword 'lambda' defined in Chez Scheme?

### ISSUE THREAD

**Issue by Saigut** [cisco/ChezScheme#427]
Hi, I am sorry asking such question as an issue. Since it seems that no other place active enough to disscuss Chez Scheme so I ask at here. 

Here is my question:
I try to find Chez Scheme how to compile, and find that many symbols are defined in `prim*` files. But I failed to find where some keywords like `lambda` are defined. 

There is no `lambda` symbol appear in C code, so I think it should be defined scheme code, but I still can't find the definition of `lambda`.

I find this in `s/primdata.ss`:
```
(define-symbol-flags*
...
(lambda [flags ieee r5rs])
..
```
And this in `s/read.ss`:
```
(define-syntax xlambda
.....
```

But neither these two like the definition of `lambda`.

So where can I find the definition of keyword `lambda`?

Any help would be appreciated.
Thanks.

**Comment by burgerrg** [comment]
`lambda` is one of the core forms of the Scheme programming language. You can find its definition in the macro expander at line 5934 of s/syntax.ss. It expands into a `case-lambda` form that is subsequently processed by the compiler.

**Comment by Saigut** [comment]
Many thanks!
