### ISSUE TITLE
Deadlock with threads

### ISSUE THREAD

**Issue by ecraven** [cisco/ChezScheme#440]
Hello!
I've tried to work out a very basic futures library (based on Gwatt's work, thanks again!). However, I keep running into deadlocks that I do not understand.
(This might well be a problem with my understanding of threads :-/)

`%make-future` creates and grabs a lock, then starts a thread, which does its work, then releases the lock.
`sync` spins on that same lock, and after acquiring it, it accesses some data.

However, this regularly deadlocks (100% CPU usage) when run as, for example:
````
(map/parallel (lambda (x) (+ x 1)) (iota 100))
````
Sometimes (but seldom) `(sync (spawn 3))` also hangs.

Running it on ta6le (with `--eedisable`). Is this some sort of bug in Chez Scheme, or is my code (see attachment) just wrong?
[future.txt](https://github.com/cisco/ChezScheme/files/3328776/future.txt)

**Comment by yjqww6** [comment]
I don't think `ftype-spin-lock!` should be used in such a case. The work threads may be suspended for a garbage collection, but the `ftype-spin-lock!` cannot be interrupted and the main thread would not be suspended. So the garbage collector would not be run, the work threads would not get resumed, and the main thread hangs.
Replacing it with a manual loop should help.

**Comment by ecraven** [comment]
Thank you very much, it seems this was the problem. Replacing the direct `ftype-spin-lock!` with `ftype-lock!` in a loop works fine. Thanks so much for helping with this!
