### ISSUE TITLE
Buggy record writer should not cause invalid memory reference

### ISSUE THREAD

**Issue by sunderroy** [cisco/ChezScheme#441]
I am using the `chezscheme` package on Linux Mint 19.1 (Tara) which is itself based on Ubuntu 18.04 (Bionic Beaver). The following code defines a record type and installs a buggy record writer procedure which when invoked causes an invalid memory reference: 

```
> (let ()
    (define-record Atom (id name))
    (record-writer (type-descriptor Atom)
      (lambda (r p w)
        ;; BUG: second argument to w should be p not w
        (w (Atom-name r) w)))
    (make-Atom 1 2))

Exception: invalid memory reference.  Some debugging context lost
Type (debug) to enter the debugger.
```
Ideally it should throw an exception instead of corrupting system state.

**Comment by dybvig** [comment]
Thanks for the bug report.  This has been fixed with commit 4671f22.
