### ISSUE TITLE
Problem with end of line when printing from a different thread.

### ISSUE THREAD

**Issue by MetaEntity** [cisco/ChezScheme#448]
End of line is not displayed correctly in the console (threaded build on windows x64) when printing from a different thread, see image below:

![image](https://user-images.githubusercontent.com/8394023/61571799-3aa09500-aad1-11e9-92ec-a950271bb370.png)

**Comment by burgerrg** [comment]
The default exception handler for the thread writes to the console-error-port, which unfortunately is not thread safe.

**Comment by MetaEntity** [comment]
Thank you for your reply. Is overriding the different console-error-port/console-output-port parameters by thread-safe versions while the editor is enabled envisaged? (perhaps not done for performance reasons?)

**Comment by burgerrg** [comment]
The console port handlers use the tc-mutex to perform thread-safe operations. In Windows, the expression editor makes a blocking call to ReadConsoleInput without holding tc-mutex. If it held the mutex, many other operations would block, and that's undesirable. I'd recommend disabling the expression editor and using an external editor such as Emacs to give you some of its features.
