### ISSUE TITLE
exception in fork-thread cause program erratic behavior

### ISSUE THREAD

**Issue by MetaEntity** [cisco/ChezScheme#449]
On threaded windows x64 chez scheme (built downloaded from https://cisco.github.io/ChezScheme) an exception in a thread thunk leads to high CPU usage, possibly program crash and even OS crash!

Sample reproduction code:

(let rec ([i 0])
  (when (< i 5)
    (fork-thread (lambda () (string-append 1 2))) ; raising exception on purpose
    (rec (+ i 1))))

**Comment by burgerrg** [comment]
The default exception handler for the forked threads is writing to console-output-port, which is not thread safe. Do the following instead:

<pre>(let rec ([i 0])
  (when (< i 5)
    (fork-thread
     (lambda ()
       (call/cc
        (lambda (k)
          (base-exception-handler (lambda (e) (k e)))
          (string-append 1 2)))))
    (rec (+ i 1))))</pre>

**Comment by burgerrg** [comment]
You won't see the output until you enter another expression at the repl.

**Comment by MetaEntity** [comment]
Thank you it was same reason as issue #448.
