### ISSUE TITLE
Is syntax-rules has  extra runtime overhead in this case with Chez Scheme

### ISSUE THREAD

**Issue by guenchi** [cisco/ChezScheme#450]
if we have this procedure:

```
(define move
  (case-lambda
    (()(ioctl #\A))
    ((n)(ioctl n #\A))))
```

in this case, what's the diffrent with:

```
(define-syntax move
  (syntax-rules ()
    ((_)(ioctl #\A))
    ((_ n)(ioctl n #\A)))) 
``` ?

What I would like to know is that in this case (without the "..." syntax), syntax-rules will expand to the equivalent of case-lambda compilation at compile time. In other words, my concern is whether syntax-rules has extra runtime overhead in this case?
If not, what is the meaning of case-lambda? (since it can be replaced by syntax-rules)

in other case:

(define-syntax move
  (syntax-rules ()
    ((_)(ioctl #\A))
    ((_ n)(ioctl n #\A))
    ((_ n ...)(ioctl n ... #\A)))) 

If syntax-rules has extra runtime overhead with "..." syntax in Chez Scheme?

Thx

**Comment by soegaard** [comment]
Den søn. 28. jul. 2019 kl. 21.25 skrev guenchi <notifications@github.com>:

> if we have this procedure:
>
> (define move
>   (case-lambda
>     (()(ioctl #\A))
>     ((n)(ioctl n #\A))))
>
> in this case, what's the diffrent with:
>
> (define-syntax move
>   (syntax-rules ()
>     ((_)(ioctl #\A))
>     ((_ n)(ioctl n #\A))))
> ``` ?
>
> What I would like to know is that in this case (without the "..." syntax), syntax-rules will
>
> expand to the equivalent of case-lambda compilation at compile time.
>
> No.

If you are using the macro definition of move above, then

    (move)  matches the first pattern (_) so the expansion is (ioctl #\A)

   (move 10) matches the second pattern (_ n) so it will expand into
(ioctl 10 #\A)

/Jens Axel

**Comment by guenchi** [comment]
> Den søn. 28. jul. 2019 kl. 21.25 skrev guenchi <notifications@github.com>:
> if we have this procedure: (define move (case-lambda (()(ioctl #\A)) ((n)(ioctl n #\A)))) in this case, what's the diffrent with: (define-syntax move (syntax-rules () ((_)(ioctl #\A)) ((_ n)(ioctl n #\A)))) ``` ? What I would like to know is that in this case (without the "..." syntax), syntax-rules will expand to the equivalent of case-lambda compilation at compile time. No.
> If you are using the macro definition of move above, then (move) matches the first pattern (_) so the expansion is (ioctl #\A) (move 10) matches the second pattern (_ n) so it will expand into (ioctl 10 #\A) /Jens Axel

my concern is whether syntax-rules has extra runtime overhead in this case 

if no, why case-lambda exist?

**Comment by amirouche** [comment]
> if no, why case-lambda exist?

`case-lambda` is first class you can pass it around to other function dynamically. `syntax-rules` return a syntax object and is processed at compile time.

**Comment by guenchi** [comment]
> > if no, why case-lambda exist?
> 
> `case-lambda` is first class you can pass it around to other function dynamically. `syntax-rules` return a syntax object and is processed at compile time.

Get it, thx !

So, syntax-rules  has not extra runtime overhead in this case?

**Comment by amirouche** [comment]
> So, syntax-rules has not extra runtime overhead in this case?

Macros in general have no extra runtime overhead.

**Comment by guenchi** [comment]
> > So, syntax-rules has not extra runtime overhead in this case?
> 
> Macros in general have no extra runtime overhead.



Is syntax-rules has extra runtime overhead with "..." syntax in Chez Scheme?

like:

(define-syntax move
  (syntax-rules ()
    ((_)(ioctl #\A))
    ((_ n)(ioctl n #\A))
    ((_ n ...)(ioctl n ... #\A)))) 

thx
