### ISSUE TITLE
\t is not expanded

### ISSUE THREAD

**Issue by SaitoAtsushi** [cisco/ChezScheme#454]
https://github.com/cisco/ChezScheme/blob/84a6a6ab36294c73dbdc617d19c42fada42c3a15/c/Mf-ta6nt#L58

In this case,  `\t` is not expanded as an escape sequence, output raw string.

**Comment by burgerrg** [comment]
Thanks, see if branch https://github.com/cisco/ChezScheme/tree/454 fixes it.

**Comment by SaitoAtsushi** [comment]
I build that branch on my environment and confirmed that the problem was solved.
Thank you.

**Comment by burgerrg** [comment]
Thank you, I merged the change to master.
