### ISSUE TITLE
UUID library issue

### ISSUE THREAD

**Issue by TheFausap** [cisco/ChezScheme#456]
Hello,
I'm trying to compile under Fedora 30, but it seems the uuid library shipped with Fedora is not compatible.

1) the include file is not under /usr/include/uuid directory, but in the /usr/include 
2) even if I change the location, it seems function uuid_generate doesn't exist, I have uuid_create.

I'm using uuid-1.6.2

regards,
Fausto

**Comment by burgerrg** [comment]
Try the [libuuid-devel](https://fedora.pkgs.org/30/fedora-x86_64/libuuid-devel-2.33.2-1.fc30.x86_64.rpm.html) package.

**Comment by TheFausap** [comment]
Yes I installed the devel package but I suppose they changed something
between versions.
Which version is known to be working with ChezScheme ?

**Comment by burgerrg** [comment]
The manifest file for https://fedora.pkgs.org/30/fedora-updates-x86_64/libuuid-devel-2.33.2-2.fc30.x86_64.rpm.html shows /usr/include/uuid/uuid.h as expected.

I don't have a Fedora 30 system, but my Ubuntu 18.04.3 system uses package uuid-dev/bionic-updates 2.31.1-0.4ubuntu3.3 amd64.

**Comment by gwatt** [comment]
It looks like there are competing uuid packages. One is just called "uuid" and appears to be the same as the one you have installed. The other is "libuuid" and is what Chez Scheme depends upon.

**Comment by TheFausap** [comment]
Thanks a lot for the clarification!
I will install the other one.

**Comment by TheFausap** [comment]
The build is ok, using the other library (libuuid). Thanks for the help!
