### ISSUE TITLE
Strange behaviour when manipulating foreign data of 'size_t'

### ISSUE THREAD

**Issue by macdavid313** [cisco/ChezScheme#457]
Hello,

I've encountered a very strange behaviour when I tried to allocate a C array of type `size_t`. My environments are:

1. Windows 10 (installed by the released installer)
2. Ubuntu 18.04 LTS (compiled by clang-8)
3. Chez Scheme 9.5.2 threaded

Please see the code below:

```scheme
> (define ptr (foreign-alloc (* 2 (foreign-sizeof 'size_t))))
> (foreign-set! 'size_t ptr 0 100)
> (foreign-ref 'size_t ptr 0)
100
```
Everything works just fine by now, but after I set the next value and try to access at offset 0 again, it drammatically becomes **INCONSISTENT**!

```scheme
> (foreign-set! 'size_t ptr 1 200)
> (foreign-ref 'size_t ptr 0)
51300 ;; Why it becomes an arbitrary number?
> (foreign-ref 'size_t ptr 1)
200
```

I have tried many times, but it never worked out. Did I write any part wrong? Can anyone reproduce this result or even had experience with it?

**Comment by burgerrg** [comment]
foreign-set! and foreign-ref use _byte_ offsets. Instead of 1, use (foreign-sizeof 'size_t).

**Comment by macdavid313** [comment]
@burgerrg thank u!

I thought `foreign-ref` and `foreign-ref` already take care of the offset calculation, since they both take the `type` parameter.
