### ISSUE TITLE
fatal error: 'uuid/uuid.h' file not found

### ISSUE THREAD

**Issue by cheery** [cisco/ChezScheme#458]
I resolved this by installing `uuid-dev` (ubuntu 16 LTS).

Installation went well afterwards. I had no other trouble during installing. :+1: 

If feasible, you may like to adjust `./configure` such that it catches if uuid library is missing. Otherwise this issue is yet another marker for ppl who are trying to install chez and have this kind of trouble.

**Comment by LiberalArtist** [comment]
It seems like it might be possible to remove the dependency on `libuuid` entirely. As long as you have a good source of randomness like `/dev/urandom`, generating Type 4 UUIDs is not especially hard. Does Chez Scheme support platforms where that is not available?

```scheme
#!r6rs

;; Generate Type 4 UUIDs in R6RS Scheme.
;; Ported from https://github.com/LiberalArtist/uuid/blob/master/main.rkt

(import (rnrs)
        (rnrs bytevectors)
        (rnrs arithmetic fixnums)
        (rnrs io ports))

(define (bytevector-update! bv i proc)
  (bytevector-u8-set! bv i (proc (bytevector-u8-ref bv i))))

(define (uuid)
  (define bv
    (let ([in (open-file-input-port "/dev/urandom")])
      (dynamic-wind
       (lambda () #t)
       (lambda () (get-bytevector-n in 16))
       (lambda () (close-port in)))))
  ;; version number
  (bytevector-update! bv 6 (lambda (x)
                             (fxior #b01000000
                                    (fxand #b00001111 x))))
  ;; variant
  (bytevector-update! bv 8 (lambda (x)
                             ;; but see https://www.rfc-editor.org/errata/eid5560
                             ;; (not a big issue for version 4 uuids)
                             (fxior #b10000000
                                    (fxand #b00111111 x))))
  bv)

;; Example:
(write (uuid))
```

**Comment by melted** [comment]
Windows for one certainly doesn't have /dev/urandom

**Comment by LiberalArtist** [comment]
Yes, but Chez Scheme already uses `UuidCreate` on Windows, and Windows also offers an interface to cryptographic-quality randomness, [`RtlGenRandom`](http://blogs.msdn.com/b/michael_howard/archive/2005/01/14/353379.aspx).

**Comment by burgerrg** [comment]
We mention that the header files and libraries for uuid are required in BUILDING, but it would be helpful if we could detect the absence in configure and give an informative error message. The same goes for nurses and Xwindows, I suppose. If you know how to do that in a simple, robust way, please submit a pull request.

libuuid-dev is convenient and readily available on Unix-like systems, so I'd prefer not to reproduce part of it for Chez Scheme using /dev/urandom.

**Comment by gwerbin** [comment]
I am trying to build this on Fedora 35, and I installed `uuid-devel`, but the header file was installed to `/usr/include/uuid.h` and not `/usr/include/uuid/uuid.h`, which causes compilation to fail, because `uuid/uuid.h` does not exist and cannot be found.

I see that `USE_NETBSD_UUID` changes the `#include <uuid/uuid.h>` to `#include <uuid.h>`, but it seems like a bad idea to force that setting, given that I am definitely not using NetBSD.

Is there an appropriate workaround, other than patching the source code?

**Comment by mflatt** [comment]
The default build mode no longer uses `uuid/uuid.h`.
