### ISSUE TITLE
Should set-port-output-buffer! set the output size to the length minus one?

### ISSUE THREAD

**Issue by burgerrg** [cisco/ChezScheme#459]
> The procedure set-port-output-buffer! sets the output buffer field of output-port to x, which must be a string for textual ports and a bytevector for binary ports. It also sets the output size to the length of the string or bytevector and the output index to 0.

For output ports, the size is the length of the string or bytevector minus one. Shouldn't the procedures that set the output-buffer subtract one from the length to give room for the last character/octet?

**Comment by dybvig** [comment]
While some of the handlers set the size to the length of the string or bytevector minus one to give them room to store a character or byte, this isn't the case for all handlers.  Some of the built-in handlers set the buffer to the empty string or bytevector and the size (redundantly) to zero, for example.  It also looks like the bytevector and string output port handlers don't take advantage of setting the size one less than the length and should be changed to set the size to the length.

So I think it's better for the size to be set to the length by default and let handlers override.  In any case, I don't know what user-defined handlers we might break by changing the behavior.

**Comment by burgerrg** [comment]
That sounds good, thank you!
