### ISSUE TITLE
Hey, Why this is not the same?

### ISSUE THREAD

**Issue by AiziChen** [cisco/ChezScheme#468]
in racket r5rs and chez scheme 9.5.2 on mac 10.14.6.
Is this an issue?
![Racket r5rs vs chez scheme 9.5.2](https://ae01.alicdn.com/kf/He0cfa360a83e4695b7d84c770c5c0c19i.jpg)

**Comment by olopierpa** [comment]
Il giorno 3 ottobre 2019, alle ore 10:27, 陈权业 <notifications@github.com> ha scritto:

>in racket r5rs and chez scheme 9.5.2 on mac 10.14.6.
>This is an issus?

The first expression is handled correctly by both implementations.

The second expression modifies a constant, so its result is undefined and any program evaluating it has no meaning. It could have returned 42 or have caused your dog to bark, and still the implementation would not be at fault. 

In an ideal world your second expression should have raised an error, but unfortunately very few actual implementations detect this mistake.

HTH

**Comment by AiziChen** [comment]
> Il giorno 3 ottobre 2019, alle ore 10:27, 陈权业 <notifications@github.com> ha scritto:
> in racket r5rs and chez scheme 9.5.2 on mac 10.14.6. This is an issus?
> The first expression is handled correctly by both implementations. The second expression modifies a constant, so its result is undefined and any program evaluating it has no meaning. It could have returned 42 or have caused your dog to bark, and still the implementation would not be at fault. In an ideal world your second expression should have raised an error, but unfortunately very few actual implementations detect this mistake. HTH

thank you so much!
