### ISSUE TITLE
Consider using a standard git workflow

### ISSUE THREAD

**Issue by michaellenaghan** [cisco/ChezScheme#47]
Currently all development is being done on the master branch. That model may or may not work for Chez, but there are other options—e.g., [gitflow](http://nvie.com/posts/a-successful-git-branching-model/).

In gitflow:

 * The develop branch is the trunk.

 * Features are prepared in feature branches and then merged into the develop branch.

 * Releases are prepared in release branches and then merged into the develop *and* master branches.

 * Releases are tagged in the master branch.

Feature branches are especially useful for big features that might otherwise disrupt ongoing development. Likewise, release branches prevent disruption of ongoing development while releases are alpha/beta tested.

Of course, this is just one option. It has the benefit of being documented (e.g., [here](http://nvie.com/posts/a-successful-git-branching-model/), [here](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow), [here](https://yakiloo.com/getting-started-git-flow/)) and being supported by tools (e.g., [here](https://github.com/nvie/gitflow), [here](https://blog.sourcetreeapp.com/2012/08/01/smart-branching-with-sourcetree-and-git-flow/), [here](https://gitflow.nl)). Whether or not this is the right option for Chez is up to the team; the main point, I think, is that this is probably a good time to think about it.

**Comment by distransient** [comment]
Having a "trunk" branch is far from a "standard" Git workflow because `master` **is** Git's "trunk". Don't shoehorn Subversion concepts onto Git where it isn't necessary.

**Comment by michaellenaghan** [comment]
I meant "standard" in the sense of "documented" and "supported"—i.e., well-known rather than ad-hoc. But my bigger point was that this is probably a good time to think about workflow. 

The rule of thumb I've always heard and used is that you should branch on change in policy. Unlike a continuously deployed website Chez is a versioned product, and from that perspective gitflow's branches make perfect sense. Well, to me. YMMV.

**Comment by dybvig** [comment]
I've taken a look at gitflow, and it does seem to be a good fit.  Still, I'd like to try maintaining a single branch for now and see what problems we run into before selecting an alternative.  Effectively, we already have feature branches in the form of forks; what's missing for now are development and release branches separate from the main branch.
