### ISSUE TITLE
Command line file load resolution errors

### ISSUE THREAD

**Issue by Letladi** [cisco/ChezScheme#470]
If you have the following example folder structure (with dependencies as indicated after the # symbols;
- parent
   - folder1
      - a.scm
      - b.scm # depends (loads) on a.scm with statement `(load "a.scm")`
   - folder2
     - c.scm # depends (loads) b.scm in folder1 with statement `(load "../folder1/b.scm")`

If you are in the `parent` folder and try to load `c.scm` with;
```(load "folder2/c.scm")```
You will get the error `Exception in load: failed for ../folder1/b.scm: no such file or directory`

If on the other hand you are in `folder2` and try to load `c.scm`, you will get the error; `Exception in load: failed for a.scm: no such file or directory`

**Comment by gwatt** [comment]
Chez Scheme's load is relative to the [`(source-directories)`](http://cisco.github.io/ChezScheme/csug9.5/system.html#./system:s94) parameter and not the from the current file being loaded.
In this case, all of your loads will need to be relative from the parent folder. `c.scm` loads `"folder1/b.scm"` and `b.scm` loads `"folder1/a.scm"`

**Comment by Letladi** [comment]
Oh, that is unexpected.
Thank you for the response 🙏🏾
