### ISSUE TITLE
Error with time-utc->date in Cygwin

### ISSUE THREAD

**Issue by gus-massa** [cisco/ChezScheme#474]
I got an error in this mat [date.ms#L624-L629](https://github.com/cisco/ChezScheme/blob/master/mats/date.ms#L624-L629). I got the error **only** when I run scheme.exe in Cygwin, not when I run it in a normal cmd terminal. Note that my timezone is Buenos Aires, Argentina (-3).

In the mat the first test is fine, the error is in the other three. In particular the second one can be reduced to

    (let* ([t (current-time)]
           [t2 (date->time-utc (time-utc->date t 0))])
      (- (time-second t) (time-second t2)))

This should be `0` but I get `1800 =  3 * 3600` in Cygwin because my timezone is -3 hours. 
(But I get `0` if I run the program from windows.)

**Comment by burgerrg** [comment]
Try `unset TZ` before running the mats. Cygwin's use of the TZ environment variable conflicts with Windows standard library usage.

**Comment by gus-massa** [comment]
Thanks! That fix my problem.

I think this should be fixed anyway if possible. I don't care too much about the results inside cygwin, but someone else may use chez scheme in a script inside cygwin in the future and get a subtle error.

**Comment by burgerrg** [comment]
The problem is an interaction bug with Cygwin, so Chez Scheme can't fix it. There is a note about this in BUILDING.Schemehttps://github.com/cisco/ChezScheme/blob/243cd029bb19ce555dac4012e6e20c5673143b64/BUILDING#L300-L302

**Comment by gus-massa** [comment]
OK, let's close this then.
