### ISSUE TITLE
Problems identifying a real number??

### ISSUE THREAD

**Issue by mayer-goldberg** [cisco/ChezScheme#475]
Is this behaviour a bug?

> (integer? 7.2e2)
#t
> (exact->inexact 7.2e3)
7200.0
> (integer? 7.245e2)
#f
> (integer? (exact->inexact 3e100))
#t
> (integer? (exact->inexact 3.23e100))
#t

And if this is not silly enough:
> (* 4 (atan 1) (expt 10.0 0))
3.141592653589793
> (integer? (* 4 (atan 1) (expt 10.0 0)))
#f
> (integer? (* 4 (atan 1) (expt 10.0 100)))
#t

This is unreal!

Thanks,

Mayer Goldberg

**Comment by gwatt** [comment]
integer? returns #t for exact integers and flonums where the decimal part is zero. http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-14.html#node_idx_448
 You're probably looking for a combination of exact? and integer?
