### ISSUE TITLE
Script reports "Exception: attempt to define out-of-context identifier name", but run as top program have no problem

### ISSUE THREAD

**Issue by Saigut** [cisco/ChezScheme#481]
I have such code:
`mycode.ss`:
```scheme
#!r6rs
(import (chezscheme))

(define-syntax def-new-type
  (lambda (x)
    (define (parser-body name body)
      (syntax-case body (bd)
        ((bd other ...)
          #'(define name "just-it-"))))
    (syntax-case x ()
      ((_ name body)
        (parser-body #'name #'body)))))

(def-new-type bbbbb (bd 111))
```
(My OS is Windows 10, and Chez Scheme version is 9.5.2.)
When I run my code as script, it will report error:
```
>scheme --script ./mycode.ss
output:
Exception: attempt to define out-of-context identifier name at line 9, char 21 of ./mycode.ss
```
But when I run my code as program, it reports no error:
```
>scheme --program ./mycode.ss
output:

```
So is my code syntax right?
And which behavior between `script` and `program` is right?

**Comment by gwatt** [comment]
I'm not sure why the behavior is different between script and program, but you probably need to insert `name` into the resulting syntax object from `parser-body` as follows:
```scheme
#`(define #,name "just-it")
```
That will insert the value of name into the syntax-object rather than the literal identifier `name`

**Comment by Saigut** [comment]
@gwatt You are right, that's my mistake. But I am still puzzled about that different behavior.

**Comment by dybvig** [comment]
When you use --program, the introduced definition of name creates a new local binding.  When you use --script, the introduced definition is a top-level definition, so it behaves like an assignment to an existing (possibly implicit) top-level binding.  Yet the visible binding for name is not only not global, it's not a run-time variable, hence the out-of-context error.  If you wrap the def-new-type use in a let, --script should swallow it just fine.

**Comment by Saigut** [comment]
@dybvig 
> When you use --script, the introduced definition is a top-level definition, so it behaves like an 
> assignment to an existing (possibly implicit) top-level binding. Yet the visible binding for name is 
> not only not global, it's not a run-time variable, hence the out-of-context error.

From my view, the `name` in `(parser-body name body)` only exists during expend-time, while the `name` in `#'(define name "just-it-"))))` only exists during run-time.  So they are in two different world, and are impossible be conflicting with each other.
So I guess --script do the wrong thing?

**Comment by gwatt** [comment]
The `name` in parser-body's argument list and the `name` in `#'(define name "just-it")` are the same. Identifiers inside of a syntax quote are resolved by pattern variables from syntax-case OR visible bindings at the call site of the syntax-quote OR finally introducing a fresh variable. Since `name` is visible from parser-body's argument list at the call site of `#'(define ...)` the syntax-quote will make the identifier `name` in the expansion be the `name` from the argument list.

**Comment by dybvig** [comment]
@Saigut, it's not a question of right or wrong, only what is.  We could have gone in the direction you suggest and had multiple namespaces, one for run-time code, another for compile-time code, another for the compile-time code's compile time code, etc.  We could have done as Common Lisp and some older Lisps did and have different namespaces for variables naming procedures and variable naming other values.  The namespaces for record-type names and module names could also be different from all the others.  We've consistently chosen instead to have a single namespace for everything.  It's a simpler model and leads to more readable code.

**Comment by Saigut** [comment]
Thanks for all your patient answers!
