### ISSUE TITLE
Possible bad reduction of let in cp0

### ISSUE THREAD

**Issue by gus-massa** [cisco/ChezScheme#482]
I'm still not sure, but I think this reduction is wrong:

    (expand/optimize '(let ([b (box 0)]) (let ([x (set-box! b 1)]) (list b x b))))
    ; ==>
    '(let ([b (#2%box 0)]) (#2%list b (#2%set-box! b 1) b))

 When it runs, I get the correct result `'(1 #<void> 1)` but I think there are no guaranties that the other steps of the compilation will run the `set-box!` first, so I think it is possible to get `'(0 #<void> 1)` or `'(0 #<void> 0)`.

But I could not make an example with wrong output.

**Comment by gwatt** [comment]
I think that's only an issue if you call unbox as part of the call to list, which then correctly orders the operations:
```scheme
(expand/optimize '(let ([b (box 0)]) (let ([x (set-box! b 1)]) (list (unbox b) x (unbox b)))))
; =>
(let ([b (#2%box 0)])
  (let ([x (#2%set-box! b 1)])
    (#2%list (#2%unbox b) x (#2%unbox b))))
```
When just passing `b` directly to list, the order of evaluation of the arguments doesn't matter, since the object will be mutated before any code in `list` ever runs.

**Comment by gus-massa** [comment]
I think you are correct.
