### ISSUE TITLE
read-char issues with unicode standard input on Windows 10

### ISSUE THREAD

**Issue by NHALX** [cisco/ChezScheme#484]
read-char seems to not be able to process unicode characters from text mode standard input ports on Windows 10 Pro 1909.

I've tried every combination of transcoder and buffer-mode options and it does not produce the correct result, nor does it produce any errors. Standard output works perfectly fine with UTF-8, and disk files do as well for both input and output. To test the terminal I checked that python3 deals with unicode input properly and it does.

The port is being converted like so:
(standard-input-port
         (buffer-mode block)
         (make-transcoder (utf-8-codec)))

The result is either #\nul or #\newline depending on which options/codecs are used. Various Greek letters were presented as input.

**Comment by burgerrg** [comment]
See issue https://github.com/cisco/ChezScheme/issues/466.  The Windows console does not support UTF-8. You need to use a Unicode terminal such as Cygwin's Terminal or Git Bash.

**Comment by NHALX** [comment]
@burgerrg recent builds seem to support it by setting the code page to 65001 (utf-8)

The default shell reads and writes unicode characters fine (tested with: mkdir Δ). Python3, when run in the terminal, does as well; as does Haskell's GHCI. Chez prints unicode ok but can't read.

Chez also has the same problem when run via an Emacs inferior mode on Windows. 

Most likely the windows APIs used by Chez don't interact well with the new UTF-8 codepage, but it should be possible to support unicode on Windows 10 without third party shells (which probably don't solve the problem with Emacs).

**Comment by burgerrg** [comment]
Thanks, I see that Windows 10 now supports code page 65001 (utf-8).

First, the expression editor uses the ANSI API, so one must disable it with the --eedisable command-line switch.

Second, Chez Scheme calls the _read function in the Microsoft C Runtime library on file descriptor 0, which seems to be in a mode that does not handle UTF-8. Perhaps a _setmode call with _O_U8TEXT could fix this, but then the rest of the code would need to handle UTF-16LE if I understand the MSDN documentation correctly.

If you're willing to figure out how to get Unicode console input and output to work in Windows, I would be happy to review a pull request.

**Comment by NHALX** [comment]
@burgerrg 

read-char produces the correct results when using GetStdHandle + ReadConsoleW + WideCharToMultiByte instead of _read at new_io.c:440. 

```
Chez Scheme Version 9.5.3
Copyright 1984-2019 Cisco Systems, Inc.

> (read-char)
Δ
#\Δ
```

However there are issues with this: 

1.) If STDIN is a file and not a console it needs to either identify the handle type or try, fail, and fall back to the default file handling since ReadConsole only works when stdin isn't remapped. 

2.) There is a question of how many wide characters should be read. If you read 'count' characters the result may be larger than requested due to UTF 16 -> 8 conversion. There are a variety of ways to deal with this but I don't know anything about the Chez code base, so I can't really comment.

The snippet below is what was used to test. It will crash the EE though.

```
  if (!gzflag && fd == 0)
  {
        wchar_t buf[count];

        DWORD size;
        HANDLE h = GetStdHandle(STD_INPUT_HANDLE);
        if (ReadConsoleW(h, buf, (IO_SIZE_T) count, &size, NULL))
        {
                m = WideCharToMultiByte(CP_UTF8, WC_ERR_INVALID_CHARS,
                                         buf, size, &BVIT(bv,start), (IO_SIZE_T) count, NULL, NULL);
        }
        else
        {
                m = 0;
        }
  }
```

**Comment by burgerrg** [comment]
Thanks for finding out how to read the Unicode characters using ReadConsoleW! The `s_ee_init_term` function in c/expeditor.c has a way to test if standard input is a console.

You might need to use a persistent buffer to handle the conversion to UTF-8 when you don't have room for all the bytes.

I'm not in a position to experiment with these changes, but I'd be happy to review a pull request if you'd like to take a stab at it.

**Comment by burgerrg** [comment]
Perhaps the easiest way to determine if the handle is a console is to call ReadConsoleW and see if it raises the error associated with invalid console handle. See https://docs.microsoft.com/en-us/windows/console/readconsole.

**Comment by NHALX** [comment]
@burgerrg what is the proper way to lock the persistent decode buffer in Chez?

The output buffer is locked with LOCKandDEACTIVATE(tc, bv), but I assume there needs to be a separate lock for the decode buffer.

I'll probably be ready to submit a pull request in a few days.
