### ISSUE TITLE
Can I keep both mit-scheme and Chez Scheme?

### ISSUE THREAD

**Issue by xnastudio** [cisco/ChezScheme#49]
I think this is a stupid question.
At ubuntu, after ./configure and sudo make install , I can use scheme or petite to start Chez Scheme.
But I found that I can't use mit-scheme to start mit-scheme anymore.
Can I keep both mit-scheme and chez-scheme?
Sometimes, I need mit-scheme to test the code of SICP.

**Comment by dengyunsheng250** [comment]
so dude,how you solve this issue?@xnastudio

**Comment by amirouche** [comment]
I have a project called scheme united pinned on my profile that install in a prefix mit et both chez variant. All three can be used from united interface.

Feedback welcome
