### ISSUE TITLE
Support for RISC-V

### ISSUE THREAD

**Issue by amirouche** [cisco/ChezScheme#491]
[RISC-V open-hardware started shipping](https://en.wikipedia.org/wiki/RISC-V#Implementations).

[QEMU support RISC V](https://wiki.qemu.org/Documentation/Platforms/RISCV), so it should be simple to start a port.

**Comment by pmatos** [comment]
Sorry - I only just saw this... 
I made a start a few years ago but it's far from finished - If there's interest I can keep working on it.
I own a Sifive Unleashed so I was targeting that.

https://github.com/pmatos/ChezScheme/tree/wip-riscv

**Comment by UeharaYou** [comment]
> Sorry - I only just saw this... I made a start a few years ago but it's far from finished - If there's interest I can keep working on it. I own a Sifive Unleashed so I was targeting that.
> 
> https://github.com/pmatos/ChezScheme/tree/wip-riscv

I'm currently working on a prototype chip based on riscv. It will be appreciating if there is any bootstrap-tips or experienced on migrating chezscheme to riscv arch (or potentially other platform). Thank you.

**Comment by mflatt** [comment]
RISC-V is now supported.
