### ISSUE TITLE
import in REPL

### ISSUE THREAD

**Issue by fedeinthemix** [cisco/ChezScheme#50]
Hi,

I'm trying to use SRFI-26 from https://github.com/arcfide/chez-srfi. Using import in the REPL doesn't work as I would expect from the documentation:

> (import (srfi :26))
> ((cut + 1 <>) 1)
Exception: incorrect argument count in call ((lambda () (+ 1 <>)) 1)
Type (debug) to enter the debugger.

However, if I wrap it in a top-level-program form it does work.

> (top-level-program
     (import (rnrs) (srfi :26))
     (display ((cut + 1 <>) 1))
     (newline))
2

Is something special required to use import in the REPL?

Thanks,
Fede

**Comment by hyln9** [comment]
See #41

**Comment by fedeinthemix** [comment]
I missed that. Thanks!
