### ISSUE TITLE
The link to "The Scheme Programming Language" on www.scheme.com is broken

### ISSUE THREAD

**Issue by lockywolf** [cisco/ChezScheme#501]
The original link from the phrase "It is available for order direct from MIT Press and various online and local retailers." is no more. (The old one was https://mitpress.mit.edu/books/scheme-programming-language)

The correct one now is probably https://mitpress.mit.edu/books/scheme-programming-language-fourth-edition

**Comment by dybvig** [comment]
Fixed, thanks!
