### ISSUE TITLE
CSUG reference [10] outdated

### ISSUE THREAD

**Issue by xaengceilbiths** [cisco/ChezScheme#505]
http://www.ccs.neu.edu/events/wand-symposium/
=>
http://www.ccs.neu.edu/home/dherman/browse/subversion/web-sites/mitchfest/program.html

**Comment by jltaylor-us** [comment]
New link is also 404.  I managed to find it on archive.org
https://web.archive.org/web/20170626072601/http://www.ccs.neu.edu/events/wand-symposium/talks/mitchfest-09-dybvig.pdf

Someone will get around to updating the docs eventually. :)
