### ISSUE TITLE
Can‘t make chez on FreeBSD machine

### ISSUE THREAD

**Issue by kelvenchi** [cisco/ChezScheme#52]
I have found a piece of code in 'configure' file about FreeBSD 
```
if uname -a | egrep 'i386|i686|amd64|athlon|x86_64' > /dev/null 2>&1 ; then
    m32=i3fb
    m64=a6fb
    tm32=ti3fb
    tm64=ta6fb
fi 
installprefix=/usr/local
nstallmansuffix=man
```
but when I run the './configure' command , it tell me 'available machine types: a6le, a6nt, a6osx, i3le, i3nt, i3osx, ta6le, ta6nt, ta6osx, ti3le, ti3nt, and ti3osx' and my question is: what is the right machine type for FreeBSD amd 64. And what is i3fb, a6fb, ti3fb, ta6fb that mentioned in that piece of code ?

**Comment by dybvig** [comment]
configure considers a machine type $m available if the file boot/$m/scheme.boot is present, so you first need to create that boot file.  To get the required boot and header files in place, try the instructions given in BUILDING in the second paragraph under 'make bootfiles'.
