### ISSUE TITLE
Macro is rendered as `(void)` by `(expand ...)` if macro expands into `define-ftype`.

### ISSUE THREAD

**Issue by lemvik** [cisco/ChezScheme#525]
Hi!

I have a question regarding `(expand ...)` behavior. 

I'm writing some macros to simplify generation of a C-library bindings. These macros leverage a convention that target library has to remove boilerplate from `struct` definitions. I'd like to debug those macros and to that extent I only found [`expand` and `expand/optimize`](https://cisco.github.io/ChezScheme/csug9.5/system.html#./system:s90) procedures.

Unfortunately, in some cases the expansions they output are rendered as `(#2%void)`, most notably (and most annoyingly) when macro expands into `define-ftype`.

Here are some examples (from REPL):

1. Definition that expands to `define-ftype`:
```scheme
> (define-syntax test-struct-expansion
    (lambda (x)
      (syntax-case x (fields)
        [(_ fn (fields (fname ftype) ...))
         #'(define-ftype fn
             (struct
               [fname ftype] ...))])))
> (expand '(test-struct-expansion a-struct (fields (a unsigned-32))))
(#2%void)
```
2. Definition that expands into `define-record-type`:
```scheme
> (define-syntax test-record-expansion
    (syntax-rules (fields)
      [(_ fn (fields fname ...))
       (define-record-type fn
         (nongenerative)
         (fields (immutable fname) ...))]))
> (expand '(test-record-expansion str (fields a)))
(begin
  (set! make-str
    (#2%r6rs:record-constructor
      '#<record constructor descriptor>))
  (set! str? (#2%record-predicate '#<record type str>))
  (set! str-a (#2%record-accessor '#<record type str> 0))
  (#2%void))
```

My assumption is that `define-ftype` expands into some meta definitions that are only available in compilation/expansion contexts and thus do not produce code that will end up being compiled. So the whole expansion ends up visible as `(void)` in the end, as the actual effect of expansion results in augmenting the compiler/expander with new defines used to generate code.

My current macro debugging approach is somewhat ugly as I basically either add `(format #t "~&Debugging: ~a~%" ...)` in `syntax-case` macros or just create pointers to generated `ftype`s and call `(ftype-pointer-ftype ...)` on them to get the generated structure.

So, questions:
1. Is there any analog to `(macroexpand-1 ...)` from Common Lisp? Maybe some internal procedure that can be used as such?
2. If not, what could be more sensible approach to debug such definitions? 

Thanks!

P.S. Thank you for the wonderful Scheme implementation and a really nice documentation!

**Comment by lemvik** [comment]
After some thought, there is another (and much simpler) way to debug output (in simple cases at least) - just return quoted expression from macro:

```scheme
> (define-syntax test-quoted-struct-expansion
    (lambda (x)
      (syntax-case x (fields)
        [(_ fn (fields (fname ftype) ...))
         #''(define-ftype fn ; <- here another ' character to quote the returned form
              (struct [fname ftype] ...))])))
> (test-quoted-struct-expansion astr2 (fields [a unsigned-32]))
(define-ftype astr2 (struct [a unsigned-32]))
```

Still, if there is some other facility to debug macro expansions, it would be nice to know.

**Comment by akeep** [comment]
There are two tools to help out with this: `trace-define-syntax` which works like `trace-define` and shows the input and output of the syntax transformer.  For instance:

```scheme
> (trace-define-syntax test-struct-expansion
      (lambda (x)
        (syntax-case x (fields)
          [(_ fn (fields (fname ftype) ...))
           #'(define-ftype fn
               (struct
                 [fname ftype] ...))])))
> (expand '(test-struct-expansion a-struct (fields (a unsigned-32))))
|(test-struct-expansion
   (test-struct-expansion a-struct (fields (a unsigned-32))))
|(define-ftype a-struct (struct [a unsigned-32]))
(#2%void)
```

If you are interested in seeing what things eventually expand into, for these cases where the run-time expansion is just `(void)`, we have an internal primitive called `$expand/cte` which will show both the compile-time expansion code (`visit`) and run-time expansion code (`revisit`).  Since it is an internal, you need to specifically call it using the `#%` syntax:

```scheme
> (#%$expand/cte '(test-struct-expansion a-struct (fields (a unsigned-32))))
(begin
  (recompile-requirements () ())
  (eval-when (visit)
    (#3%$sc-put-cte
      '#<syntax a-struct>
      (#3%$transformer->binding
        (#2%make-compile-time-value '#<ftd a-struct>))
      '*top*)))
```

You can also see the results of the optimizer on this using `$expand/cte/optimize`, though in this case there is not much to optimize.
