### ISSUE TITLE
9.5.4 release

### ISSUE THREAD

**Issue by dybvig** [cisco/ChezScheme#528]
I've been asked to create a long-overdue release.  This is a heads up that I will be working on that over the next several days.  First, I intend to address the S_condition_wait limitation mentioned in issue #527 and the record-writer bug mentioned in issue #441.  I will also look into using the latest subprojects per pull request #472.  If I've missed any other bug-fix issues that should be addressed please respond to this issue.  In order to ensure stability of the release, I won't be making / pulling any major changes.

**Comment by dybvig** [comment]
I would be happy to include fixed arm32le support in the release.  I haven't been following the progress. Is there working arm32le code in the Racket branch of Chez Scheme?

**Comment by mflatt** [comment]
Yes, the Racket branch has working arm32le implementation. Unfortunately, changes there to "arm32.ss" are tangled up with many other changes, but hopefully the notes in #438 point well enough to relevant changes.

**Comment by dybvig** [comment]
I don't have an Arm setup or time to create one and update the Arm code based on the notes in #438.   If someone else is willing to do so in the next few days I'll hold off on this release; otherwise we'll have to do this release without it and perhaps get it into the next.

**Comment by cjfrisz** [comment]
I think I can make time to pull in the changes and test on my RasPi 4 in the next few days. What's your preferred cutoff date/time so I have a deadline to motivate myself against?

**Comment by dybvig** [comment]
Thanks @cjfrisz.  I'd like to do the release on Sunday, so getting the changes in by late Saturday would be great.

**Comment by cjfrisz** [comment]
I started in on the changes per @mflatt in #438 yesterday, and it compiles on my Pi, but there's still errors in the `foreign.ms` `structs` mats. I thought the ABI changes wrt the floating point registers should have fixed that, so I'm hoping to find a bug in my environment or my translation of the part of racket@4066af9 @mflatt pointed out.

Otherwise, I've disabled the `$read-time-stamp-counter` mats for `arm32le` since there was never a discussion about how to handle it with the need for a kernel module. I suppose it would probably be better to have it throw a compile-time error and update the mats to reflect that until we come up with a better solution.

I also didn't tackle the varargs ABI, os I've disabled that mat for `arm32le` as well.

**Comment by dybvig** [comment]
Thanks @cjfrisz for pushing forward on this.

Did you also pull in the sign extension changes and the change from r11 to r7 mentioned in #438?  Plus address @weinholt's arm32.ss review comment in #510?

It might be useful to update #510 with your latest changes so others can look at them and possibly spot something.

WRT read-time-stamp-counter, I think it's better to leave it as a run-time rather the compile-time error with notes in the release notes and user's guide that a kernel module must be created to enable the feature, along with a new issue requesting that someone create the kernel module.

**Comment by cjfrisz** [comment]
Immediately after I posted, I found a bug in my translation, so I have another round of tests to try.

> Did you also pull in the sign extension changes and the change from r11 to r7 mentioned in #438? Plus address @weinholt's arm32.ss review comment in #510?

I included both.

> It might be useful to update #510 with your latest changes so others can look at them and possibly spot something.

I also got a note from @mflatt and will update my fork in a few minutes.

> WRT read-time-stamp-counter, I think it's better to leave it as a run-time rather the compile-time error with notes in the release notes and user's guide that a kernel module must be created to enable the feature, along with a new issue requesting that someone create the kernel module.

I'll leave it alone and update the docs. Please feel free to edit that if we get to a place to merge.

**Comment by cjfrisz** [comment]
I pushed my latest changes to https://github.com/cjfrisz/ChezScheme/commit/28192422c94da20b459d9de4f76e99a042f05286. It's definitely not correct, since there are new bugs in all sorts of `foreign.ms` tests.

**Comment by cjfrisz** [comment]
I've already spotted one issue: https://github.com/cjfrisz/ChezScheme/commit/28192422c94da20b459d9de4f76e99a042f05286#diff-b79ccbf9fd46030acc7c997ebd74d595R3036

I used the wrong fp registers for the callee-save list.

**Comment by cjfrisz** [comment]
I pushed the fix for `callee-save-fpregs` to https://github.com/cjfrisz/ChezScheme/commit/da5bdce2a079263f989bd6c1a2adeb2a7cd00cc7, but I'm back to the "invalid memory reference" and "illegal instruction" errors in the `structs` mat.

**Comment by mflatt** [comment]
It looks like the problem is a missing `return-bytes` in the sum at https://github.com/cjfrisz/ChezScheme/blob/fix-arm32le/s/arm32.ss#L3084

Apparently, I fixed that later than other things mentioned in #438, then forgot about the repair. Sorry about that!

**Comment by cjfrisz** [comment]
Thanks! Not all the mats have finished, but the `structs` errors in the `o=0` and `o=3` mats have gone away.

**Comment by cjfrisz** [comment]
@dybvig I poked around in csug to find a place to document the kernel module for `$read-time-stamp-counter`, but didn't come up with anything since there aren't entries for individual primitives--do you have any suggestions? Similarly, is there anything I should do to make sure that gets into the release notes?

My Pi very rudely interrupted the ssh session where the mats were running, so I've restarted them in a screen. Once they presumably pass (knock on wood), I'll initiate a pull request.

**Comment by dybvig** [comment]
I had forgotten we didn't surface the feature as a user primitive either directly or indirectly.  So forget about documenting it in the user's guide, since, by design, system primitives are undocumented.    The existing Version 8.9.1 release note for $read-time-stamp-counter already mentions that the feature might not be enabled outside the kernel, so the most I would do is add a similar note to say that $read-time-stamp-counter is supported for 32-bit ARM only if enabled in the kernel.  You could also be silent about it in the release notes and put a reminder in prims.ss in case someone someday decides to surface the feature.

**Comment by cjfrisz** [comment]
I marked #510 ready for review, added the note to `prims.ss` that you suggested, and added a mat to `misc.ms` based on @weinholt's test for the immediate bug. It's probably worth documenting the incomplete varargs support for `arm32le`, but I don't understand the details like @mflatt does.

**Comment by cjfrisz** [comment]
I've left something out in using the test libraries for the mat I added, and now the TravisCI builds are failing. On review, I don't think I did things with test files the way they're usually used, so I can try to rework it in the morning or back out that change if it's blocking merge.

There were some previous builds that had errors in the `misc.ms` `lock-object` mat for one OSX build and one Bionic build, but I'm not sure how I could have caused that.

Again, I'll take a look in the morning and hopefully have things ironed out before it's time to cut the release.

**Comment by cjfrisz** [comment]
I rewrote that new mat to create its testfiles a la other mats, and it worked with a `make` in the `mats` directory with a clean workspace. I have a full `make allx` run going on my laptop, and I'll go update the PR if I get a pass on `o=0` and `o=3`.

**Comment by dybvig** [comment]
Okay, I've just created a release of Version 9.5.4 and bumped master to 9.5.5.  @burgerrg, would you please add an .exe file to the release (at tag v9.5.4) as you have so kindly done in the past?

**Comment by burgerrg** [comment]
The Windows install is now part of the release page.

**Comment by dybvig** [comment]
Thanks!
