### ISSUE TITLE
Missing tag release for 9.5.3

### ISSUE THREAD

**Issue by thomasdziedzic** [cisco/ChezScheme#531]
I wanted to compare what the differences were between 9.5.3 and 9.5.4 through github's ui, but I'm unable to do so because there is a missing tag for 9.5.3.

**Comment by dybvig** [comment]
We have been creating releases only for even-numbered versions, e.g., 9.5.2 and 9.5.4, with odd-numbered versions serving as progressively changing development snapshots.  So if you want to see what's changed between released versions, you can do that by comparing 9.5.2 and 9.5.4.  Literally the only change between 9.5.3 and 9.5.4 is the change in version numbers.

**Comment by thomasdziedzic** [comment]
ok, thank you for the clarification!
