### ISSUE TITLE
SICP compatibility

### ISSUE THREAD

**Issue by anonyno** [cisco/ChezScheme#533]
The [version 3 release notes][1] mention a procedure named `support-sicp` but it doesn't exist in the current version. Is there any other way to get SICP compatibility with Chez Scheme?

[1]: https://www.scheme.com/docs/3.pdf

**Comment by Lysias-1998** [comment]
In Racket we can't use `set-car!` straightforward, but in Chez Scheme we can. So what specific problem do you encounter when using Chez Scheme for reading SICP?

**Comment by amirouche** [comment]
There is https://srfi.schemers.org/srfi-216/

**Comment by amirouche** [comment]
It will require R7RS libraries from akkuscm.org

**Comment by anonyno** [comment]
thank. I will try SRFI 216.
