### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by donaldcallen** [cisco/ChezScheme#538]
In the Chez Scheme User's Guide, Section 4.5, the explanation for foreign-ref says "foreign-ref extracts the value of type type offset bytes **into** the block of foreign data addressed by address." (Emphasis mine.) I think what is meant is "foreign-ref extracts the value of type type offset bytes **from** the block of foreign data addressed by address."

I ran into trouble with foreign-ref today, which turned out to be completely of my own doing, but this little issue in the documentation further confused me and delayed my getting things straightened out for a bit (I had to make a test case to determine whether foreign-ref did what I thought it did rather than what the documentation says; it was the former). So the code works fine, but I think this little documentation error needs to be fixed.

**Comment by jltaylor-us** [comment]
I think the entire later half of the sentence is supposed to be read as position from which the value is extracted.  I.e. "into" meaning  "offset from the beginning of".  It might be clearer to restate as: 
> `foreign-ref` extracts the value of type _type_ from the memory location at _offset_ bytes offset from _address_. 

This also makes more sense than "into" when _offset_ is negative and removes possible confusion about what "block" means.  The restrictions on where the resulting memory location may be are already specified later in the function description.
