### ISSUE TITLE
Uninstall Chez Scheme built from source?

### ISSUE THREAD

**Issue by Jonathan50** [cisco/ChezScheme#55]
The makefile doesn't have an uninstall target.

**Comment by Jonathan50** [comment]
I've just run
```
sudo rm -rf /usr/bin/scheme /usr/bin/petite /usr/bin/scheme-script /usr/lib/csv9.4/ /usr/share/man/man1/scheme.1.gz /usr/share/man/man1/petite.1.gz
```
Hopefully I haven't messed anything up...

**Comment by TisonKun** [comment]
@burgerrg could you take a look at this?

1. if the process above sufficient for "totally" removing
2. whether we introduce a `uninstall` target or mentioned somewhere, like BUILDING

**Comment by burgerrg** [comment]
There is an uninstall target in Mf-install, but it only echos instructions, and I don't think it handles schemescript. I'll look into this.

**Comment by TisonKun** [comment]
@burgerrg nice job! then could we just close this thread?

**Comment by burgerrg** [comment]
Yes, thank you!
