### ISSUE TITLE
The order of execution of module initializers

### ISSUE THREAD

**Issue by arkoort** [cisco/ChezScheme#551]
The [documentation](https://cisco.github.io/ChezScheme/csug9.5/syntax.html#./syntax:h5) says:

> A module consists of a (possibly empty) set of definitions and a (possibly empty) sequence of initialization expressions.

The code:

```scheme
#!chezscheme
(import (scheme))

(module ma (a)
  (define a 11)
  (set! a 111)
  (pretty-print (list 'a a)))

(import ma)
(pretty-print (list 1 a))

(module (b)
  (define b 22)
  (set! b 222)
  (pretty-print (list 'b b)))

(pretty-print (list 2 b))
```

The output of version 9.5.4 (identical in `scheme` and `petite`):

```
(1 11)
(2 22)
(a 111)
(b 222)
```

Why are both initialization expressions executed after the usage of module definitions?
(And is there the way to control the execution order?)

**Comment by burgerrg** [comment]
I put the code above into code.ss and get the output you expected:
```scheme
% scheme code.ss
Chez Scheme Version 9.5.4
Copyright 1984-2020 Cisco Systems, Inc.

(a 111)
(1 111)
(b 222)
(2 222)
```
I get the output you reported when running `scheme --program code.ss`. Top-level programs are treated differently. See [Section 10.3](https://scheme.com/tspl4/libraries.html#g145) of _The Scheme Programming Language_.

**Comment by burgerrg** [comment]
If you wrap the non-definitions in an empty module, you'll get the behavior you expect from the top-level program:
```scheme
(import (scheme))

(module ma (a)
  (define a 11)
  (set! a 111)
  (pretty-print (list 'a a)))

(import ma)
(module ()
  (pretty-print (list 1 a)))

(module (b)
  (define b 22)
  (set! b 222)
  (pretty-print (list 'b b)))

(module ()
  (pretty-print (list 2 b)))
```

**Comment by arkoort** [comment]
Thank you. Probably, [11.5](https://cisco.github.io/ChezScheme/csug9.5/syntax.html#g103) describes it:

>  Internal definitions and definitions within a module body are processed from left to right so that a module's definition and import may appear within the same sequence of definitions. Expressions appearing within a body and the right-hand sides of variable definitions, however, are translated only after the entire set of definitions has been processed, allowing full mutual recursion among variable and syntactic definitions. 

This was not clear to me at the first glance.

**Comment by burgerrg** [comment]
Yes, thanks, that's exactly where it's explained, which I couldn't find when I wrote back earlier.
