### ISSUE TITLE
sleeping forever

### ISSUE THREAD

**Issue by ocyzl** [cisco/ChezScheme#553]
`(sleep (make-time 'time-duration 0 -1))` appears to sleep forever. (I'm running Chez Scheme 9.5.4 64-bit nonthreaded on Windows 7.) It would probably be better for `sleep` to return immediately when given a negative time duration. Or, at least, document the current behavior.

**Comment by burgerrg** [comment]
I'd be happy to review a pull request to fix this in Windows.

**Comment by ocyzl** [comment]
I don't really know how to use Git, but maybe the following will be useful.

`sleep` is defined in [s/7.ss](https://github.com/cisco/ChezScheme/blob/master/s/7.ss) at line 697:
<pre>
(define-who sleep
  (let ([fp (foreign-procedure "(cs)nanosleep" (ptr ptr) void)])
    (lambda (t)
      (unless (and (time? t) (eq? (time-type t) 'time-duration))
        ($oops who "~s is not a time record of type time-duration" t))
      (fp (time-second t) (time-nanosecond t)))))
</pre>

I would put an `if` around the call to `fp` at the end:
<pre>
(define-who sleep
  (let ([fp (foreign-procedure "(cs)nanosleep" (ptr ptr) void)])
    (lambda (t)
      (unless (and (time? t) (eq? (time-type t) 'time-duration))
        ($oops who "~s is not a time record of type time-duration" t))
      (if (>= (time-second t) 0)
          (fp (time-second t) (time-nanosecond t))
          (fp 0 0)))))
</pre>

This change affects all targets, not just Windows, but that seems right to me.  The foreign procedure `s_nanosleep`, defined in [c/prim5.c](https://github.com/cisco/ChezScheme/blob/master/c/prim5.c) at line 1196, gets the value of its first argument by calling `Sunsigned64_value` on it, and puts the result in a variable of type `U64`, which indicate that it's not expecting a negative number.  So `sleep` shouldn't pass it one.  If the current code works on Linux, that's probably because the unsigned value gets converted back to a signed one when it gets put in the `tv_sec` field of a `struct timespec`, and then Linux's `nanosleep` returns immediately with an error because of the negative `tv_sec`.  See the [Linux man page for `nanosleep`](https://man7.org/linux/man-pages/man2/nanosleep.2.html).  Windows' `Sleep` on the other hand takes a `DWORD` argument, which is unsigned, so what was a negative number gets interpreted as a large positive one, and Windows therefore sleeps for a long time.  See Microsoft's documentation for [`Sleep`](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleep) and for [`DWORD`](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dtyp/262627d8-3418-4627-9218-4ffe110850b2).

**Comment by burgerrg** [comment]
Thanks, commit 5342bb33b6abd14d6addab8b296999888c419996 should fix it.
