### ISSUE TITLE
About opaque records

### ISSUE THREAD

**Issue by gus-massa** [cisco/ChezScheme#554]
The functions `record-equal-procedure` and `record-hash-procedure` do not raise an error like `record-rtd` when applied to opaque records. 

The current behavior is fine, but I just want to know if it's a mistake or it is on purpose.

    (define-record-type point (fields x y) (opaque #t))
    (define p (make-point 1 2))
    (record-equal-procedure p p)  ; => #f
    (record-hash-procedure p) ; => #f
    (record-rtd p) ; => Exception in record-rtd: #<point> is not a record

**Comment by burgerrg** [comment]
[Chapter 9](https://scheme.com/tspl4/records.html#./records:h1) of _The Scheme Programming Language_ states:

> Opaque clause.  An opaque clause of the form (opaque #t) declares that the record type is opaque. Instances of an opaque record type are not considered records by the record? predicate or, more importantly, the rtd-extraction procedure record-rtd, which are both described in Section 9.3.

[Section 7.14](https://cisco.github.io/ChezScheme/csug9.5/objects.html#./objects:h14) of the _Chez Scheme User's Guide_ states:

> A default equality procedure to be used for all record types (including opaque types) can be specified via the parameter default-record-equal-procedure. The default equality procedure is used only if neither instance's type has or inherits a type-specific record equality procedure.

> A default hash procedure to be used for all record types (including opaque types) can be specified via the parameter default-record-hash-procedure. The default hash procedure is used only if an instance's type does not have or inherit a type-specific hash procedure.

Thus, the behavior you highlighted seems intentional.

**Comment by gus-massa** [comment]
Thanks
