### ISSUE TITLE
Are there any introduction materials of the BOOT file format?

### ISSUE THREAD

**Issue by lhtin** [cisco/ChezScheme#578]
Hi all,

I'm a new hand in the Chez Scheme compiler system. But I need to understand the BOOT file format because of my work. Therefore, I would like to ask if there is any existing information about the system that can help me understand.

Thank you so much.

**Comment by lhtin** [comment]
[Here](https://github.com/racket/ChezScheme/blob/master/IMPLEMENTATION.md) is a very useful document about the implementation details of the Chez Scheme.

**Comment by WEREWOLFGHOST** [comment]
You can read the code and comments in c/fasl.c, esp. the function faslin(), which parses fasl files and allocates objects accordingly.

**Comment by mflatt** [comment]
Closing now that "IMPLEMENTATION.md" is merged, although there's plenty of room for improvement.
