### ISSUE TITLE
The expression (cond #t (else 2)) should raise an exception

### ISSUE THREAD

**Issue by ByLiZhao** [cisco/ChezScheme#588]
The expression `(cond #t (else 2))` currently returns `#t` with the latest main branch.

The expression should raise an exception instead.  
The same expression with Chez Scheme version 9.5.4, will cause the following exception being raised:

>  > (cond #t (else 2))
    Exception: invalid syntax (cond #t (else 2))
    Type (debug) to enter the debugger.

**Comment by burgerrg** [comment]
With Chez Scheme commit c0374240dde4a6c31d61a3d8a2c31439be249798, I can't reproduce it:
```
Chez Scheme Version 9.5.5
Copyright 1984-2020 Cisco Systems, Inc.

> (cond #t (else 2))
Exception: invalid syntax (cond #t (else 2))
```
Perhaps you're using `cond` in a place where its definition is shadowed?

**Comment by ByLiZhao** [comment]
I just tried again. And I can't reproduce it too. 
I am pretty sure when I tried it I did not use it in a context where `cond`'s definition is shadowed. 

I would like to try it again in a VM from a fresh state.

**Comment by ByLiZhao** [comment]
I could not reproduce the issue when tried again. 
I will close the issue.
