### ISSUE TITLE
char->integer or read-char Issues

### ISSUE THREAD

**Issue by uternet** [cisco/ChezScheme#59]
I defined a procedure `read-byte` and try to parsing a JPEG file in Chez.

```
    (define (read-byte . opt)
      (let ((c (apply read-char opt)))
        (if (eof-object? c) c (char->integer c))))
```

The bytes like `ff d8 ff e1`  always return numbers: 65533 65533 65533 65533 ....

A byte maximum is `FF`, equal to 255, How is 65533?

```
> (char->integer (integer->char 255))
255
```

The same code runs correctly in Larceny

```
> (define ip (open-input-file "1.jpg"))
> (define (read-byte . opt)
      (let ((c (apply read-char opt)))
        (if (eof-object? c) c (char->integer c))))
read-byte

> (read-byte ip)
255

> (read-byte ip)
216

> (read-byte ip)
255

> (read-byte ip)
225
```

**Comment by jltaylor-us** [comment]
Characters are not bytes.  Perhaps you want `get-u8`?
(In other words, if you open a binary file with a textual input port, you're gonna have a bad time.)

**Comment by uternet** [comment]
thank jltaylor-us.
