### ISSUE TITLE
is random supposed to be uniform?

### ISSUE THREAD

**Issue by amirouche** [cisco/ChezScheme#592]
I was said random is biased; but I can not reproduce; it seems uniform (see the screen capture).

What I can tell is that the [expected behavior of `random` is not documented](https://cisco.github.io/ChezScheme/csug9.5/numeric.html#g70), but that is maybe too much niche?

![screenshot-2021-11-14T15:39:04+01:00](https://user-images.githubusercontent.com/7444897/141685826-374e8d29-94be-46cb-90a6-eafe5f85590e.jpg)

**Comment by amirouche** [comment]
Here is the program that produce the graphical output:

```scheme
#!chezscheme
(import (chezscheme))


(let loop ((index (expt 10 6)))
  (unless (fxzero? index)
    (let* ((number (random 8))
           (vt100-color (fx+ 30 number)))
      (format #t "\033[~smx\033[0m" vt100-color)
      (loop (fx- index 1)))))
```

**Comment by amirouche** [comment]
link to the documentation: https://cisco.github.io/ChezScheme/csug9.5/numeric.html#g70

**Comment by amirouche** [comment]
See https://gitlab.com/mdhughes/scheme-test/

<img width="2329" alt="Screen_Shot_2021-11-14_at_07 05 28" src="https://user-images.githubusercontent.com/7444897/141689612-329a4289-fbaa-47b9-b523-0303aae9f67a.png">

**Comment by amirouche** [comment]
Given the following program that includes `(random 255)` a million time:

```scheme
(import (chezscheme))


(let loop ((index (expt 10 6)))
  (unless (fxzero? index)
    (display (random 255))
    (newline)
    (loop (fx- index 1))))
```

It appears like `random` is not uniform, here is an extract from the histogram, the second column is what `(random 255)` yields, the first column is the number of times it appears:

```
   4064 7
   3982 70
   3986 71
   4035 72
   3919 73
   3892 74
   3941 75
   3791 76
   3898 77
   3984 78
   3893 79
   3819 8
   3921 80
   3974 81
   3833 82
   4124 83
   3872 84
   3897 85
   3972 86
   3804 87
   3816 88
   3858 89
   3912 9
   3858 90
   3918 91
   3897 92
   3827 93
   3888 94
   3836 95
   3933 96
   3860 97
   3949 98
   3923 99
```

**Comment by amirouche** [comment]
Sorry, deleted my last comment, the histogram I used does not display the problem either.

**Comment by jltaylor-us** [comment]
What, exactly, is the issue?

One of the great things about open source software is that if you want to know how something is implemented you can just look at the code.  Reading the [scheme](https://github.com/cisco/ChezScheme/blob/2077454566b0a845ee5804806c4ac94ad80984fd/s/5_3.ss#L2634) and then underlying [c](https://github.com/cisco/ChezScheme/blob/2077454566b0a845ee5804806c4ac94ad80984fd/c/prim5.c#L903) for `random`, we can see that Chez Scheme uses a linear congruential pseudo-random number generator.  This class of random number generator is described in detail in Knuth's _The Art of Computer Programming_, Volume 2, section 3.2.1.  The summary on [Wikipedia](https://en.wikipedia.org/wiki/Linear_congruential_generator) is pretty good.  If you want to analyze the algorithm for various measures of "randomness" then the remainder of that chapter of Knuth has several different metrics (both theoretical and empirical) that you can compute.

**Comment by amirouche** [comment]
Thanks for the useful reply. I do not have the habit to look at the code. Thanks for the hint!

**Comment by amirouche** [comment]
> What, exactly, is the issue?

`random` will repeat the same value multiple times, I guess it is intended.
