### ISSUE TITLE
Exception in compile-whole-program: unable to locate expanded library file for (arew)

### ISSUE THREAD

**Issue by amirouche** [cisco/ChezScheme#602]
I am trying to compile a program that rely on `(arew)` that is shipped with a custom `arew.boot`. It errors with:

> Exception in compile-whole-program: unable to locate expanded library file for (arew)

Is it possible to compile a program without the source, nor the `.wpo`, nor the `.so` just with the boot file. If so, how?

**Comment by amirouche** [comment]
Some context: I am trying to create a single binary executable that contains everything needed to compile Scheme programs with my own libraries. Given the `compile-whole-program` error, it seems like I also need to include the sources of the library `(arew)`, or at least to `.so` and `.wpo` files inside the binary, and at compile time unpack those, and recompile all the things.

**Comment by akeep** [comment]
Whole program compilation works by taking the intermediate representation stored in a set of `.wpo` files and combining it into a single nested `letrec` that is compiled as a single chunk through the rest of the compiler.  Without the `.wpo` files, there is no point in doing whole program compilation, as the `.so` and `.boot` files do not retain enough information for the compiler to do any useful optimization with them.  If you have a mix of `.wpo` files and `.so` files, whole program compilation can insert loading of the code from the `.so` file at the appropriate time based on the dependency information.

If you are just hoping to combine several binary files, like `.so` and `.boot` files into a single file, I believe it should still be possible to simply concatenate them together, though it is worth noting that the order matters if there are dependencies between the files.

**Comment by jltaylor-us** [comment]
> If you are just hoping to combine several binary files, like .so and .boot files into a single file, I believe it should still be possible to simply concatenate them together

I don't think this works anymore; use `concatenate-object-files` instead.

**Comment by amirouche** [comment]
Thanks.

**Comment by amirouche** [comment]
To say otherwise what is said in this thread: 

A custom `.boot` made of my own libraries do not contain all the necessary information to compile another program `program.scm` to a binary executable (but it is sufficient to run `program.scm`). To make it possible to compile some `program.scm` into a standalone executable it requires the `.boot` file and the object files of the custom libraries, the files with the extension `.so`. A library made of several other libraries can be packed with [`concatenate-object-files`](https://cisco.github.io/ChezScheme/csug9.5/system.html#./system:s82) into a single `.so` file.
