### ISSUE TITLE
Were 9.5.6 release files changed?

### ISSUE THREAD

**Issue by kbertalan** [cisco/ChezScheme#605]
Recent installs using Arch linux [chez-scheme AUR package](https://aur.archlinux.org/packages/chez-scheme/) are failing due to mismatch in the sha256 sum of [csv9.5.6.tar.gz](https://github.com/cisco/ChezScheme/releases/download/v9.5.6/csv9.5.6.tar.gz).
The package expects to see this sha 256 sum:

    6b3d1d111c6c47a4e51b500b30f4c29efd339e414f6ace743cff6d08a0dacaae

When I download the file I see this sha 256 sum:

    9aaa208c63eda8edfad72566790db0f9cedc7c6bb860157c400c98e22583c6b4

The AUR package definition has not changed since 24th November, see [the change history](https://aur.archlinux.org/cgit/aur.git/log/PKGBUILD?h=chez-scheme). I had used it for installing chez scheme, and I'm pretty sure that the checksum was fine before.

This kind of changes can mean security risks.

Was there any known change made on the release files recently?

**Comment by jltaylor-us** [comment]
The tarballs were updated so that `s/update-revision` has the proper revision ids (to match what `git archive` would produce).  @burgerrg or @owaddell can provide more details and rationale if necessary.

**Comment by kbertalan** [comment]
@jltaylor-us Thanks for the answer. I am glad that this was a known/planned change.
