### ISSUE TITLE
= can be not transitive

### ISSUE THREAD

**Issue by FrankHB** [cisco/ChezScheme#606]
R6RS requires `=` to be transitive.

However, with a case from [this page](https://codewords.recurse.com/issues/one/when-is-equality-transitive-and-other-floating-point-curiosities): `(= 9007199254740992.0 9007199254740993)` => `#t`.

This is not conforming. The requirement is same from R5RS to R7RS, and there is a note in R7RS stating "the implementation  approach of converting all arguments to inexact numbers if any argument is inexact is not transitive".

(I'm not sure whether this is intended in R6RS, since [this ticket](https://small.r7rs.org/ticket/367/) suggests inexact contagion is allowed generally.)

**Comment by FrankHB** [comment]
> Chez Scheme is based on R6RS. Even though the procedure `=` returns a boolean value (not a numerical value) I think this sentence of R6RS § 11.7.1 can be applied to `=`:
> 
> > The general rule is that the generic operations return the correct exact result when all of their arguments are exact and the result is mathematically well-defined, but return an inexact result when any argument is inexact.
> 
"Generic" has sense of parametric polymorphism (just not formally required in a latent-typing language like Scheme); it suggests more about how to infer the exactness property of the result from arguments, rather than the concrete value of the result own.

The exactness is not a property of boolean. So, I don't think the report is using "inexact" as you meant here. 

> The way I understand it, this allows `=` to return an incorrect result when any of its arguments is inexact. For the procedure `=`, returning an incorrect result means possibly returning `#t` when its arguments are not equal, and possibly returning `#f` when its arguments are equal. If the result produced by `=` is incorrect, then the main property of the procedure `=` ("returns `#t` iff all arguments are equal") does not hold, consequently I see no reason to try to maintain a secondary property (like transitivity) at all costs. The fact that R7RS-small introduces a contradiction (in the note you are referring to) shouldn't change the meaning of R6RS.
> 

It is expect to return results not always keeping the same accuracy of the input (hence reliable) for inexact numbers, but not incorrect one (with arbitrary imprecision); otherwise, `=` is practically useless for inexact numbers.

> My understanding seems to be confirmed in R6RS § 11.7.4, in a note about the procedure `=`:
> 
> > _Note:_ While it is possible to compare inexact number objects using these predicates, the results may be unreliable because a small inaccuracy may affect the result; this is especially true of `=` and `zero?` (below).

As of the note, see the discussions in the chibi issue mentioned above.

... Let's go to that issue for discussions not specific to Chez.

**Comment by FrankHB** [comment]
@luke21923 Now Chibi has fixed the issue. FYI, Here is the reply of some remaining points from [yours](https://github.com/ashinn/chibi-scheme/issues/812#issuecomment-1036554753) not yet clarified there.

As said, this may better be settled down in WG2 list, as many of your points are about the design in the Scheme report, not just for any specific implementations.

> I assumed that you were proposing to make Chibi Scheme automatically convert the inexact arguments of `=`, `<`, `>`, `<=` and `>=` to exact numbers (with `exact`), when at least one of the arguments is exact. This is the behaviour of MIT Scheme, for instance.
> 

No. There are basically two choices: to note the specific implementation not respecting RnRS's `=` transitivity requirement; or, as you said here.

I'm not suggesting any of one in issues I opened. Let the maintainer choose.

> > However, for unary predicates like `zero?`, it should not follow the similar rules because it will be almost useless for inexact numbers if it does so. Since inexact numbers are actually allowed, better avoid such design. Instead, there are caveats to users about the accuracy issue. [...]
> 
False. It is quite legitimate to have objects initialized by values in source notation of inexact numbers with the fact of not being inexactness initially in mind, in particular when the user assumes they are likely implemented as flonums or floating-point numbers. Exact numbers do not help, because they may likely incur unnecessary internal conversions overhead with such implementations, either in read-only accesses or assignments.

This is like C:

```
double data[] =  {0.0, 42.0, 3.0, /*...*/ 0.0}; // Even without runtime overhead, changing 0.0 to 0 would not be a good idea to express the intent in general.
```

Such initialize value may include zeros. They may or may not be handled as input of operations having results cannot be exact. When they are not handled like this, the values may be unchanged, and `zero?` is useful to test this.

Conceptually it is `flzero?` without the requirement of the typecheck of flonums, hence more ad-hoc polymorphic. Given that the object in a container (list, vector, ...) may have different types in a latent-typed language, generic procedures are needed (for convenience) anyway.

> `zero?` and `=` are useless for inexact (IEEE 754 binary64) numbers. Exact equality comparison involving an inexact floating-point number does not make sense:

False. It is even more useful when the representation is assumed, since zeros can be represented in only 2 normalized bit patterns for such a format (quite different to NaNs), although the usefulness is not necessarily shown by treating them as numbers.

> 
> ```
> > (= 3 (/ 0.6 0.2))
> #f
> > (zero? (- 3 (/ 0.6 0.2)))
> #f
> ```
> 
> There is no point in trying to reverse that. Transitive or not, `zero?` and `=` (applied to inexact IEEE 754 binary64 arguments) are irrelevant. I really don't see how transitivity would make them useful again (except perhaps for the [argument](https://github.com/ashinn/chibi-scheme/issues/812#issuecomment-1034916585) about optimisation that you mentioned previously).
> 
In a concrete implementation, perhaps. In Scheme, generally no.

The key point of the issues I opened is not insisting on the usefulness of transitive (OTOH, as I've mentioned, to take the benefits of the transitive properties are possible but it looks like quite advanced techniques), but the guarantees based on the compliance.

Multiple major implementations disagree here, and it should be not difficult to find which indeed do not conform the written specification. The status is unfriendly to users having no resources to patch the affected implementations by themselves (including beginners).

To resolve the problem, either remove the requirement away from RnRS, or change the implementations to as RnRS. Or the third way... document as Racket having some support of RnRS, instead of be an implementation of RnRS. 

You can see this issue as a plea to request a specific implementation to resolve the problem in the second way. However, I don't say this is a must. Instead I see the requirement suspicious, esp. in the contexts of R6RS. I just believe other ways are even more infeasible in practice.

Doing nothing and keeping the status quo is worse than any choice above, for any implementations differ than RnRS's requirement and any users who will potentially take the portability of RnRS as granted (since the overall library portability guarantees are already quite weak, loose and confusingly "easy to implement" in some naive users' view, at least for R5RS and R7RS).

> The only comparison procedures that make sense when applied to one or more inexact (IEEE 754 binary64) arguments are `<`, `>`, `<=` and `>=`.
> 
This is probably true for math concerns, but not looking like an interesting solution. To distinguish them may likely introduce more problems. For instance, do you want to also change the requirement similarly on `char=?` and its friends?

> > The disagreement comes from the dilemma: when the behaviors conflict, and there are no math rules suggesting it definitely incorrect, which should be choosed for this?
> > Without considering the inpacts on the implementations, I choose the former. Generally, when implementing a pure function (without any side effects in the call), the range of the results of the procedure is a more significant property then how it constraints on the input.
> 
> I am not convinced by that. In fact I don't understand how it is connected to any benefit of making `=` and `<` transitive.
> 
There is no direct connection. The point here is to improve the ease of reasoning the language rules by users who are interested in the rationale of the design.

I have argued that, this approach is easier to learn. It is not that intuitive, but your approach is also not, either.

For a latent-typed language like Scheme, learners should always take care of the actual meaning of the procedure by reading the documented descriptions of the interface. A calling form is certainly not enough: it has too litter information of the procedure, if it has _ever_ exposed something beyond the calling syntax.

On the other hand, in languages with explicit type annotations, such requirements are ususally directly encoded as type signature of the interface. Once learners can read them correctly, they can take less care of the remaining specification of the interface. (I don't think this is necessarily good, though, mainly because the expressiveness here is _always_ limited by the concrete type system rules and users should still to see the remaining parts.)

Compared to type signatures, the rules implied in your approach are definitely too implicit. They don't require less effort of reading the specification of the procedures.

And in my approach, the part about predicates can be semi-formalized: "some procedures have function types in forms of `* -> boolean` and you should generally first try to take care of them regardless of `*`". This is not explicitly readable in the source language besides the `?` suffix, but the methodology behind are shared with the experience of languages having type signatures.

> I acknowledge that you are not convinced by the benefit of consistent conversion of arguments (for both `+` and `<`). I am not sure we will be able to agree on any of that.
> 
> > This interpretation also looks like intentional in R7RS: the second note in page 36 mentions `=` and `zero?` together to show how inaccuracy makes the results unreliable.
> 
> Let's look at that note:
> 
> ```
> Note: While it is not an error to compare inexact numbers
> using these predicates, the results are unreliable because a small
> inaccuracy can affect the result; this is especially true of = and
> zero?. When in doubt, consult a numerical analyst.
> ```
> 
> Yes, that note groups `zero?` and `=` together. That note says that comparison predicates applied to inexact numbers (presumably IEEE 754 floating-point numbers) are **unreliable**, and that this is **especially true** for `=` and `zero?`. It means that `=` and `zero?` are _especially unreliable_ when applied to inexact (IEEE 754 binary64) arguments. In other words, as I said before, they are useless. I acknowledge that `=` and `<` are predicates.

The note emphasizes that, if the user do not sure how to prevent the issues of inaccurate numerical result, the result should not be relied on. It does not mean this should be unconditionally cared about. Otherwise, why not make it an error (not required to be signaled)?

Some exceptional cases are:

- Non numerical values of the numbers are not inaccurate at all. Will you care inaccuracy of NaN?
- For interface conveying such possibility of non-numerical values, it is the user to choose whether accept the risks or not.
	- I've said I used to suppress GCC's `-Wfloat-equal`. One typical case is, when I am implementing `zero?` for a Scheme-like language, I should pretend the underlying floating-point operand is accurate and just ignore the warning. Otherwise, if I introduce something like machine epsilon, the semantic is wrongly changed. It should be the user of such features, not I, to make the decision to deal with the accuracy issues.
	- This method has further application in high level designs. RnRS's allowance of not signaling an error and C's undefined behavior are both typical examples of "delaying the decision to users" approach. This allows the language specifications formally portable in a broader sense, while not prevent potentially useful detailed designs at the cost of slightly less adoption (e.g. POSIX defines some C's undefined behaviors).

And in R6RS, the same note uses "may be". This is clearly showing the decision of reliability is up to the user, but not the interfaces. It just not so specific to numerical values.

> ### Refutation of the language-lawyer proof
> Now, let's talk about your arguments aimed at refuting my [language-lawyer proof](https://github.com/ashinn/chibi-scheme/issues/812#issuecomment-1035495818).
> 
> > > For instance, here is a violation of rule number 1 in Chibi Scheme:
> > > `> (= 9007199254740992.0 9007199254740993.0)`
> > > `#t`
> > 
> > 
> > Although the rule of equality is not very clear, it still allows the result, because, from R7RS:
> > > 6.2.4 ... It is important to distinguish between mathematical numbers,  the Scheme numbers that attempt to model them, the machine representations used to implement the Scheme numbers, and notations used to write numbers.
> > 
> > 
> > The rule of the equality relationship is defined mathematically on mathematical numbers, because by common sense, there are no other definitions not exposing the implementation details available (except comparing the written forms in the source, which is absurd).
> 
> This invalidates my proof. It is not obvious (at least to me), but the report defines the rules of `=` as being valid over "Scheme numbers", not over the _written form_ of the numbers in the source code. Two numbers in _written form_ designate the same "Scheme number" if the procedure `number->string` returns the same result with both numbers as argument.
> 
> For instance:
> 
> ```
> > (number->string 9007199254740992.0)
> "9007199254740992.0"
> > (number->string 9007199254740993.0)
> "9007199254740992.0"
> ```
> 
> Notwithstanding what the report says, I still consider the evaluation of `(= 9007199254740992.0 9007199254740993.0)` => `#t` to be erroneous.

Despite the mapping from the written forms to the Scheme numbers, the mapping from Scheme numbers to mathematical numbers are just not guaranteed one-to-one, so there is quite big room you have to tolarent the inaccuracy. For real numbers, basically there are uncountable infinite math numbers you can choose. `=` can't work as you expectation.

And this is practically required to allow floating-point numbers as the implementation. Most decimal numbers with finite digits don't have a mathematically equal representation in a binary floating-pointer number; you will requires infinite precision to get it accurate.

> ### Transitivity of `<`
> 
> `=` is useless on inexact finite-precision floating-point numbers, and, after all, I couldn't care less about what it returns (when applied to a mix of exact/inexact arguments). For the extremely rare cases _(floating-point bit twiddling)_ where I would want to test the raw equality on inexact finite-precision floating-point numbers, I can afford to encapsulate the arguments inside `inexact` forms.
> 
I don't think Scheme guarantees you can safely hacking into the representation of the numbers just by inexact procedures...

> What really matters is the behaviour of the other comparison procedures `<`, `>`, `>=` and `<=`. Do the transitivity of _those_ procedures is broken? I am trying to find three (exact and/or inexact) numbers **num1**, **num2** and **num3** such that:
> 
> `(< num1 num2)` => `#t` `(< num2 num3)` => `#t` `(< num1 num3)` => `#f`
> 
> or such that:
> 
> `(<= num1 num2)` => `#t` `(<= num2 num3)` => `#t` `(<= num1 num3)` => `#f`
> 
> But I didn't find any exemple so far.
> 
I believe they are allowed by RnRS. There are too few requirements about how inexact and how inaccurate an finite inexact can be.

But probably no Scheme implementations in practice use a format behave badly here.

At least with a format like any types specified in IEEE FP, an finite number being able represented exactly always has exact one value being encoded and the encoding scheme guarantees the order it is well-defined for each exact binary representation compared to those of other finite numbers.

This is quite cheap. All ordering can be implemented statically in primitive FP operations without runtime overhead in software.

Actually IEEE-754 requires `totalOrder` predicate reflecting the property. Note this is even exact for `=` over representable values of the format.

The possible unreliability comes from conversions and inexact operations, including the rounding thereof.

Unfortunately, only equality is sensitive to rounding loosing accuracy, but all ordered predicates are stable and same results survived in the same rounding mode (without [double rounding](https://en.wikipedia.org/wiki/Rounding#Double_rounding)).

Note strict ordering may suffer from this: `a < b < c` => `a = b = c`. But you will not observe them since `a < c` is also effectively `a = c` in this case.

The ordered comparison can be broken, when either condition is meet in the implementation:

- Different rounding modes are used for different comparisons.
- Different inexact number format with different precision used in different comparisons.
- The inexact number is not modeled by a single binary encoding scheme. For example, see [RnRK](https://ftp.cs.wpi.edu/pub/techreports/pdf/05-07.pdf), which is somewhat a derivation from R5RS about this topic. Such models allows inexact values having different precision natively.

> If the transitivity of `<` and friends is not broken, then one solution to be R7RS-small compliant without causing too much problems would be:
> 
>     1. To automatically convert the inexact arguments of `=` with the procedure `exact`, into exact numbers (when at least one initial argument is exact), and
> 
>     2. To leave  `<`, `>`, `>=` and `<=` alone (keep the current behaviour of converting exact arguments to inexact when there is a mix of exact/inexact arguments).
> 
> 
> This would introduce an unattractive discrepancy in the behaviours of the comparison procedures though.

While it can be broken in ways as discussed above, the difference treatment on ordered comparing and equality relying on concrete representations are implementation details. This is clearly intentional. From R7RS 6.2.1:

> Scheme's numerical operations treat numbers as abstract data, as independent of their representation as possible.

Both can be unreliable as per the current rules, even if you may observe unreliability only for `=` in practice.

**Comment by jltaylor-us** [comment]
@luke21923, Can you give me a test case showing how the current behavior of the strict inequalities is out of spec?  I.e., you say
```
> (> (+ (expt 2 53) 1) (inexact (expt 2 53))) ; error
#f
```
but how does this make the function non-transitive?  (We _may_ want to change the behavior for consistency, but my test case for operator transitivity is not flagging the current implementation as an error [and is flagging `=` and the inclusive inequalities].  Perhaps my test case is not imaginative enough.)

**Comment by luke21923** [comment]
Definition (derived from R6RS page 10): A *Number Object* is any Scheme object `obj` such that `(number? obj)` => `#t`. Note that the expressions `9007199254740992.0` and `9007199254740993.0` denote the same Number Object because the procedure `number->string` returns the same result when it is applied to these expressions.

I don't think the transitivity of `>` is currently broken. @FrankHB [suggested](https://github.com/cisco/ChezScheme/issues/606#issuecomment-1037052874) that not using always the same IEEE 754 rounding mode could break the transitivity of `>`.

However, I think that
 
    > (> (+ (expt 2 53) 1) (inexact (expt 2 53))) ; error
    #f

is out of spec, because R6RS (page 42) requires that the procedure `>` returns `#t` if its arguments are monotonically decreasing, and #f otherwise. This is required to hold for any arrangement of arguments that are Number Objects. In this exemple, the first argument is ` (+ (expt 2 53) 1)` and the second argument is `(inexact (expt 2 53))`.

    > (number->string (+ (expt 2 53) 1))
    "9007199254740993"
    > (number->string (inexact (expt 2 53)))
    "9.007199254740992e15"

These two arguments are monotonically decreasing, because, mathematically, the number "9007199254740993" is greater than the number "9.007199254740992e15".

Remark: I am just realising that

    > (= (+ (expt 2 53) 1) (inexact (expt 2 53))) ; error
    #t

does not only break the transitivity requirement, it also breaks the equality requirement of `=`.

Here is a unit test showing that your example produces an incorrect result:

    > (define a (+ (expt 2 53) 1))
    > a
    9007199254740993
    > (define b (inexact (expt 2 53)))
    > b
    9.007199254740992e15
    > (> (exact a) (exact b))
    #t
    > (> a b)
    #f

This is incorrect, because, even though `a` is mathematically greater `b`, the expression `(> a b)` evaluates to `#f`. This is a violation of an R6RS requirement regarding the procedure `>`. My understanding is that the procedure `>` must *simulate* the behaviour of converting all its arguments with `exact` before performing the comparison.

**Comment by jltaylor-us** [comment]
>  even though the Number Object `a` is mathematically greater than the Number Object `b`

Is it, though?

I think there is a fundamental disconnect about what it means to be an inexact number.  In an IEEE double-precision floating point representation (i.e., IEEE-754 binary64), the value `9.007199254740992e15` represents all mathematical (i.e., exact) values in the range `[9.0071992547409915e15,9.007199254740993e15]`.

The r6rs authors are smart guys; and they certainly had the opportunity to specify a behavior for mixed exact-inexact comparisons.  Instead, the spec is silent on the matter.  One reasonable interpretation is that, e.g., `(> a b)` means that for all possible mathematical values that a and be could represent, a > b.

In any case, if there is not a counterexample showing that the current behavior of the strict inequalities leads to non-transitivity then I'll take my patch to the other maintainers and see if we want to change the behavior of the strict inequalities just for code consistency.  If you disagree with the results then I suggest a separate issue (since this one is specifically about transitivity, as explicitly stated in the spec).

**Comment by luke21923** [comment]
Ok (I will not disagree with your decision).

Since Chez Scheme is almost already compliant with the interpretation of R6RS in which an inexact floating-point number represents only the exact number "sign * mantissa * 2^exponent", I thought this was the interpretation we were adhering to.

When you and the other maintainers consider changing the behaviour of the strict inequalitites just for code consistency, keep in mind the following perquisites of this consistency:
* Comparison operators could be used interchangeably. For instance, `(= a b)` could be replaced intuitively by a user with `(not (or (< a b) (> a b)))`. Or `(<= a b)` could be replaced with `(> b a)`.  Even though this is a mistake, given our current interpretation of R6RS, some users may think that those properties of interchangeability hold (because in their experience in writing code in the REPL, those properties were never broken).
* It would be easier to write tests. When exact integers behave inconsistently in the range [2^53, 2^60], we need to write test cases with integer arguments inside and outside that range. For instance, if we want to test thoroughly a function having two exact integers as arguments, we need to write test cases in which arg1 and arg2 are in [2^53, 2^60], then write test cases in which arg1 and arg2 are out of [2^53, 2^60], then write test cases in which arg1 is in [2^53, 2^60] and arg2 is out of [2^53, 2^60], then write test cases in which arg1 is out of [2^53, 2^60] and arg2 is in [2^53, 2^60].
* Also, If the users are told that "*`(> a b)` means that for all possible mathematical values that a and b could represent, a > b*", then they might expect (by consistency) that "*`(= a b)` means that for all possible mathematical values that a and b could represent, a = b*", and therefore they might expect that both `(= 9007199254740992.0 9007199254740992)` and `(= 9007199254740992.0 9007199254740993)` evaluate to `#f`.
