### ISSUE TITLE
load-shared-object has (no?) effect in library definition

### ISSUE THREAD

**Issue by ChaosEternal** [cisco/ChezScheme#61]
`
; the library code "linux/abc.ss"
(library (linux abc)
  (export getenv1)
  (import (chezscheme)
          (rnrs bytevectors))

  (define getenv1
    (foreign-procedure "getenv" (string) string)
    )

  (begin
    (load-shared-object "libc.so.6")) ;; seems putting load-shared-object here has no effect
)
`

the test code:
;; the test code
`
(import (linux abc))

(display (getenv1 "HOME"))

`
;; the error message:
Exception in foreign-procedure: no entry for "getenv" 

The behavior of Chez is (maybe) different to  r6rs :

http://www.r6rs.org/final/html/r6rs/r6rs-Z-H-10.html#node_sec_7.1

The <library body> is the library body, consisting of a sequence of definitions followed by a sequence of expressions. The definitions may be both for local (unexported) and exported bindings, and the expressions are initialization expressions to be evaluated for their effects.

**Comment by gwatt** [comment]
You'll need to move the `load-shared-object` call above any foreign-procedure definitions. I realize that r6rs requires library definitions to appear above arbitrary code, but thankfully you can do still do this:
```
(library (linux abc)
  (export getenv1)
  (import (chezscheme)
    (rnrs bytevectors))

  (define init
    (begin (load-shared-object "libc.so.6"))
    ; anything else you may need
  )

  (define getenv1
    (foreign-procedure "getenv" (string) string))
)
```

**Comment by michaellenaghan** [comment]
The relevant section is [4.2](http://cisco.github.io/ChezScheme/csug9.4/foreign.html#./foreign:h2):

> Two steps are necessary before foreign procedures can be invoked from Scheme. First, the foreign procedure must be compiled and loaded, either statically or dynamically, as described in Section [4.6](http://cisco.github.io/ChezScheme/csug9.4/foreign.html#g32). Then, access to the foreign procedure must be established in Scheme, as described in this section. Once access to a foreign procedure has been established it may be called as an ordinary Scheme procedure.

Your original approach (understandably!) reversed the two steps.

**Comment by ChaosEternal** [comment]
actually, i misunderstood r6rs

thanks !

**Comment by NalaGinrut** [comment]
Here's another method I've ever used.
You may define multiple libraries in a file, so you do this:
``` scheme
(library (init) (import) (export)
  (load-shared-object "xxx.so")
  '' do other related init work
  )

(library (your-module)
  (import (init) (chezscheme) (rnrs))
  (export ...)
  ;; put your definitions here
  )
```

This method is useful especially if you have record-type to be defined first.

**Comment by dybvig** [comment]
It seems like this issue is resolved, so I'm closing it.
