### ISSUE TITLE
Exception raised in the helper procedure `fixnum-floatable-wlop?` from the file s/5_3.ss

### ISSUE THREAD

**Issue by luke21923** [cisco/ChezScheme#612]
The helper procedure [`fixnum-floatable-wlop?`](https://github.com/cisco/ChezScheme/blob/73dcc9056f39a730d0a81ba39b8654629ab16791/s/5_3.ss#L668) raises an exception when [`(constant float-precision-bits)`](https://github.com/cisco/ChezScheme/blob/73dcc9056f39a730d0a81ba39b8654629ab16791/s/5_3.ss#L37) plus one is equal to [`(fixnum-width)`](https://scheme.com/tspl4/objects.html#./objects:s152).

    > (fixnum-width)
    61
    > (define float-precision-bits 60)
    > (define constant
        (lambda (x)
          x))
    > (constant float-precision-bits)
    60
    > (define fixnum-floatable-wlop?
        ;; floatable without loss of precision
        (lambda (x)
          (if (<= (fixnum-width) (constant float-precision-bits))
              #t
              (fx<= (- (expt 2 (constant float-precision-bits))) x (expt 2 (constant float-precision-bits))))))
    > (fixnum-floatable-wlop? 1)
    Exception in fx<=: 1152921504606846976 is not a fixnum
    Type (debug) to enter the debugger.

To fix this, the `fixnum-floatable-wlop?` procedure may be rewritten this way:
    
    (define fixnum-floatable-wlop?
      ;; floatable without loss of precision
      (lambda (x)
        (if (<= (- (fixnum-width) 1) (constant float-precision-bits))
            #t
            (fx<= (- (expt 2 (constant float-precision-bits))) x (expt 2 (constant float-precision-bits))))))

Explanation: the [width of a fixnum](https://scheme.com/tspl4/objects.html#./objects:h5) includes the sign bit, whereas the [width of the mantissa](https://en.wikipedia.org/wiki/Double-precision_floating-point_format#IEEE_754_double-precision_binary_floating-point_format:_binary64) of a floating-point number does not include the sign bit.

Context: I talked about this in the [pull request #611](https://github.com/cisco/ChezScheme/pull/611#issuecomment-1042921006).

**Comment by burgerrg** [comment]
Thanks for catching the edge case. This can also be remedied by reducing the upper bound by one. I will make this change and rename float-precision-bits to float-mantissa-bits for clarity.

**Comment by burgerrg** [comment]
Fixed in https://github.com/cisco/ChezScheme/commit/3a8467dbc200b853d8991e02ad8fd4667342099c. Thanks again!

**Comment by jltaylor-us** [comment]
Just so we're clear on this... This "edge case" does not exist on any platform supported by Chez scheme.  I highly doubt it there is any architecture anywhere (now or in the future) where it will exist.  This bug report says that an internal function will fail _under a condition that never happens_.
