### ISSUE TITLE
typos in TSPL4

### ISSUE THREAD

**Issue by ocyzl** [cisco/ChezScheme#617]
[Section 6.8. Strings](https://www.scheme.com/tspl4/objects.html#./objects:h8) says in the second paragraph:

> Any Unicode character may be inserted with the syntax <tt>#\x<i>n</i>;</tt>, where <tt><i>n</i></tt> consists of one or more hexadecimal digits and represents a valid Unicode scalar value.

Similarly, [Section 6.11. Symbols](https://www.scheme.com/tspl4/objects.html#./objects:h11) says in the third paragraph:

> These and any other Unicode character may appear anywhere within the printed representation of a symbol with the syntax <tt>#\x<i>n</i>;</tt>, where <tt><i>n</i></tt> consists of one or more hexadecimal digits and represents a valid Unicode scalar value.

I think the <tt>#</tt> doesn't belong there, in either case.  That is, to insert an arbitrary character within a string or symbol, the syntax to use is <tt>\x<i>n</i>;</tt>.  See [the formal grammar for strings](https://www.scheme.com/tspl4/grammar.html#grammar:strings) and [that for symbols](https://www.scheme.com/tspl4/grammar.html#grammar:symbols).

Also, the description of the [`symbol->string` procedure](https://www.scheme.com/tspl4/objects.html#./objects:s270) says:

> The string returned by `symbol->string` should be treated as immutable. Unpredictable behavior can result if a string passed to `string->symbol` is altered with `string-set!` or by any other means. 

I guess "a string passed to `string->symbol`" should instead be "a string returned from `symbol->string`".  The description of [`string->symbol`](https://www.scheme.com/tspl4/objects.html#./objects:s269) already said, "The effect of modifying a string after it is used as an argument to `string->symbol` is unspecified."

**Comment by dybvig** [comment]
Thanks for these corrections.  The online version of tspl4 at www.scheme.com and the errata page have been updated.
