### ISSUE TITLE
Make void take arguments

### ISSUE THREAD

**Issue by bjoli** [cisco/ChezScheme#62]
Hi there! 

I was porting some code from chicken recently, and noticed that the void procedure doesn't take any arguments. I think it would be a small and un-intrusive change, but one that could bring some utility. In chicken, I have sometimes done things like "(make-output-port void void)" to make a null port that just ignores any input.

I find it quite handy sometimes when prototyping to just have a procedure that just ignores any argument, like (define (ignore . args) (void)).

I don't know if this is the right forum for it, or if there are any philosophical aversions to it, but I thought I might as well ask.

Best regards
Linus

**Comment by jltaylor-us** [comment]
If the results are unimportant (i.e., not bound or examined) then you can use `values`.

**Comment by bjoli** [comment]
hah! I didn't think about that :)
