### ISSUE TITLE
"engine.ss" is broken and yielding nonsense results.

### ISSUE THREAD

**Issue by shenlebantongying** [cisco/ChezScheme#623]
The code below is copied verbatimly from

https://cisco.github.io/ChezScheme/csug9.5/control.html#./control:h4
or
https://www.scheme.com/tspl4/examples.html#./examples:h11

But resulting different results.

Left: book, Right: in current version of chez

![image](https://user-images.githubusercontent.com/20123683/165777231-3e4963ad-610d-490f-a374-ea525dc4cf64.png)

According to the documentation, the code will burn 1 "fuel". Thus, the resulting left over should be 9. The other code examples also resulting wrong results.

**Comment by burgerrg** [comment]
Section 6.4 of the user's guide states: "In the example above, the value is 3 and there are 9 ticks left over, i.e., it takes one unit of fuel to evaluate 3. (The fuel amounts given here are for illustration only. Your mileage may vary.)"

**Comment by burgerrg** [comment]
The number of timer ticks required for particular operations is not specified, so the exact counts for the examples can change across versions. The Fibonacci example in Section 6.4 works in 9.5.8 but burns a different amount of fuel (ticks).

**Comment by shenlebantongying** [comment]
Wait a second. The book assume all operation cost 1 seconds, thus will always result "nice" numbers.

My bad, I didn't fully understand the engine.

Thanks for your reminder!
