### ISSUE TITLE
Bug in char-

### ISSUE THREAD

**Issue by alewmoose** [cisco/ChezScheme#627]
```
;; should be -1
(char- #\a #\b) => 72057594037927935
```
I'm using Chez Scheme Version 9.5.8, machine type is ta6le

**Comment by akeep** [comment]
Thanks for the bug report!  It looks like we have a logical shift right where we needed an arithmetic one.  I have a fix, but I need to add some tests for `char-`.  Apparently we do not currently have any tests for this (at least that I can find)!
