### ISSUE TITLE
Is it possible to promote individual object into 'static generation?

### ISSUE THREAD

**Issue by lemvik** [cisco/ChezScheme#630]
Hi!

A question related to locking of objects and static generation of GC. The documentation for `locked-object?` states that it will return true if GC can no longer reclaim/move it. I'd like to have some objects be immovable (namely - some `foreign-callable` objects that represent callbacks to be retained in the C-land) and avoid the "heap fragmentation"/"storage manager overhead" mentioned in the `lock-object` docs. Semantically those objects are `'static` in the sense that they will be there for the whole duration of program execution. 

So, is there a way to somehow mark object as `'static` without calling GC with `'static` generation target? The reason why I'm hesitant to call the GC this way is that it might retain more much than what I want (I assume that _everything_ that is alive at the moment of such call will be promoted to `'static`, so I have to be really careful with the environment when doing so).

**Comment by jltaylor-us** [comment]
I don't think this is possible.

**Comment by lemvik** [comment]
Thank you for the detailed answer!
