### ISSUE TITLE
Blocking system calls via FFI can jam the chez runtime

### ISSUE THREAD

**Issue by ChrisVine** [cisco/ChezScheme#64]
I have some code at https://github.com/ChrisVine/chez-a-sync which is a port of guile-a-sync.  I have an issue which is that if a thread is blocking on a system call invoked via the FFI (in this case, poll()), the chez scheme storage manager (I think) jams if the program runs more than about 25 threads.

There are various cludges which can be used, such as running a regular timeout to keep the poll()/event loop thread unblocking regularly, but the problem seems to be that something (the storage manager?) requires every thread of execution to be making progress.  Is there any way around this or fix that could be employed?

**Comment by yjqww6** [comment]
I think it is similar to #58. Try Sdeactivate_thread and Sactivate_thread around blocking calls.

**Comment by akeep** [comment]
@yjqww6 is correct, Sactivate_thread and Sdeactivate_thread are the functions to take a look at.  There are a couple of good paragraphs about this with a description of how C threads interact with the storage manager in the [User's Guide](http://cisco.github.io/ChezScheme/csug9.4/foreign.html#./foreign:h8) near the end of section 4.8 C Library Routines, where the Sactivate_thread and Sdeactivate_thread routines are described.

**Comment by ChrisVine** [comment]
Ah excellent.  That does seem to do it, together will Slock_object()'ing a few bytevectors which poll() uses.

Thanks for the help.
