### ISSUE TITLE
syntax-case - One I can understand, readable in chibi-scheme  .

### ISSUE THREAD

**Issue by xingzheone** [cisco/ChezScheme#643]
dear  dybvig professor .   Sorry to bother you again. 
I basically understand Theoretical thought of Chez's syntax-case , But there is no original code, I'm still a little confused.
I found  https://github.com/ashinn/chibi-scheme  
Now I just want to get your confirmation Chez's original code(syntax-case) is similar to him. 

Here are some code snippets in chibi  (lib\chibi\syntax-case.scm)
https://github.com/ashinn/chibi-scheme/blob/master/lib/chibi/syntax-case.scm
```scheme
(define-syntax syntax-case
  (er-macro-transformer
   (lambda (expr rename compare)
     (let ((expr (cadr expr))
           (lit* (car (cddr expr)))
           (clause* (reverse (cdr (cddr expr))))
           (error #'(error "syntax error" e)))
       #`(let ((e #,expr))
           #,(if (null? clause*)
                 error
                 #`(let ((fail (lambda () #,error)))
                     #,(let loop ((clause (car clause*))
                                  (clause* (cdr clause*)))
                         (if (null? clause*)
                             (gen-clause lit* clause)
                             #`(let ((fail (lambda ()
                                             #,(gen-clause lit* clause))))
                                 #,(loop (car clause*) (cdr clause*))))))))))))
```

**Comment by gwatt** [comment]
syntax-case punts the pattern matching work to a procedure called `syntax-dispatch`, which I think is what you're looking for.
https://github.com/cisco/ChezScheme/blob/f19ae927a9011e033e4aea08eddad3241116d7d5/s/syntax.ss#L7314-L7336

You can see this a bit if you invoked the expander on a syntax-case expression:
```
> (expand '(syntax-case asdf ()
             [(_ a b c) #'(vector a b c)]
             [(_ a b) #'(+ a b)]))
(let ([#:tmp asdf])
  (let ([#:tmp (#3%$syntax-dispatch #:tmp '(_ any any any))])
    (if #:tmp
        (#3%apply
          (lambda (#:a #:b #:c)
            (#3%list '#<syntax vector> #:a #:b #:c))
          #:tmp)
        (let ([#:tmp (#3%$syntax-dispatch #:tmp '(_ any any))])
          (if #:tmp
              (#3%apply
                (lambda (#:a #:b) (#3%list '#<syntax +> #:a #:b))
                #:tmp)
              (#3%syntax-error #:tmp))))))
```

**Comment by lassik** [comment]
I'm far from an expert, but psyntax may be easier to understand since it's a self-contained library: https://web.archive.org/web/20220107023625/http://ikarus-scheme.org/r6rs-libraries/index.html

See also https://www.unsyntax.org/

**Comment by xingzheone** [comment]
tks @lassik  ,   For later beginners, let's wait for a certain expert @dybvig . 
 
I have got the answer I want from Chibi scheme . (It makes me more comfortable with Chez scheme)
https://srfi.schemers.org/srfi-149/srfi-149.html
