### ISSUE TITLE
chez.scheme.org

### ISSUE THREAD

**Issue by lassik** [cisco/ChezScheme#644]
We're slowly working on setting up a website at Scheme.org. Part of the project is giving subdomains to Scheme implementations. Most of the major ones now have one: https://mit.scheme.org/, https://gambit.scheme.org/, https://bigloo.scheme.org/, etc.

With the permission of the Chez Scheme maintainers, we'd like to add `chez.scheme.org` redirecting to a URL or DNS CNAME of your choice. Scheme.org's registrant stipulates that the domain be non-commercial, so perhaps the open source site at https://cisco.github.io/ChezScheme/ would be a good target.

**Comment by burgerrg** [comment]
Thanks for asking us about making chez.scheme.org point to https://cisco.github.io/ChezScheme/. We think it's a great idea! You have our permission. -Bob for the Chez Scheme maintainers

**Comment by lassik** [comment]
Thank you very much. The redirect is now live: https://chez.scheme.org/
