### ISSUE TITLE
Disassembly

### ISSUE THREAD

**Issue by ghost** [cisco/ChezScheme#669]
I have what I hope is a simple question.  Is there some equivalent in Chez to the "disassemble" function in Common Lisp?  It displays the assembly language code for a compiled function.  Thank you.

**Comment by burgerrg** [comment]
No. You can get the source information for a procedure like this:
```scheme
(define (procedure-source x)
  (let ([src (((inspect/object x) 'code) 'source)])
    (and src (src 'value))))
```

Setting `(#%$assembly-output #t)` will cause the compiler to display the assembly output at compile time.
