### ISSUE TITLE
Feature request: add situation `test` to `eval-when`

### ISSUE THREAD

**Issue by ceving** [cisco/ChezScheme#677]
I prefer having the unit tests right next to the definitions in the same source file. This makes it necessary to selectively enable them, because they should only be evaluated, when the code gets tested, but not when the code is running in production.

Right now I hijack the `compile` situation for my unit tests. But I think it would be cleaner to have a dedicated situation for this. Ideally this new situation can be enabled by a command line option.

**Comment by mnieper** [comment]
There is the `meta-cond` special form. You can use this to enable and disable parts of your code selectively.
