### ISSUE TITLE
Feature request: create an Arm64 target

### ISSUE THREAD

**Issue by chriszyx** [cisco/ChezScheme#678]
There’s a target ‘arm32le’ but none for arm64.

My C isn’t good enough to unscramble pointer to int cast size issues :-(

If adding a 64-bit ARM (Linux) target were just a case of modifying a Makefile, well - that would be appreciated.

**Comment by steelhopper** [comment]
已收到

**Comment by melted** [comment]
There is a pull request for Mac ARM64 support https://github.com/cisco/ChezScheme/pull/607. But it's marked as a draft.

Note that Racket's Chez Scheme already has ARM64 support, so if you want it now you can build that. The binaries they distribute do not contain a standalone Chez executable, but they are built when building it from source.

**Comment by lassik** [comment]
Is Petite architecture-independent enough to run on aarch64? If so, how does one build only Petite?

**Comment by maoif** [comment]
It's done, check my [repo](https://github.com/maoif/ChezScheme). The machine type is `aarch64le` and `taarch64le` for threaded version.

Just pull the main branch on your aarch64 machine and run:

```
./configure -m=aarch64le --disable-x11 --installprefix=<your/path>
make install -j8
```

Make sure you use `--disable-x11` since it's not supported.

**Comment by chenrui333** [comment]
Can you cut off a new release per this issue close?

relates to https://github.com/Homebrew/homebrew-core/pull/152760

**Comment by burgerrg** [comment]
Yes, the next release will include this support.
