### ISSUE TITLE
The documentation of statistics and related functions is out of date.

### ISSUE THREAD

**Issue by burgerrg** [cisco/ChezScheme#68]
http://cisco.github.io/ChezScheme/csug9.4/system.html#./system:s204

The times are no longer milliseconds but time records.

**Comment by dybvig** [comment]
Indeed.  In fact, there were more substantial changes, which somehow escaped mention in the release notes.  I've rectified that and updated system.stex.

**Comment by burgerrg** [comment]
Thanks! I updated the web pages and PDF.
