### ISSUE TITLE
Any chance of resurrecting the OS X / PowerPC code?

### ISSUE THREAD

**Issue by cellularmitosis** [cisco/ChezScheme#680]
Hello,

I work on a "retrocomputing" [package manager](https://github.com/cellularmitosis/leopard.sh) for old PowerPC Macs, to which I just added the last versions of "petite" Chez which supported OS X / PowerPC (7.4 for Tiger, 8.4 for Leopard).

Though I'd guess the code required for that support has long since been removed from the latest Chez, now that Chez is open source, I was curious if it might be possible to resurrect that code?  Would anyone even have access to the 7.4 and 8.4 codebases?

Thanks in advance!

**Comment by jltaylor-us** [comment]
I'm sure _someone_ has it lying around, but it wasn't part of the open source release.  The [Racket fork](https://github.com/racket/ChezScheme) claims support for OSX PPC32, so once we merge that back in to Chez (...eventually) there will be support again - for some definition of "support".  I imagine part of that merge process is going to be distinguishing between the platforms that are really supported and those with "community support" (or whatever the nice way is to say "we think it probably works but if anything goes wrong you're on your own").

**Comment by cellularmitosis** [comment]
Oh fantastic, I didn't know about that fork!

**Comment by cellularmitosis** [comment]
It works!  [Added as a package](https://github.com/cellularmitosis/leopard.sh/commit/4f089102b93e4a3dd1241c31ca960e6690121400).

![chez-imacg3](https://user-images.githubusercontent.com/223396/217160745-09b040ce-3a3d-4a0a-a0b5-1d81adb32374.png)
