### ISSUE TITLE
Is it a bug?

### ISSUE THREAD

**Issue by aarwoo** [cisco/ChezScheme#688]
![image](https://user-images.githubusercontent.com/51515401/227733221-763aede9-d728-44a5-9cc5-19a5c7f98f4d.png)

**Comment by soegaard** [comment]
No. 

```
(lambda y f 'x)
```

evaluates to a function with a variable number of arguments.
When it is called, the variable `y` is bound to the list of actual arguments.
The body of the functions is `(begin f 'x) which is equivalent to just `'x`

**Comment by aarwoo** [comment]
Thanks.
