### ISSUE TITLE
How to generate arbitrary machine code?

### ISSUE THREAD

**Issue by Saigut** [cisco/ChezScheme#705]
We know that Chez Scheme compiles code from text filnally to machine code.
So I wonder if Chez Scheme can generate arbitrary machine code that I desire.
For example, can Chez Scheme generate x86 machine code like the following assembly code? If so, how to achieve it?  

```assembly
[BITS 16]
[ORG 0x7C00]

        cli
        mov     ax, 0x07C0
        mov     ds, ax
        mov     es, ax
        mov     fs, ax
        mov     gs, ax

        mov     ax, 0x0000
        mov     ss, ax
        mov     sp, 0xFFFF
        sti

        mov     si, msgHello
        call    DisplayMessage
        mov     si, msgEnd
        call    DisplayMessage
        hlt

DisplayMessage:
        lodsb
        or      al, al
        jz      .DONE
        mov     ah, 0x0E
        mov     bh, 0x00
        mov     bl, 0x07
        int     0x10
        jmp     DisplayMessage
     .DONE:
        ret          
          
msgHello  db 0x0D, 0x0A, "Hello World", 0x0D, 0x0A, 0x00          
msgEnd  db 0x0D, 0x0A, "That's all folks!!!", 0x0D, 0x0A, 0x00           
          
        TIMES 510-($-$$) DB 0
        DW 0xAA55
```

Also, is it possible for Chez Scheme to support inline assembly similar to C language?

```c
void print_char(char c)
{
    __asm__ __volatile__ (
            "mov $0x0e, %%ah\n"
            "mov $0x00, %%bh\n"
            "mov $0x07, %%bl\n"
            "mov %0, %%al\n"
            "int $0x10\n"
            :
            : "r" (c)
            : "%ah", "%bh", "%bl"
            );
}
```

**Comment by maoif** [comment]
Given a piece of code, ChezScheme first macro-expands that, then probably optimizes that (`cp0`) , then hands the code to the compiler (`cpnanopass`). The compiler transforms the code through a series of passes and finally generates machine code for supported architectures.

Therefore, the machine code generated is highly dependent on the Scheme source code and is mostly peculiar to Scheme semantics. AFAIK, there's no way to generate *arbitrary* machine code. Also, ChezScheme does not support inline asm.

But you can write inline asm in C and use FFI to call the functions.

See [here](https://gitlab.com/weinholt/machine-code) if you want to use Scheme to generate machine code, though the functionality is limited.

**Comment by amirouche** [comment]
> I wonder if Chez Scheme can generate arbitrary machine code that I desire.

Like @maoif describe it is possible to produce an elf binary using a c compiler, or using scheme; then with proper naming it should be possible to use foreign procedures using `load-shared-object` et al. That is using C calling convention. That is some sort of `(assembly->procedure ...)`. 

I wonder whether it is possible to avoid the c calling convention?

**Comment by Saigut** [comment]
Not having support for inline assembly is indeed a bit of a pity. I was originally wanting a 'Scheme machine' implemented by only Scheme. 
From the current perspective, using a combination of C and Scheme code should be enough for implementing a Scheme machine.

**Comment by Saigut** [comment]
> > I wonder if Chez Scheme can generate arbitrary machine code that I desire.
> 
> Like @maoif describe it is possible to produce an elf binary using a c compiler, or using scheme; then with proper naming it should be possible to use foreign procedures using `load-shared-object` et al. That is using C calling convention. That is some sort of `(assembly->procedure ...)`.
> 
> I wonder whether it is possible to avoid the c calling convention?

I agree the idea of `(assembly->procedure ...)`, it's may the right way to achieve inline asm.
And I think `c calling convention` is ok, because we can wrap a  asm function like 'void func(void)', in that case the parameter and the return value are not the matter.

**Comment by Saigut** [comment]
I noticed the `asm-module` ([x86](https://github.com/cisco/ChezScheme/blob/8c5f5cc27cf8f2b432aafc4f2fc640435294b74a/s/x86.ss#L935), [arm32](https://github.com/cisco/ChezScheme/blob/8c5f5cc27cf8f2b432aafc4f2fc640435294b74a/s/arm32.ss#L893)) in Chez Scheme, this should be the abstraction and wrap for assembly across different cpu arch.
`asm-module` may be a good way to implement the inline asm of Scheme.

**Comment by amirouche** [comment]
I pushed a demo at https://github.com/letloop/cli/commit/a59360ebd36ca755036ccdb11fecf59c27cf1e34.

Tho, we need to figure what are the use-cases. I have an idea to go beyond [manual jit](https://m00natic.github.io/lisp/manual-jit.html), as on-the-fly runtime optimization based on runtime statistics. 

If the goal is tape into say simd instructions, it is not necessary to have a procedure like `assembly->procedure`.

NB: Fibonacci implemented in assembly is almost 200 times faster than Scheme with -O0.

**Comment by Saigut** [comment]
> I pushed a demo at [letloop/cli@a59360e](https://github.com/letloop/cli/commit/a59360ebd36ca755036ccdb11fecf59c27cf1e34).
> 
> Tho, we need to figure what are the use-cases. I have an idea to go beyond [manual jit](https://m00natic.github.io/lisp/manual-jit.html), as on-the-fly runtime optimization based on runtime statistics.
> 
> If the goal is tape into say simd instructions, it is not necessary to have a procedure like `assembly->procedure`.
> 
> NB: Fibonacci implemented in assembly is almost 200 times faster than Scheme with -O0.

I want to write MBR program (for boot OS) using Scheme, if it can be achieved, there is the hope to built the Scheme OS which not depend on C. A Scheme OS just by Scheme, with several nesessary machine or asm code.
The challenges I think inlude:
* Compiling Scheme code to machine code, and which can be execute by cpu deirectly.
* The mentioned machine code can call the Scheme peocedure.
* In Scheme peocedure, it can call bios interrupts via inline asm (which you tried)

**Comment by amirouche** [comment]
Then disregard my previous comments they are unrelated to your goal.

**Comment by ufo5260987423** [comment]
> > I pushed a demo at [letloop/cli@a59360e](https://github.com/letloop/cli/commit/a59360ebd36ca755036ccdb11fecf59c27cf1e34).
> > Tho, we need to figure what are the use-cases. I have an idea to go beyond [manual jit](https://m00natic.github.io/lisp/manual-jit.html), as on-the-fly runtime optimization based on runtime statistics.
> > If the goal is tape into say simd instructions, it is not necessary to have a procedure like `assembly->procedure`.
> > NB: Fibonacci implemented in assembly is almost 200 times faster than Scheme with -O0.
> 
> I want to write MBR program (for booting OS) using Scheme, if it can be achieved, there is the hope to build the Scheme OS which do not depend on C. A Scheme OS just by Scheme, with several necessary machine or asm code. The challenges I think inlude:
> 
>     * Compiling Scheme code to machine code, and which can be executed by cpu deirectly.
> 
>     * The mentioned machine code above can call the Scheme procedure.
> 
>     * In Scheme peocedure, it can call bios interrupts via inline asm (which you tried)

So, you're making a lisp machine? I recommend  you [this work](http://www.aviduratas.de/lisp/lispmfpga/index.html) and [this work](https://icfp20.sigplan.org/details/scheme-2020-papers/3/Running-Scheme-On-Bare-Metal-Experience-Report-).

**Comment by maoif** [comment]
> > I pushed a demo at [letloop/cli@a59360e](https://github.com/letloop/cli/commit/a59360ebd36ca755036ccdb11fecf59c27cf1e34).
> > Tho, we need to figure what are the use-cases. I have an idea to go beyond [manual jit](https://m00natic.github.io/lisp/manual-jit.html), as on-the-fly runtime optimization based on runtime statistics.
> > If the goal is tape into say simd instructions, it is not necessary to have a procedure like `assembly->procedure`.
> > NB: Fibonacci implemented in assembly is almost 200 times faster than Scheme with -O0.
> 
> I want to write MBR program (for booting OS) using Scheme, if it can be achieved, there is the hope to build the Scheme OS which do not depend on C. A Scheme OS just by Scheme, with several necessary machine or asm code. The challenges I think inlude:
> 
>     * Compiling Scheme code to machine code, and which can be executed by cpu deirectly.
> 
>     * The mentioned machine code above can call the Scheme procedure.
> 
>     * In Scheme peocedure, it can call bios interrupts via inline asm (which you tried)

Perhaps you can look at [loko scheme](https://gitlab.com/weinholt/loko).

Loko is entirely written in Scheme and can be bootstrapped by Chez.

It can run on on Linux and on bare metal, though currently only on x86_64. It uses the library I mentioned above, [machine-code](https://gitlab.com/weinholt/machine-code) to write assembly directly and being without libc, invokes syscalls directly (see [this file](https://gitlab.com/weinholt/loko/-/blob/master/arch/amd64/linux-syscalls.sls) and [this file](https://gitlab.com/weinholt/loko/-/blob/master/arch/amd64/linux-numbers.sls)).

The bare metal support are mostly implemented in those files starting with `pc` [here](https://gitlab.com/weinholt/loko/-/tree/master/arch/amd64). e.g., [interrupt handling](https://gitlab.com/weinholt/loko/-/blob/master/arch/amd64/pc-interrupts.sls) and [page table operations](https://gitlab.com/weinholt/loko/-/blob/master/arch/amd64/pc-paging.sls)

The GC is also implemented in assembly...which I think needs to be reworked on a higher level.

**Comment by Saigut** [comment]
@ufo5260987423 @maoif Thank for your references.

**Comment by mbakhterev** [comment]
On Tue, Jul 11, 2023 at 01:30:41AM -0700, Amir wrote:
> I pushed a demo at https://github.com/letloop/cli/commit/a59360ebd36ca755036ccdb11fecf59c27cf1e34.
> 
> Tho, we need to figure what are the use-cases. I have an idea to go beyond [manual jit](https://m00natic.github.io/lisp/manual-jit.html), as on-the-fly runtime optimization based on runtime statistics. 
> 
> If the goal is tape into say simd instructions, it is not necessary to have a procedure like `assembly->procedure`.
> 
> NB: Fibonacci implemented in assembly is almost 200 times faster than Scheme with -O0.
> 

It is because the Scheme version has exponential time complexity, but the
assembly one is linear. Equivalent Scheme version should be kind of

`(define (fib n) (let lp ((a 0) (b 1) (n n)) (if (< n 1) a (lp b (+ a b) (1- n)))))`
