### ISSUE TITLE
ftype-set! example in CSUG seems to have regressed

### ISSUE THREAD

**Issue by jeffhhk** [cisco/ChezScheme#707]
I am consolidating fragments across a few pages, so I could be misreading what was intended.  Code is identical in CSUG 9.4 and 9.5.

Tested on 9.5 official binaries, and 9.5.8 build from source:

    ;; 4.5. Foreign Data
    (import (chezscheme))
    (define-ftype B
      (struct
       [b1 integer-32]
       [b2 (array 10 integer-32)]))
    (define b
      (make-ftype-pointer B
		          (foreign-alloc
		           (* (ftype-sizeof B) 3))))
    (ftype-set! (b1) b 5)
    ;; => Exception: invalid syntax (ftype-set! (b1) b 5)

**Comment by burgerrg** [comment]
The last line should be:
`(ftype-set! B (b1) b 5)`

See https://cisco.github.io/ChezScheme/csug9.5/foreign.html#./foreign:s152 for a description of `ftype-set!`.

**Comment by jeffhhk** [comment]
Ah, indeed.  My bad.

**Comment by jeffhhk** [comment]
Thanks!
