### ISSUE TITLE
Does the latest version of the program support computers installed on macbook m1/m2 chips?

### ISSUE THREAD

**Issue by luomgf** [cisco/ChezScheme#712]
Does the latest version of the program support computers installed on macbook m1/m2 chips?

**Comment by jltaylor-us** [comment]
The binaries for the `a6osx` and `ta6osx` machine types run fine under Rosetta2.  Building those on an M-series mac requires running the build under Rosetta2 as well.  The easiest way to do that is launch a shell in x86 mode and all of its child process will inherit that as the preferred architecture: `/usr/bin/arch -x86_64 /bin/bash -l`

The [Racket fork](https://github.com/racket/ChezScheme) of Chez Scheme has native arm64 support.  That will get merged in... eventually.. for the next major release of Chez Scheme.

**Comment by burgerrg** [comment]
Now there is native support for ARM64 Macs.
