### ISSUE TITLE
malloc/foreign-free and foreign-alloc/free

### ISSUE THREAD

**Issue by bjornkihlberg** [cisco/ChezScheme#718]
Can `foreign-free` in **Chez Scheme** free memory allocated in **C++** with `malloc` and can `free` in **C++** free memory allocated with `foreign-alloc` in **Chez Scheme** or are the different systems maintaining their own list of allocated memory such that responsibility of the memory can't be transferred between them?

// Regards
Björn Kihlberg

**Comment by jltaylor-us** [comment]
`foreign-alloc` and `foreign-free` [call](https://github.com/cisco/ChezScheme/blob/e0ca8bdca008ddae518cfbbcbd54814507ed455b/s/record.ss#L48-L59) foreign procedures [`s_malloc` and `s_free`](https://github.com/cisco/ChezScheme/blob/e0ca8bdca008ddae518cfbbcbd54814507ed455b/c/prim5.c#L1844-L1859), which in turn call `malloc` and `free` from the C library.  Whether the **C++** functions `std::malloc` and `std::free` use the same **C** library functions is a different question, but I assume all major implementations do even if it's not technically _required_ by the C++ standard.

Of course, this is not a  _documented_ behavior of Chez Scheme, so theoretically it could change in the future...  but I would find that very surprising.

**Comment by bjornkihlberg** [comment]
Thank you for the answer! This helps me understand what is going on under the hood.
