### ISSUE TITLE
Is it possible to reload shared object without restarting REPL?

### ISSUE THREAD

**Issue by mbakhterev** [cisco/ChezScheme#719]
Greetings. I am using Chez Scheme to work with expensive and fragile scientific equipment to script experiments. It is undesirable to run the device through initialization/shutdown cycles. The ability to keep the device operational while developing code is great benefit of using Chez REPL. Other languages with simple FFI are just not as flexible. So, first of all, thank you, Chez developers, for the great tool!

But i've an issue. Updating Scheme code works just fine. But there is module with computation intensive C-code. It is compiled as shared library and is loaded with `load-shared-object` procedure. The problem is that it is loaded once, and it is not reloaded when i update the code and load it again with `load-shared-object`.

For example. I have initially the following test.c

```
extern int test(void) { return 1; }
```

and the following test.scm

```
(library (test)
         (export test)
         (import (chezscheme))
  (define *cam* (begin (display "invoked\n")
                       (load-shared-object "./test.so")))

  (define test (foreign-procedure "test" () int)))
```

And i have the following REPL session

```
> (load "test.scm")
> (invoke-library '(test))
invoked
> (import (test))
> (test)
1
```

Then i change test.c

```
extern int test(void) { return 2; }
```

recompile it

```
gcc -fPIC -shared -o test.so test.c
```

And continue the REPL session

```
> (load "test.scm")
> (invoke-library '(test))
invoked
> (test)
Exception: compiled program requires a different compilation instance of (test) from the one previously compiled
Type (debug) to enter the debugger.
> (import (test))
> (test)
1
```

It looks like test.so was not reloaded. Are there any ways to reload shared object without restarting REPL?

- Respectfully, Mike.

**Comment by burgerrg** [comment]
Another option would be to use a different name for each revision of the shared object. E.g., (load-shared-object "./test-v1.0.so")

**Comment by mbakhterev** [comment]
@burgerrg huge thank!

**Comment by mbakhterev** [comment]
> Another option would be to use a different name for each revision of the shared object. E.g., (load-shared-object "./test-v1.0.so")

This works well enough. Thank you very much.
