### ISSUE TITLE
Bug: Exception Generated When Using (import (library (for fun))) in Chez Scheme

### ISSUE THREAD

**Issue by kilesduli** [cisco/ChezScheme#723]
In both tspl4 and r6rs, it is mentioned that import-reference can take one of the following two forms:
```
  <import reference> ->
    <library reference>
    (library <library reference>)
```
However, when defining a library named `(for fun)` and importing it using `(import (library (for fun)))`, an exception is thrown:
`Exception: invalid library reference (library (for fun))`

Upon inspecting the source code, it was discovered that in https://github.com/cisco/ChezScheme/blob/e0ca8bdca008ddae518cfbbcbd54814507ed455b/s/syntax.ss#L4252-L4255

The `(sym-kwd? ?library-reference library-reference)` check is using the keyword `library-reference`. After replacing `library` with `library-reference`, `(import (library-reference (for foo)))` can be successfully imported without throwing an exception. I believe this is a simple keyword error.

**Comment by jltaylor-us** [comment]
Thanks for the detailed report!
