### ISSUE TITLE
Possible bug of the `syntax-case` pattern matcher?

### ISSUE THREAD

**Issue by Jarhmander** [cisco/ChezScheme#727]
An "ellipsised" pattern in a `syntax-case` clause matches 0 or more of the corresponding pattern.

For example, the pattern `(_ ...)` matches any proper list. Moreover, the pattern `(l ... . r)` matches not only proper and improper lists, in fact it matches anything: if the `expr` is not a list, then `l` matches the empty list and `r` matches the entire expression. It makes sense: a `syntax-case` clause `((l ... . r) (append #'(l ...) #'r))` will match anything and reconstruct the original expression.

However, if the "ellipsised" subpattern is more complicated, then it may fail to match, even though there is some possible way to match the subject.

These cases work:
```
(syntax-case '() () [((l) ... . r) (append #'((l) ...) #'r)])
=> ()
(syntax-case "hey" () [((l) ... . r) (append #'((l) ...) #'r)])
=> "hey"
(syntax-case  '((foo)) () [((l) ... . r) (append #'((l) ...) #'r)])
=> ((foo))
(syntax-case  '((foo) . 42) () [((l) ... . r) (append #'((l) ...) #'r)])
=> ((foo) . 42)
(syntax-case  '((foo) . #(42)) () [((l) ... . r) (append #'((l) ...) #'r)])
=> ((foo) . #(42))
```

However, this does not:
```
(syntax-case  '((foo) . (42)) () [((l) ... . r) (append #'((l) ...) #'r)])
=> <syntax violation>
```

However, the pattern would read, "accept any list of lists of one element, then match any cdr at the end", and the last example could have `((l) ...) := ((foo))` and `r := (42 . ())` as a solution, but `syntax-case` fails to give this result. It's as though the pattern matching machinery greedily matches "ellipsised" patterns: during list traversal, if a cdr is a pair, then it must match the "ellipsised" subpattern, otherwise the entire match fails.

Is this the normal behavior of `syntax-case`?

**Comment by akeep** [comment]
Yes, this is expected because the `((foo) . (42))` is the proper list: `((foo) 42)`, as a result the `((l) ...` pattern attempts to consume it greedily, and does consume the `(foo)` entry, but because `42` does not match the pattern `(l)` it fails to match the pattern. There is no back-tracking in `syntax-case` pattern matching, so it simply fails.

It is still possible to match something like that, though it is a bit more work:
```
> (let ()
    (define match-clause
      (lambda (clauses remainder)
        (syntax-case clauses ()
          [((l) . r) (cons #'(l) (match-clause #'r remainder))]
          [r (cons #'r remainder)])))
   (syntax-case '((foo) . (42)) ()
     [(clause ... . remainder) (match-clause #'(clause ...) #'remainder)]))
((foo) (42))
```

**Comment by Jarhmander** [comment]
Thank you for the reply.

I think I have found it in the R6RS "specs" (emphasis mine):

> More formally, an input form F matches a pattern P if and only if one of the following holds:
> ...
>   - P is of the form (P1 ... Pk Pe <ellipsis> Pm+1 ... Pn . Px), where <ellipsis> is the identifier ... and F is a list or improper list of n elements whose first k elements match P1 through Pk, whose next m−k elements each match Pe, whose next n−m elements match Pm+1 through Pn, and whose nth and **final** cdr matches Px.

I had trouble understanding parts of the rules because the ellipsis was used to describe a range of items instead of denoting that the preceding item is present 0 or more times. But if `k = 1` and `n = m+1` then that description matches the patterns I was using.
