### ISSUE TITLE
the links to chez libraries and files at https://get.scheme.org/chezscheme/ are 404

### ISSUE THREAD

**Issue by spdegabrielle** [cisco/ChezScheme#729]
Hi, 

the links to chez **libraries** and **files** at https://get.scheme.org/chezscheme/ are 404

<img width="761" alt="image" src="https://github.com/cisco/ChezScheme/assets/108047/4fd3805e-6778-43fa-b9e5-8c059aefc134">

**Comment by jltaylor-us** [comment]
We do not control the contents of get.scheme.org (or any of the other scheme.org subdomains, except insofar as chez.scheme.org redirects to something we do control).  The maintainer of get.scheme.org [appears to be](https://github.com/schemeorg/schemeorg/blob/5d5f2c5545a8de87f5cae794f81db0dcbe30a749/projects.scm#L213-L217) Lassi Kortela.

**Comment by spdegabrielle** [comment]
thanks 
raised via schemeorg mailing list at https://srfi-email.schemers.org/schemeorg/msg/23523348/
