### ISSUE TITLE
arity of procedures

### ISSUE THREAD

**Issue by fedeinthemix** [cisco/ChezScheme#74]
Is there a way to obtain the arity of procedures? I've tried with, e.g,
(((inspect/object proc) 'code) 'source)
but it returns #f for build-in procedures such as 'car', '+', ...

I've tried changing the line 'i = f' to 'i = t' in 'Mf-base' before compiling Chez, but it doesn't seem to have any effect on this.

**Comment by dybvig** [comment]
No, short of disassembling the code that dispatches on argument count.
