### ISSUE TITLE
c/build.zuo should call s/update-revision

### ISSUE THREAD

**Issue by burgerrg** [cisco/ChezScheme#747]
The revision file currently generated does not include the second line. Moreover, it fails to work properly if .git is removed. The s/update-revision script is designed to update itself when exported to an archive file. This update will work when .git is removed.

**Comment by mflatt** [comment]
It would be good to call `s/update-revision` in some way that works at a vanilla Windows command prompt. The current Zuo script assumes that a ".git" means that `git` can be expected in the path, so maybe a `bash` associated with `git` can be used?

**Comment by burgerrg** [comment]
Thanks, I had not considered the vanilla Windows case. Perhaps we need a s/update-revision.bat to be used on Windows?

**Comment by burgerrg** [comment]
Another option is to use the same trick in c/build.zuo that s/update-revision uses, which is to place it in .gitattributes with an export-subst. Let me try that.

**Comment by burgerrg** [comment]
Matthew, removing s/update-revision and putting the logic into c/build.zuo seemed to work well. Please see what you think: https://github.com/cisco/ChezScheme/pull/748
