### ISSUE TITLE
the collector mutex recursively locked

### ISSUE THREAD

**Issue by yjqww6** [cisco/ChezScheme#76]
I have 3 thread in repl, the first is the main thread waiting for my input, the second does some memory consuming work, and the third calls a eventloop in C via foreign-procedure without deactivating and reactivating thread, and go back into scheme world via foreign-callable to sleep for 10ms per 20ms.

But sometimes I get the following error :
Exception in condition-wait: mutex 356495584 is recursively locked

I check the code and it seems only the  $collect-rendezvous in 7.ss has invoked this function.

**Comment by yjqww6** [comment]
I guess I know what happened. The problem has disappeared after I added 'volatile' specifier to the fields 'owner' and 'count' of 'scheme_mutex_t' in 'types.h' and recompiled chez scheme.

**Comment by burgerrg** [comment]
Good, I'm glad [this fix](https://github.com/cisco/ChezScheme/commit/0a6a1e14e7ecb9e39fa7a10a8584ed2fec24cbf4) also resolved this issue.
