### ISSUE TITLE
When will be the next release?

### ISSUE THREAD

**Issue by ncihnegn** [cisco/ChezScheme#788]
Waiting for one that supports Apple Silicon.

**Comment by amirouche** [comment]
It is simple to build from source, look into https://github.com/cisco/ChezScheme/blob/main/BUILDING. I am using the following on Linux at this time:

```
    git clone --filter=blob:none --depth=1 https://github.com/cisco/ChezScheme/
    ./configure --threads --disable-x11 --disable-curses --installprefix=$PREFIX > /dev/null
    make -j $(nproc) > /dev/null
    make install > /dev/null
```

Then `$PREFIX/bin` must be in `$PATH`. I do not remember the exact steps necessary to build it on macos, I remember it can be done.

**Comment by ncihnegn** [comment]
Thanks. I can build from source, but I need a release for packaging purpose.

**Comment by burgerrg** [comment]
Today Chez Scheme Version 10.0.0 was released!
