### ISSUE TITLE
backtracing

### ISSUE THREAD

**Issue by ovenpasta** [cisco/ChezScheme#79]
Hello, I'm trying to learn how to debug programs with chezscheme.
In this case I have an exception while loading some code. But I cannot easily find from where the error is coming.  There is some way to show a backtrace to see the context from where the variable is referenced?
Follows my attempt to inspect the code

```
> (load "sdl2.sls")

Exception: variable sdl-pixeltype is not bound
Type (debug) to enter the debugger.
> (debug)
debug> i
#<continuation>                                                   : s
  continuation:          #<system continuation in ksrc>
  call code:             sdl-pixeltype
#<continuation>                 
#<continuation>                                                   : c
source code not available
#<continuation>                                                   : sl
  continuation:          #<system continuation in ksrc>
  call code:             sdl-pixeltype
#<continuation>                                                   : sf
  0: #<continuation>
  1: #<system continuation in ksrc>
  2: #<system continuation>
  3: #<system continuation in dynamic-wind>
  4: #<system continuation in dynamic-wind>
  5: #<system continuation in $reset-protect>
  6: #<system continuation in new-cafe>
#<continuation>                                                   : cp
this frame has no closure

sdl-pixeltype                                                     : ?

   ref(r) .............. inspect value field [n] of symbol
   value(v) ............ inspect top-level-value of symbol
   name(n) ............. inspect name of symbol
   property-list(pl) ... inspect property-list of symbol
   show(s) ............. show fields of symbol
   ?? .................. display more options

sdl-pixeltype                                                     : s
  0. top level value:    #<unbound object>
  1. name:               "sdl-pixeltype"
  2. properties:         ()
```

**Comment by dybvig** [comment]
The inspector shows only what's currently in the continuation, i.e., the calls that still remain to be returned from, and this is often insufficient.  You might find [this document](http://www.cs.indiana.edu/chezscheme/debug/) useful for general debugging tips.  For unbound identifiers, the best advice I can give you is to (re)structure your code into libraries and top-level programs.  Library and program scopes are self-contained, and you get compile-time errors identifying the location of unbound identifiers.  If that's not practical, you can always grep for unbound identifier with relatively unique names, and if the uses aren't obviously unbound, rename one at a time (or half of them at a time, if there are a lot) to something you know to be bound and see if you can narrow it down that way..
