### ISSUE TITLE
No scheme.boot and boot directory for FreeBSD

### ISSUE THREAD

**Issue by eatonphil** [cisco/ChezScheme#8]
I'm running FreeBSD on an x86_64 processor.

Running `./configure` produces:

```
no suitable machine type found
try rerunning as ./configure -m=<machine type>
available machine types: a6le, a6nt, a6osx, i3le, i3nt, i3osx, ta6le, ta6nt, ta6osx, ti3le, ti3nt, and ti3osx
```

However, in the configure file, there are settings that indicate such machine types as "i3fb" and "a6fb". But no such directories exist in `boot/` and running `./configure -m=a6fb` produces the same error as above. This issue applies to at least OpenBSD and perhaps more.

What is a good way to deal with this in order to build on FreeBSD (and others)?

**Comment by dybvig** [comment]
Please see my comment on [issue 7](https://github.com/cisco/ChezScheme/issues/7).
