### ISSUE TITLE
Small error in the CSUG

### ISSUE THREAD

**Issue by olopierpa** [cisco/ChezScheme#802]
In the CSUG, https://cisco.github.io/ChezScheme/csug10.0/io.html#./io:h14

"When print-vector-length is set to a true value, write, put-datum, and pretty-print includes the length for all vectors between the "#" and open parenthesis, all bytevectors between the "#vu8" and open parenthesis, and all fxvectors between the "#vfx" and open parenthesis. "

Actually in the case of {byte|fx}vectors the length is printed after the # and not after #vu8 and #vfx, as the examples show.

**Comment by burgerrg** [comment]
Thanks, this should be fixed in c502a24ffb00f23030374ea09e5b0b4b941aa78d.
