### ISSUE TITLE
Release 10.0.0 .tar.gz does not contain the submodules

### ISSUE THREAD

**Issue by tkurtbond** [cisco/ChezScheme#804]
Despite what the release notes say.

**Comment by mflatt** [comment]
Hi — I wonder whether you were looking at the "Source Code (.tar.gz)" link at https://github.com/cisco/ChezScheme/releases/tag/v10.0.0? That link is automatically put there by GitHub, and it's a snapshot of the repo without submodules. The "csv10.0.0.tar.gz" link is the one with submodules.

**Comment by tkurtbond** [comment]
Ah, that was exactly what happened.  I apologize for my confusion.

**Comment by tkurtbond** [comment]
That worked fine.
