### ISSUE TITLE
Bug in V format prefix parameter

### ISSUE THREAD

**Issue by olopierpa** [cisco/ChezScheme#840]
Hello,

the CSUG says: "Chez Scheme's implementation of format supports all of the Common Lisp format directives except for those specific to the Common Lisp pretty printer."

The CLHS says: "In place of a prefix parameter to a directive, V (or v) can be used."
https://www.lispworks.com/documentation/lw60/CLHS/Body/22_c.htm

However,
```
> (format #f "~vA" 10 10)
"10        "
> (format #f "~VA" 10 10)
Exception in format: unrecognized directive ~V
Type (debug) to enter the debugger.
```

**Comment by burgerrg** [comment]
Fixed in https://github.com/cisco/ChezScheme/pull/843. Thank you for finding and fixing this!
