### ISSUE TITLE
cp0 improvement: kill `call/cc` when the captured procedure is never invoked

### ISSUE THREAD

**Issue by dpk** [cisco/ChezScheme#872]
Chez 10.0.0:

```scheme
> (expand/optimize '(lambda () (call/cc (lambda (k) 'foo))))
(lambda ()
  (#2%call/cc
    (lambda (#{k hjfex6sqm22nfqdreunm4v2sg-0}) 'foo)))
```

Perhaps there is some reason why this optimization is not sound in the general case, but at least here, when `call/cc` is invoked but the captured continuation is provably never invoked, the `call/cc` can be killed. That example should optimize to:

```scheme
(lambda () 'foo)
```

(Alternatively, maybe this optimization happens later on. That would be useful to know, too.)

**Comment by LiberalArtist** [comment]
This was completed in https://github.com/cisco/ChezScheme/commit/b63133797ddace9929d66f68c33bded4cfeea362 and can be closed.
