### ISSUE TITLE
fxdiv-and-mod is slower than the "wrong" way

### ISSUE THREAD

**Issue by mml** [cisco/ChezScheme#891]
```scheme
(define loops (make-parameter (inexact->exact 300e6)))
(define divisor 1000)
(printf "~a loops with divisor ~a~n" (loops) divisor)

(time
  (let multiply-loop ([i (loops)][sum 0])
    (let* ([q (fx/ i divisor)]
           [r (fx- (fx* q divisor))])
      (if (zero? i)
        sum
        (multiply-loop (sub1 i) (+ sum q r))))))

(time
  (let divmod-loop ([i (loops)][sum 0])
    (let-values ([(q r) (fxdiv-and-mod i divisor)])
      (if (zero? i)
        sum
        (divmod-loop (sub1 i) (+ sum q r))))))
```

```console
% scheme --version ; scheme --script div-and-mod.ss
10.1.0
300000000 loops with divisor 1000
(time (let multiply-loop ...))
    no collections
    4.838191199s elapsed cpu time
    4.839586693s elapsed real time
    0 bytes allocated
(time (let divmod-loop ...))
    no collections
    5.124795301s elapsed cpu time
    5.125451247s elapsed real time
    0 bytes allocated
```

Is it extra overhead due to `let-values`?

**Comment by jltaylor-us** [comment]
The value you are computing in the wrong way is... wrong.  As in incorrect.  If you're allowed to get incorrect results then you can be even faster by just returning a constant.

**Comment by mml** [comment]
Whoops, you're right.  In setting up this test case, I made a mistake.  So I corrected [the code](https://github.com/user-attachments/files/18104352/div-and-mod.ss.txt), and then because I suspected the issue might be multiple values, I modified both versions to use call-with-values.

And now it gets weirder.  If I run against the `.ss` file, `fxdiv-and-mod` is faster.  But if I compile with `--optimize-level 3`, my version wins again.  Maybe due to procedure inlining removing the `call-with-values` entirely?

```console
% scheme --script div-and-mod.so
300000000 loops with divisor 1000
(time (let multiply-loop ...))
    no collections
    4.377042967s elapsed cpu time
    4.377222988s elapsed real time
    0 bytes allocated
(time (let divmod-loop ...))
    no collections
    4.982228683s elapsed cpu time
    4.982571173s elapsed real time
    0 bytes allocated
verified for 300000000 values with divisor 1000
(time (check))
    no collections
    0.000005053s elapsed cpu time
    0.000004923s elapsed real time
    2272 bytes allocated
% scheme --script div-and-mod.ss
300000000 loops with divisor 1000
(time (let multiply-loop ...))
    no collections
    5.378710186s elapsed cpu time
    5.378931384s elapsed real time
    0 bytes allocated
(time (let divmod-loop ...))
    no collections
    5.021773160s elapsed cpu time
    5.022052621s elapsed real time
    0 bytes allocated
verified for 300000000 values with divisor 1000
(time (check))
    no collections
    0.000013817s elapsed cpu time
    0.000012730s elapsed real time
    2272 bytes allocated
```

**Comment by jltaylor-us** [comment]
The linked code is still doing the same computation.  Also your check function is missing the recursion so it doesn't actually loop.  Change your loop termination condition so the dividend can be negative and you will see where the values you are computing diverge from the values returned by `div` and `mod`.

**Comment by mml** [comment]
OK, I can see that my version is correct only for nonnegative fixnums.  However, that's a lot of fixnums!  I'll close this issue and file this under "today I learned how div-and-mod really works".  Sorry for the noise!
