### ISSUE TITLE
kernel.o file should also be installed

### ISSUE THREAD

**Issue by ChaosEternal** [cisco/ChezScheme#92]
since kernel.o is important for embedding chez , this kernel.o file should also be installed with boot file.

and should it be made a lib file?

**Comment by ChaosEternal** [comment]
PR #96 is aimed for solving this.

**Comment by abhi18av** [comment]
@ChaosEternal , this is really great! :+1:

**Comment by burgerrg** [comment]
Commit fd7812d05c791e05eb65982c93bd8c36f7a0404f installs equates.h, kernel.o, and main.o on unix-like systems. The Windows install already includes the comparable files.
