### ISSUE TITLE
How to use the (base-exception-handler) ?

### ISSUE THREAD

**Issue by regomne** [cisco/ChezScheme#98]
I'm building an REPL myself. Here is some code:
```
ptr scheme_eval(const char* expr_string)
{
    auto open_input_string = Stop_level_value(Sstring_to_symbol("open-input-string"));
    auto stream = Scall1(open_input_string, Sstring(expr_string));
    auto read = Stop_level_value(Sstring_to_symbol("read"));
    auto expr = Scall1(read, stream);
    auto eval = Stop_level_value(Sstring_to_symbol("eval"));
    return Scall1(eval, expr);
}
```
But when I call:
`scheme_eval("(error 'a 'b)");`
It will exit directly. So I added an exception handler:
`scheme_eval("(base-exception-handler (lambda (x) (display-condition x) (debug)))");`
But in debug console, I can't input "e" or "q", It will raise another exception:
  **Exception occurred with condition components:**
  **0. &non-continuable**

How do I return to the context which calls the scheme_eval, please?

**Comment by dybvig** [comment]
You'll need to capture a continuation that can be invoked by the exception handler.  One way would be to define a function that grabs the continuation and parameterizes the base exception handler, during the call to `eval`, to something that invokes that continuation after `debug` returns,  An easier solution would be to have the function use `guard`.

If you want `debug` to do anything but print "Nothing to debug." and exit, your exception handler should set the `debug-condition` parameter before calling `debug`.

**Comment by regomne** [comment]
Thanks very much.
Now I use call/cc and with-exception-handler to capture exceptions when eval, it works well.
